// COPIED from ilm-red-unbound/packages/api-client by scripts/sync-api-client.mjs. Do not edit here.
// GENERATED by scripts/build-api-client.mjs from api/openapi/*.json. Do not edit by hand;
// change the contract in openapi/ and run `npm run api:spec`.

/* eslint-disable */
export interface paths {
    "/ai/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the models behind each AI feature and their prices
         * @description One row per feature and model the caller may use, with the price per unit in credits and the languages it handles well. Anonymous callers see list prices; a signed-in member sees the models their plan allows. Filter by `feature`.
         */
        get: operations["listAiModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List my AI conversations
         * @description Filter by `book_id`, `club_id` or `post_id`. Sortable by `updated_at` (default, newest first) and `created_at`.
         */
        get: operations["listAiSessions"];
        put?: never;
        /**
         * Start an AI conversation about a book, a club or a post
         * @description The context is exactly one of `book_id`, `club_id` or `post_id`, and the caller must be able to read it (a club session needs membership). A book session may be narrowed to a page range; answers then cite only those pages. Starting a session is free; each question is priced.
         */
        post: operations["createAiSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /**
         * Get a conversation with a page of its messages
         * @description Messages come oldest first. `cursor` and `limit` page through the messages, not the session; the envelope is in `messages`.
         */
        get: operations["getAiSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask a question in a conversation
         * @description Streams the answer as Server-Sent Events by default (`Accept: text/event-stream`). Each event's `event:` line names its type and its `data:` line is one JSON object:
         *
         *     - `token` `{text}`: the next piece of the answer text.
         *     - `citation` `{book_id, page, quote}`: a passage the answer relies on, sent as soon as it is known.
         *     - `usage` `{credits}`: what the answer cost, sent once before `done`.
         *     - `done` `{message_id, question_id}`: the answer is complete and saved.
         *     - `error` `{slug, title}`: the answer failed; nothing is charged for a failed answer.
         *
         *     Send `Accept: application/json` to wait for the whole answer instead. With `?estimate=true` the call returns a `PriceEstimate` as JSON and asks nothing. Credits are reserved when the question is accepted and settled at `usage`.
         */
        post: operations["askAiQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/sessions/{session_id}/messages/{message_id}/rating": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionId"];
                message_id: components["parameters"]["MessageId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rate an answer up or down
         * @description Rating again replaces the earlier rating. Only assistant messages can be rated.
         */
        post: operations["rateAiMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/sessions/{session_id}/messages/{message_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionId"];
                message_id: components["parameters"]["MessageId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish an answer to the book's public Q&A
         * @description Copies the question and this answer, with their citations, to the book's public Q&A under the member's name. Only answers in a book conversation can be published, and each answer once.
         */
        post: operations["publishAiMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/summaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Summarize a chapter or a page range of a book
         * @description A `short` summary of up to 30 pages comes back at once (200). Anything longer is queued and answered with 202 and a run id to poll at `GET /ai/runs/{run_id}`. A summary someone already paid for at the same range, length and language is served from cache and charged at the cache rate.
         */
        post: operations["createAiSummary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/terms/{slug}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        /**
         * Explain a term for a beginner or an expert
         * @description A plain explanation of a glossary term at the chosen level, in the chosen language. Explanations are cached per term, level and language; a cached one costs nothing (`X-Credits-Charged: 0`).
         */
        get: operations["explainTerm"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/translations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Translate a piece of text or a page range of a book
         * @description Send either `{text, source_lang?, target_lang}` (up to 10,000 characters, answered at once) or `{book_id, from, to, target_lang}` for pages of a book the caller can read (queued, 202 with a run id). Pages that already have a translation in `target_lang` are returned without charge. Book translations made here are private to the caller; to publish a translation of a whole book, order one through the Premium API.
         */
        post: operations["createAiTranslation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/council/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Have the AI council review content against a rubric
         * @description Each seat (a model with its own persona) scores the content against every rubric criterion and gives a verdict with reasons; the quorum result is the weighted vote. `seats` defaults to the standing council (usually 4) and is capped at 7. Answered at once; large reviews can take up to a minute.
         */
        post: operations["createAiCouncilReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        /**
         * Get the status and result of a queued AI run
         * @description Poll every few seconds; `result_url` is set once `status` is `done`.
         */
        get: operations["getAiRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the outside agents connected to my account
         * @description Session only: an agent cannot see or change connections. Sortable by `last_used_at` (default, newest first) and `connected_at`.
         */
        get: operations["listAiAgentConnections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Disconnect an agent
         * @description Revokes every token the agent holds for me at once. The agent must go through consent again to reconnect.
         */
        delete: operations["revokeAiAgentConnection"];
        options?: never;
        head?: never;
        /**
         * Change a connected agent's scopes or monthly cap
         * @description Takes effect on the agent's next call. Removing `ai:spend` or lowering the cap below what the agent has spent this month stops its paid calls at once; running work it already queued finishes.
         */
        patch: operations["updateAiAgentConnection"];
        trace?: never;
    };
    "/ai/oauth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register an agent as an OAuth client
         * @description Dynamic client registration (RFC 7591), open to anyone, so an MCP client can connect without a manual sign-up. Registering grants nothing: a member still has to approve the agent at https://ilm.red/connect/authorize, where they choose its scopes and monthly credit cap. Public clients (`token_endpoint_auth_method: none`) must use PKCE (S256). `Idempotency-Key` is optional here because standard RFC 7591 clients do not send it.
         */
        post: operations["registerAiAgentClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/oauth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange an authorization code or refresh token for an access token
         * @description Standard OAuth 2.1 token endpoint (RFC 6749 section 4.1.3 and 6), form-encoded. The code comes from the consent screen at https://ilm.red/connect/authorize and is single use for 60 seconds; `code_verifier` is required (PKCE). Refresh tokens rotate: each use returns a new one and the old one stops working. Confidential clients authenticate with HTTP Basic or `client_secret` in the body. Errors on this endpoint use the OAuth error shape, not problem documents, because OAuth libraries expect it.
         */
        post: operations["exchangeAiAgentToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description An OAuth client id issued by `POST /ai/oauth/register`.
         * @example client_5Rt8Yp2Wd3Nq
         */
        AgentClientId: string;
        /**
         * @description A priced AI feature.
         * @enum {string}
         */
        AiFeature: "ask" | "summarize" | "explain" | "translate" | "council";
        /** @enum {string} */
        AgentScope: "library:read" | "notes:write" | "ai:spend";
        /**
         * @example {
         *       "feature": "summarize",
         *       "model": "claude-sonnet-4-6",
         *       "label": "Claude Sonnet",
         *       "unit": "page",
         *       "credits_per_unit": 0.35,
         *       "langs": [
         *         "en",
         *         "ur",
         *         "ar",
         *         "fa"
         *       ],
         *       "is_default": true
         *     }
         */
        AiModel: {
            feature: components["schemas"]["AiFeature"];
            /** @description The model's public name. */
            model: string;
            /** @description A human name for pickers. */
            label?: string | null;
            /**
             * @description What one unit is.
             * @enum {string}
             */
            unit: "question" | "page" | "1k_chars" | "1k_tokens" | "review" | "explanation";
            credits_per_unit: components["schemas"]["Credits"];
            /** @description Languages the model handles well. Empty means any. */
            langs: components["schemas"]["LangCode"][];
            /** @description Used when the caller names no model. */
            is_default: boolean;
        };
        /** @description What a conversation is grounded in. Exactly one id is set. */
        AiContext: {
            /** @enum {string} */
            kind: "book" | "club" | "post";
            book_id?: components["schemas"]["BookId"];
            club_id?: components["schemas"]["ClubId"];
            post_id?: components["schemas"]["PostId"];
            /** @description The book, club or post title, for display. */
            title?: string;
            page_from?: number | null;
            page_to?: number | null;
        };
        /**
         * @example {
         *       "id": "ses_6Tn3Qa9Lk2Pw",
         *       "title": "Who is Shahrazad?",
         *       "context": {
         *         "kind": "book",
         *         "book_id": "book_2mCq1kZ9xTb4",
         *         "title": "Alf Layla wa-Layla",
         *         "page_from": 1,
         *         "page_to": 40
         *       },
         *       "lang": "en",
         *       "model": "claude-sonnet-4-6",
         *       "message_count": 4,
         *       "credits_spent": 2.4,
         *       "archived": false,
         *       "created_at": "2026-09-22T18:04:05Z",
         *       "updated_at": "2026-09-22T18:09:41Z"
         *     }
         */
        AiSession: {
            id: components["schemas"]["SessionId"];
            title: string;
            context: components["schemas"]["AiContext"];
            lang: components["schemas"]["LangCode"];
            model?: string | null;
            message_count: number;
            credits_spent?: components["schemas"]["Credits"];
            archived: boolean;
            created_at: components["schemas"]["Timestamp"];
            /** Format: date-time */
            updated_at?: string | null;
        };
        AiSessionCreateBook: {
            book_id: components["schemas"]["BookId"];
            page_from?: number;
            /** @description Must be at least `page_from`. */
            page_to?: number;
            title?: string;
            lang?: components["schemas"]["LangCode"];
            /** @description One of the `ask` models from `GET /ai/models`. */
            model?: string;
        };
        AiSessionCreateClub: {
            club_id: components["schemas"]["ClubId"];
            title?: string;
            lang?: components["schemas"]["LangCode"];
            model?: string;
        };
        AiSessionCreatePost: {
            post_id: components["schemas"]["PostId"];
            title?: string;
            lang?: components["schemas"]["LangCode"];
            model?: string;
        };
        /** @description Exactly one of `book_id`, `club_id`, `post_id`. A page range is allowed only with `book_id`. */
        AiSessionCreate: components["schemas"]["AiSessionCreateBook"] | components["schemas"]["AiSessionCreateClub"] | components["schemas"]["AiSessionCreatePost"];
        /** @description A passage an answer relies on. */
        Citation: {
            book_id: components["schemas"]["BookId"];
            page: number;
            quote: string;
        };
        /**
         * @example {
         *       "id": "msg_8Hq2Lm0PzX1a",
         *       "role": "assistant",
         *       "text": "Shahrazad is the vizier's daughter who tells the king a new tale each night.",
         *       "citations": [
         *         {
         *           "book_id": "book_2mCq1kZ9xTb4",
         *           "page": 14,
         *           "quote": "she told him a tale"
         *         }
         *       ],
         *       "rating": "up",
         *       "credits_charged": 1.2,
         *       "agent_id": null,
         *       "published_url": null,
         *       "created_at": "2026-09-22T18:09:41Z"
         *     }
         */
        AiMessage: {
            id: components["schemas"]["MessageId"];
            /** @enum {string} */
            role: "user" | "assistant";
            author?: components["schemas"]["UserSummary"];
            text: string;
            citations?: components["schemas"]["Citation"][];
            /**
             * @description My rating, on assistant messages.
             * @enum {string|null}
             */
            rating?: "up" | "down" | null;
            credits_charged?: components["schemas"]["Credits"];
            /** @description Set when an outside agent asked this question for me. */
            agent_id?: components["schemas"]["AgentId"] | null;
            /**
             * Format: uri
             * @description Where this answer lives in the book's public Q&A, once published.
             */
            published_url?: string | null;
            created_at: components["schemas"]["Timestamp"];
        };
        AiSessionDetail: components["schemas"]["AiSession"] & {
            messages: components["schemas"]["Page"] & {
                data?: components["schemas"]["AiMessage"][];
            };
        };
        AiQuestion: {
            question: string;
            lang?: components["schemas"]["LangCode"];
        };
        /**
         * @description The non-streaming answer.
         * @example {
         *       "question": {
         *         "id": "msg_8Hq2Lm0PzX19",
         *         "role": "user",
         *         "text": "Who is Shahrazad?",
         *         "created_at": "2026-09-22T18:09:38Z"
         *       },
         *       "answer": {
         *         "id": "msg_8Hq2Lm0PzX1a",
         *         "role": "assistant",
         *         "text": "Shahrazad is the vizier's daughter who tells the king a new tale each night.",
         *         "citations": [
         *           {
         *             "book_id": "book_2mCq1kZ9xTb4",
         *             "page": 14,
         *             "quote": "she told him a tale"
         *           }
         *         ],
         *         "credits_charged": 1.2,
         *         "created_at": "2026-09-22T18:09:41Z"
         *       },
         *       "credits_charged": 1.2
         *     }
         */
        AiAnswer: {
            question: components["schemas"]["AiMessage"];
            answer: components["schemas"]["AiMessage"];
            credits_charged: components["schemas"]["Credits"];
        };
        AiStreamToken: {
            text: string;
        };
        AiStreamUsage: {
            credits: components["schemas"]["Credits"];
        };
        AiStreamDone: {
            message_id: components["schemas"]["MessageId"];
            question_id: components["schemas"]["MessageId"];
        };
        AiStreamError: {
            slug: components["schemas"]["ProblemSlug"];
            title: string;
        };
        AiRatingCreate: {
            /** @enum {string} */
            rating: "up" | "down";
            reason?: string;
        };
        /**
         * @example {
         *       "message_id": "msg_8Hq2Lm0PzX1a",
         *       "rating": "down",
         *       "reason": "The citation is from the wrong night.",
         *       "rated_at": "2026-09-22T18:10:02Z"
         *     }
         */
        AiRating: {
            message_id: components["schemas"]["MessageId"];
            /** @enum {string} */
            rating: "up" | "down";
            reason?: string | null;
            rated_at: components["schemas"]["Timestamp"];
        };
        AiPublishRequest: {
            title: string;
            description?: string;
            category?: components["schemas"]["Slug"];
            tags?: string[];
            /**
             * @default public
             * @enum {string}
             */
            visibility: "public" | "members_only";
        };
        /**
         * @example {
         *       "book_id": "book_2mCq1kZ9xTb4",
         *       "message_id": "msg_8Hq2Lm0PzX1a",
         *       "url": "https://ilm.red/books/arabian-nights-one-thousand-and-one-nights/qa/who-is-shahrazad",
         *       "visibility": "public",
         *       "published_at": "2026-09-22T18:12:00Z"
         *     }
         */
        PublishedQuestion: {
            book_id: components["schemas"]["BookId"];
            message_id: components["schemas"]["MessageId"];
            url: components["schemas"]["Url"];
            /** @enum {string} */
            visibility?: "public" | "members_only";
            published_at: components["schemas"]["Timestamp"];
        };
        /**
         * @description `QueuedWork` plus the run id to poll at `GET /ai/runs/{run_id}`.
         * @example {
         *       "job_id": "job_9Pq1Xz4Kd7Lm",
         *       "run_id": "run_4Vb8Nc2Qw6Er",
         *       "status": "queued",
         *       "estimate": {
         *         "credits_low": 12.5,
         *         "credits_high": 18,
         *         "source": "measured"
         *       }
         *     }
         */
        AiRunQueued: components["schemas"]["QueuedWork"] & {
            run_id: components["schemas"]["RunId"];
        };
        /**
         * @example {
         *       "id": "run_4Vb8Nc2Qw6Er",
         *       "feature": "summarize",
         *       "status": "running",
         *       "book_id": "book_2mCq1kZ9xTb4",
         *       "progress": {
         *         "done": 18,
         *         "total": 60,
         *         "percent": 30
         *       },
         *       "result_url": null,
         *       "error": null,
         *       "estimate": {
         *         "credits_low": 12.5,
         *         "credits_high": 18,
         *         "source": "measured"
         *       },
         *       "credits_charged": 4.1,
         *       "agent_id": null,
         *       "created_at": "2026-09-22T18:04:05Z",
         *       "finished_at": null
         *     }
         */
        AiRun: {
            id: components["schemas"]["RunId"];
            feature: components["schemas"]["AiFeature"];
            /** @enum {string} */
            status: "queued" | "running" | "done" | "failed" | "cancelled";
            book_id?: components["schemas"]["BookId"] | null;
            progress: {
                done: number;
                total: number;
                percent?: number;
            };
            /**
             * Format: uri
             * @description Where to fetch the result once `done`.
             */
            result_url?: string | null;
            error?: {
                slug: components["schemas"]["ProblemSlug"];
                title: string;
            } | null;
            estimate?: components["schemas"]["PriceEstimate"];
            credits_charged: components["schemas"]["Credits"];
            agent_id?: components["schemas"]["AgentId"] | null;
            created_at: components["schemas"]["Timestamp"];
            /** Format: date-time */
            finished_at?: string | null;
        };
        /** @enum {string} */
        SummaryLength: "short" | "medium" | "long";
        SummaryRequestChapter: {
            book_id: components["schemas"]["BookId"];
            /** @description 1-based chapter number from the book's table of contents. */
            chapter: number;
            length?: components["schemas"]["SummaryLength"];
            lang?: components["schemas"]["LangCode"];
            model?: string;
        };
        SummaryRequestPages: {
            book_id: components["schemas"]["BookId"];
            from: number;
            /** @description Inclusive; at most 500 pages after `from`. */
            to: number;
            length?: components["schemas"]["SummaryLength"];
            lang?: components["schemas"]["LangCode"];
            model?: string;
        };
        /** @description A chapter, or a page range (`from`, `to`). `length` defaults to `medium`, `lang` to the book's language. */
        SummaryRequest: components["schemas"]["SummaryRequestChapter"] | components["schemas"]["SummaryRequestPages"];
        /**
         * @example {
         *       "book_id": "book_2mCq1kZ9xTb4",
         *       "chapter": 1,
         *       "from": 1,
         *       "to": 14,
         *       "length": "short",
         *       "lang": "en",
         *       "text": "The king, betrayed, marries a new bride each night until Shahrazad begins her tales.",
         *       "model": "claude-sonnet-4-6",
         *       "cached": false,
         *       "credits_charged": 4.9,
         *       "created_at": "2026-09-22T18:04:05Z"
         *     }
         */
        Summary: {
            book_id: components["schemas"]["BookId"];
            chapter?: number | null;
            from: number;
            to: number;
            length: components["schemas"]["SummaryLength"];
            lang: components["schemas"]["LangCode"];
            text: string;
            model?: string | null;
            cached?: boolean;
            credits_charged: components["schemas"]["Credits"];
            created_at: components["schemas"]["Timestamp"];
        };
        /**
         * @example {
         *       "slug": "isnad",
         *       "term": "Isnad",
         *       "level": "beginner",
         *       "lang": "en",
         *       "text": "The chain of people who passed a report on, from the source to the one writing it down.",
         *       "usage_examples": [
         *         "A hadith's isnad names each narrator in turn."
         *       ],
         *       "related": [
         *         "matn",
         *         "hadith"
         *       ],
         *       "model": "claude-sonnet-4-6",
         *       "cached": true
         *     }
         */
        TermExplanation: {
            slug: components["schemas"]["Slug"];
            term: string;
            /** @enum {string} */
            level: "beginner" | "expert";
            lang: components["schemas"]["LangCode"];
            text: string;
            usage_examples?: string[];
            /** @description Slugs of related terms, for follow-up calls. */
            related?: components["schemas"]["Slug"][];
            model?: string | null;
            cached: boolean;
        };
        TextTranslationRequest: {
            text: string;
            source_lang?: components["schemas"]["LangCode"];
            target_lang: components["schemas"]["LangCode"];
            model?: string;
        };
        BookTranslationRequest: {
            book_id: components["schemas"]["BookId"];
            from: number;
            /** @description Inclusive; at most 200 pages after `from`. */
            to: number;
            target_lang: components["schemas"]["LangCode"];
            model?: string;
        };
        /** @description Either a piece of text or a page range of a book the caller can read. */
        TranslationRequest: components["schemas"]["TextTranslationRequest"] | components["schemas"]["BookTranslationRequest"];
        /**
         * @example {
         *       "source_lang": "ur",
         *       "detected": true,
         *       "target_lang": "en",
         *       "text": "Knowledge is a treasure whose key is the question.",
         *       "model": "claude-sonnet-4-6",
         *       "credits_charged": 0.2
         *     }
         */
        TextTranslation: {
            source_lang: components["schemas"]["LangCode"];
            /** @description True when `source_lang` was detected rather than given. */
            detected?: boolean;
            target_lang: components["schemas"]["LangCode"];
            text: string;
            model?: string | null;
            credits_charged: components["schemas"]["Credits"];
        };
        CouncilReviewRequest: {
            content: string;
            /**
             * @default markdown
             * @enum {string}
             */
            content_type: "text" | "markdown";
            rubric: {
                criterion: string;
                /** @default 1 */
                weight: number;
            }[];
            seats?: number;
            lang?: components["schemas"]["LangCode"];
        };
        /** @enum {string} */
        CouncilVerdict: "approve" | "revise" | "reject";
        CouncilSeatReview: {
            seat: number;
            /** @description The seat's role, e.g. Skeptic or Editor. */
            persona: string;
            model: string;
            verdict: components["schemas"]["CouncilVerdict"];
            score: number;
            reasons: string[];
            criteria?: {
                criterion: string;
                score: number;
                note?: string | null;
            }[];
        };
        /**
         * @example {
         *       "seats": [
         *         {
         *           "seat": 1,
         *           "persona": "Skeptic",
         *           "model": "claude-opus-4-6",
         *           "verdict": "revise",
         *           "score": 64,
         *           "reasons": [
         *             "The second claim has no source."
         *           ],
         *           "criteria": [
         *             {
         *               "criterion": "Every claim is sourced",
         *               "score": 50,
         *               "note": "Two claims unsourced."
         *             }
         *           ]
         *         },
         *         {
         *           "seat": 2,
         *           "persona": "Editor",
         *           "model": "gpt-5",
         *           "verdict": "approve",
         *           "score": 81,
         *           "reasons": [
         *             "Clear and well ordered."
         *           ]
         *         }
         *       ],
         *       "quorum": {
         *         "reached": false,
         *         "verdict": "revise",
         *         "score": 72.5,
         *         "agreeing_seats": 1,
         *         "required_seats": 2
         *       },
         *       "credits_charged": 6.3
         *     }
         */
        CouncilReview: {
            seats: components["schemas"]["CouncilSeatReview"][];
            quorum: {
                /** @description False when no verdict had the required majority; `verdict` is then the plurality. */
                reached: boolean;
                verdict: components["schemas"]["CouncilVerdict"];
                /** @description Weighted mean of the seats' scores. */
                score: number;
                agreeing_seats: number;
                required_seats: number;
            };
            credits_charged: components["schemas"]["Credits"];
        };
        /**
         * @example {
         *       "id": "agent_1Zx7Cv3Bn9Mq",
         *       "name": "Claude",
         *       "client": {
         *         "client_id": "client_5Rt8Yp2Wd3Nq",
         *         "name": "Claude",
         *         "client_uri": "https://claude.ai",
         *         "logo_uri": null
         *       },
         *       "scopes": [
         *         "library:read",
         *         "notes:write",
         *         "ai:spend"
         *       ],
         *       "monthly_cap_credits": 500,
         *       "spent_this_month": 42.75,
         *       "cap_resets_at": "2026-10-01T00:00:00Z",
         *       "last_used_at": "2026-09-22T17:55:10Z",
         *       "connected_at": "2026-09-02T09:30:00Z"
         *     }
         */
        AgentConnection: {
            id: components["schemas"]["AgentId"];
            /** @description The name the agent registered with. */
            name: string;
            client: {
                client_id: components["schemas"]["AgentClientId"];
                name: string;
                /** Format: uri */
                client_uri?: string | null;
                /** Format: uri */
                logo_uri?: string | null;
            };
            scopes: components["schemas"]["AgentScope"][];
            monthly_cap_credits: components["schemas"]["Credits"];
            spent_this_month: components["schemas"]["Credits"];
            cap_resets_at: components["schemas"]["Timestamp"];
            /** Format: date-time */
            last_used_at?: string | null;
            connected_at: components["schemas"]["Timestamp"];
        };
        AgentConnectionPatch: {
            scopes?: components["schemas"]["AgentScope"][];
            monthly_cap_credits?: number;
        };
        AgentClientRegistration: {
            client_name: string;
            /** @description HTTPS URLs, or http://127.0.0.1 / http://localhost loopback URLs for native clients. Exact match at authorize time. */
            redirect_uris: string[];
            /**
             * @default [
             *       "authorization_code",
             *       "refresh_token"
             *     ]
             */
            grant_types: ("authorization_code" | "refresh_token")[];
            /**
             * @default [
             *       "code"
             *     ]
             */
            response_types: "code"[];
            /**
             * @default none
             * @enum {string}
             */
            token_endpoint_auth_method: "none" | "client_secret_basic" | "client_secret_post";
            /** @description Space-separated scopes the agent may ask for. The member still chooses at consent. */
            scope?: string;
            /** Format: uri */
            client_uri?: string;
            /** Format: uri */
            logo_uri?: string;
            software_id?: string;
            software_version?: string;
        };
        /**
         * @example {
         *       "client_id": "client_5Rt8Yp2Wd3Nq",
         *       "client_id_issued_at": 1790100000,
         *       "client_name": "Claude",
         *       "redirect_uris": [
         *         "https://claude.ai/api/mcp/auth_callback"
         *       ],
         *       "grant_types": [
         *         "authorization_code",
         *         "refresh_token"
         *       ],
         *       "token_endpoint_auth_method": "none",
         *       "scope": "library:read notes:write ai:spend"
         *     }
         */
        AgentClient: {
            client_id: components["schemas"]["AgentClientId"];
            /** @description Only for confidential clients, and only in this response. */
            client_secret?: string;
            /** @description Unix seconds. */
            client_id_issued_at: number;
            /** @description 0 means it does not expire. */
            client_secret_expires_at?: number;
            client_name: string;
            redirect_uris: string[];
            grant_types: ("authorization_code" | "refresh_token")[];
            /** @enum {string} */
            token_endpoint_auth_method: "none" | "client_secret_basic" | "client_secret_post";
            scope?: string;
        };
        AgentTokenAuthorizationCode: {
            /** @constant */
            grant_type: "authorization_code";
            code: string;
            /** Format: uri */
            redirect_uri: string;
            client_id: components["schemas"]["AgentClientId"];
            client_secret?: string;
            code_verifier: string;
        };
        AgentTokenRefresh: {
            /** @constant */
            grant_type: "refresh_token";
            refresh_token: string;
            client_id: components["schemas"]["AgentClientId"];
            client_secret?: string;
            /** @description Ask for fewer scopes than granted. Never more. */
            scope?: string;
        };
        /** @description Form-encoded. One of the two grants. */
        AgentTokenRequest: components["schemas"]["AgentTokenAuthorizationCode"] | components["schemas"]["AgentTokenRefresh"];
        /**
         * @example {
         *       "access_token": "ilm_at_9fK2mQ7xL0pR4tW8",
         *       "token_type": "Bearer",
         *       "expires_in": 3600,
         *       "refresh_token": "ilm_rt_3Hd6Vb1Nc8Zq5Ys2",
         *       "scope": "library:read notes:write",
         *       "agent_id": "agent_1Zx7Cv3Bn9Mq"
         *     }
         */
        AgentToken: {
            access_token: string;
            /** @constant */
            token_type: "Bearer";
            /** @description Seconds; one hour. */
            expires_in: number;
            /** @description Rotates on every use. */
            refresh_token: string;
            /** @description The scopes the member granted, space-separated. May be fewer than asked for. */
            scope: string;
            agent_id: components["schemas"]["AgentId"];
        };
        /** @description RFC 6749 section 5.2 error. */
        OAuthError: {
            /** @enum {string} */
            error: "invalid_request" | "invalid_client" | "invalid_grant" | "unauthorized_client" | "unsupported_grant_type" | "invalid_scope";
            error_description?: string;
        };
        /** @example book_2mCq1kZ9xTb4 */
        BookId: string;
        /** @example club_7Kd0Wq2Rf1Ab */
        ClubId: string;
        /** @example post_3Kf9Wq1Rb7Zc */
        PostId: string;
        /** @description Every list returns this envelope. `next_cursor` is null on the last page. */
        Page: {
            data: unknown[];
            next_cursor: string | null;
        };
        /** @description RFC 9457 problem document. Branch on `slug` (also the last segment of `type`), show `title`, quote `request_id`. */
        Problem: {
            /**
             * Format: uri
             * @example https://api.ilm.red/problems/not_found
             */
            type: string;
            slug: components["schemas"]["ProblemSlug"];
            title: string;
            status: number;
            detail?: string;
            request_id: string;
        };
        /** @description What a call will cost before it runs. `low` and `high` are null when the kind has never been measured. */
        PriceEstimate: {
            credits_low: number | null;
            credits_high: number | null;
            /** @enum {string} */
            source: "measured" | "kind_spread" | "uncalibrated";
        };
        SessionId: string;
        MessageId: string;
        RunId: string;
        AgentId: string;
        ValidationProblem: components["schemas"]["Problem"] & {
            errors: components["schemas"]["FieldError"][];
        };
        /**
         * @description The stable part of a problem. Branch on this, never on `title` or `detail`.
         * @enum {string}
         */
        ProblemSlug: "unauthorized" | "key_invalid" | "key_revoked" | "key_expired" | "scope_missing" | "not_club_admin" | "club_quota_reached" | "internal_only" | "not_found" | "term_not_found" | "slug_exists" | "edge_would_cycle" | "drop_not_ready" | "needs_text" | "needs_pages" | "needs_translation" | "paper_locked" | "term_has_edges" | "paper_not_in_club" | "revision_required" | "plan_refused" | "duplicate_brief" | "review_forbidden" | "already_reviewed" | "club_required" | "brief_invalid" | "cost_cap_exceeded" | "repair_invalid" | "idempotency_conflict" | "validation_failed" | "unsupported_kind" | "rate_limited" | "extract_rate_limited" | "internal_error" | "forbidden" | "premium_required" | "insufficient_credits" | "reauth_required" | "version_conflict" | "conflict" | "gone" | "payload_too_large" | "unsupported_media_type" | "quote_expired" | "agent_cap_reached" | "lock_held";
        CreditsProblem: components["schemas"]["Problem"] & {
            balance: components["schemas"]["Credits"];
            required_credits: components["schemas"]["Credits"];
            shortfall: components["schemas"]["Credits"];
            top_up_url?: components["schemas"]["Url"];
        };
        /**
         * @description Lowercase words joined by hyphens.
         * @example arabian-nights-one-thousand-and-one-nights
         */
        Slug: string;
        /**
         * @description BCP 47 language tag.
         * @example ur
         * @example en
         * @example ar
         */
        LangCode: string;
        /** @description Credits, rounded by the server to four decimal places. One credit is one US cent of model spend at list price. */
        Credits: number;
        /**
         * Format: date-time
         * @example 2026-09-22T18:04:05Z
         */
        Timestamp: string;
        /** @example user_4Fq9ZtW1Lm8K */
        UserId: string;
        /** @example bilgrami */
        Username: string;
        /** @description How a person appears anywhere they are named. Never an email. */
        UserSummary: {
            id: components["schemas"]["UserId"];
            username: components["schemas"]["Username"];
            display_name: string;
            /** Format: uri */
            avatar_url?: string | null;
        };
        /** Format: uri */
        Url: string;
        JobId: string;
        /** @description Returned with 202 by anything that runs longer than a request. */
        QueuedWork: {
            job_id: components["schemas"]["JobId"];
            /** @enum {string} */
            status: "queued" | "running" | "done" | "failed" | "cancelled";
            estimate?: components["schemas"]["PriceEstimate"];
        };
        FieldError: {
            /**
             * @description Where the problem is, as a JSON Pointer into the request, prefixed with its part.
             * @example /body/title
             * @example /query/limit
             * @example /path/book_id
             * @example /header/Idempotency-Key
             */
            path: string;
            /**
             * @description Which rule failed.
             * @enum {string}
             */
            code: "required" | "type" | "enum" | "const" | "pattern" | "format" | "min_length" | "max_length" | "minimum" | "maximum" | "multiple_of" | "min_items" | "max_items" | "unique_items" | "unknown_field" | "one_of";
            /** @example must be at most 200 characters */
            message: string;
            /** @description The limit that was broken, when the rule has one (a length, a bound, the allowed values). */
            limit?: unknown;
        };
    };
    responses: {
        /** @description The request failed validation (`validation_failed`). `errors` lists every failing field, not just the first. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ValidationProblem"];
            };
        };
        /** @description Too many requests (`rate_limited`). Retry after the `Retry-After` header. */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No credential, or a credential that is not valid (`unauthorized`, `key_invalid`, `key_revoked`, `key_expired`, `reauth_required`). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The caller is known but may not do this (`forbidden`, `scope_missing`, `premium_required`, `internal_only`). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No such resource, or one the caller may not see (`not_found`). The two are deliberately indistinguishable. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Not enough credits (`insufficient_credits`), with the shortfall. */
        PaymentRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["CreditsProblem"];
            };
        };
        /** @description Done. No body. */
        NoContent: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: {
        SessionId: components["schemas"]["SessionId"];
        MessageId: components["schemas"]["MessageId"];
        RunId: components["schemas"]["RunId"];
        AgentId: components["schemas"]["AgentId"];
        /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
        Cursor: string;
        /** @description Page size. */
        Limit: number;
        /** @description A field name, prefixed with `-` for descending. Each list documents the fields it allows. */
        Sort: string;
        /** @description Required on this call because it creates something or spends credits. See IdempotencyKey. */
        IdempotencyKeyRequired: string;
        /** @description When true, return the price of the call and run nothing. */
        Estimate: boolean;
        /** @description Replay protection for 24 hours. The same key with the same body replays the first response; the same key with a different body is refused with `idempotency_conflict`. */
        IdempotencyKey: string;
        Slug: components["schemas"]["Slug"];
        /** @description BCP 47 language tag. A missing translation falls back to the original text plus `available_langs`. */
        Lang: components["schemas"]["LangCode"];
    };
    requestBodies: never;
    headers: {
        /** @description URL of the resource just created. */
        Location: string;
        /** @description Credits this call spent. Present on every paid response, `0` for estimates. */
        CreditsCharged: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAiModels: {
        parameters: {
            query?: {
                feature?: components["schemas"]["AiFeature"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The models, grouped by nothing; one row per feature and model. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AiModel"][];
                    };
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    listAiSessions: {
        parameters: {
            query?: {
                book_id?: components["schemas"]["BookId"];
                club_id?: components["schemas"]["ClubId"];
                post_id?: components["schemas"]["PostId"];
                include_archived?: boolean;
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
                /** @description A field name, prefixed with `-` for descending. Each list documents the fields it allows. */
                sort?: components["parameters"]["Sort"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of conversations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["AiSession"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    createAiSession: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on this call because it creates something or spends credits. See IdempotencyKey. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiSessionCreate"];
            };
        };
        responses: {
            /** @description The new conversation. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The book has no text to ground answers in yet (`needs_text`), or the page range is past the end of the book (`conflict`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    getAiSession: {
        parameters: {
            query?: {
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The conversation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiSessionDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    askAiQuestion: {
        parameters: {
            query?: {
                /** @description When true, return the price of the call and run nothing. */
                estimate?: components["parameters"]["Estimate"];
            };
            header: {
                /** @description Required on this call because it creates something or spends credits. See IdempotencyKey. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiQuestion"];
            };
        };
        responses: {
            /** @description The answer: an event stream, or with `Accept: application/json` the finished answer (or a `PriceEstimate` when `estimate=true`). */
            200: {
                headers: {
                    "X-Credits-Charged": components["headers"]["CreditsCharged"];
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                    "application/json": components["schemas"]["AiAnswer"] | components["schemas"]["PriceEstimate"];
                };
            };
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The conversation is archived (`conflict`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    rateAiMessage: {
        parameters: {
            query?: never;
            header?: {
                /** @description Replay protection for 24 hours. The same key with the same body replays the first response; the same key with a different body is refused with `idempotency_conflict`. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                session_id: components["parameters"]["SessionId"];
                message_id: components["parameters"]["MessageId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiRatingCreate"];
            };
        };
        responses: {
            /** @description The rating as stored. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiRating"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description The message is a question, not an answer (`conflict`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    publishAiMessage: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on this call because it creates something or spends credits. See IdempotencyKey. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path: {
                session_id: components["parameters"]["SessionId"];
                message_id: components["parameters"]["MessageId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiPublishRequest"];
            };
        };
        responses: {
            /** @description Published. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishedQuestion"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Already published, not an answer, or the conversation is not about a book (`conflict`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    createAiSummary: {
        parameters: {
            query?: {
                /** @description When true, return the price of the call and run nothing. */
                estimate?: components["parameters"]["Estimate"];
            };
            header: {
                /** @description Required on this call because it creates something or spends credits. See IdempotencyKey. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SummaryRequest"];
            };
        };
        responses: {
            /** @description The summary, or a `PriceEstimate` when `estimate=true`. */
            200: {
                headers: {
                    "X-Credits-Charged": components["headers"]["CreditsCharged"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"] | components["schemas"]["PriceEstimate"];
                };
            };
            /** @description Queued. Poll the run. */
            202: {
                headers: {
                    "X-Credits-Charged": components["headers"]["CreditsCharged"];
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiRunQueued"];
                };
            };
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The pages have no text yet (`needs_text`), or the chapter or range is outside the book (`conflict`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    explainTerm: {
        parameters: {
            query: {
                level: "beginner" | "expert";
                /** @description BCP 47 language tag. A missing translation falls back to the original text plus `available_langs`. */
                lang?: components["parameters"]["Lang"];
                /** @description When true, return the price of the call and run nothing. */
                estimate?: components["parameters"]["Estimate"];
            };
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The explanation, or a `PriceEstimate` when `estimate=true`. */
            200: {
                headers: {
                    "X-Credits-Charged": components["headers"]["CreditsCharged"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermExplanation"] | components["schemas"]["PriceEstimate"];
                };
            };
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            /** @description No published term with this slug (`term_not_found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    createAiTranslation: {
        parameters: {
            query?: {
                /** @description When true, return the price of the call and run nothing. */
                estimate?: components["parameters"]["Estimate"];
            };
            header: {
                /** @description Required on this call because it creates something or spends credits. See IdempotencyKey. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslationRequest"];
            };
        };
        responses: {
            /** @description The translated text, or a `PriceEstimate` when `estimate=true`. */
            200: {
                headers: {
                    "X-Credits-Charged": components["headers"]["CreditsCharged"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextTranslation"] | components["schemas"]["PriceEstimate"];
                };
            };
            /** @description Book pages queued. Poll the run. */
            202: {
                headers: {
                    "X-Credits-Charged": components["headers"]["CreditsCharged"];
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiRunQueued"];
                };
            };
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The pages have no text yet (`needs_text`), or the range is outside the book (`conflict`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    createAiCouncilReview: {
        parameters: {
            query?: {
                /** @description When true, return the price of the call and run nothing. */
                estimate?: components["parameters"]["Estimate"];
            };
            header: {
                /** @description Required on this call because it creates something or spends credits. See IdempotencyKey. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CouncilReviewRequest"];
            };
        };
        responses: {
            /** @description Every seat's review and the quorum result, or a `PriceEstimate` when `estimate=true`. */
            200: {
                headers: {
                    "X-Credits-Charged": components["headers"]["CreditsCharged"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CouncilReview"] | components["schemas"]["PriceEstimate"];
                };
            };
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["PaymentRequired"];
            403: components["responses"]["Forbidden"];
            /** @description The content is over 50,000 characters (`payload_too_large`). */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    getAiRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiRun"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listAiAgentConnections: {
        parameters: {
            query?: {
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
                /** @description A field name, prefixed with `-` for descending. Each list documents the fields it allows. */
                sort?: components["parameters"]["Sort"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of connections. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["AgentConnection"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    revokeAiAgentConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateAiAgentConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentConnectionPatch"];
            };
        };
        responses: {
            /** @description The updated connection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentConnection"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    registerAiAgentClient: {
        parameters: {
            query?: never;
            header?: {
                /** @description Replay protection for 24 hours. The same key with the same body replays the first response; the same key with a different body is refused with `idempotency_conflict`. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentClientRegistration"];
            };
        };
        responses: {
            /** @description The registered client. `client_secret` is shown only here. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentClient"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    exchangeAiAgentToken: {
        parameters: {
            query?: never;
            header?: {
                /** @description Replay protection for 24 hours. The same key with the same body replays the first response; the same key with a different body is refused with `idempotency_conflict`. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["AgentTokenRequest"];
            };
        };
        responses: {
            /** @description A token for the member who approved this agent. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentToken"];
                };
            };
            /** @description The grant is invalid, expired, already used or revoked (`invalid_grant`), or the request is malformed (`invalid_request`, `unsupported_grant_type`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthError"];
                };
            };
            /** @description Client authentication failed (`invalid_client`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthError"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
}
