// COPIED from ilm-red-unbound/packages/api-client by scripts/sync-api-client.mjs. Do not edit here.
// GENERATED by scripts/build-api-client.mjs from api/openapi/*.json. Do not edit by hand;
// change the contract in openapi/ and run `npm run api:spec`.

/* eslint-disable */
export interface paths {
    "/blog/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List published posts
         * @description Published posts only, one entry per post in the requested `lang` (falling back to the original). Filter by `category`, `tag`, `author` (username) and `q` (full-text search over title, excerpt and body). Sortable by `published_at` (default, newest first), `like_count`, `view_count`, `comment_count`, and `relevance` when `q` is given.
         */
        get: operations["listBlogFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blog/feed/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a published post
         * @description The post as a reader sees it, with its content, in `lang` when that edition exists and in the original otherwise (`available_langs` lists the editions). Drafts and unpublished posts answer `not_found`; authors read their own drafts through the studio.
         */
        get: operations["getPublishedBlogPost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blog/feed/by-slug/{username}/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a published post by its web address
         * @description Resolves `/blog/<username>/<slug>`. When the address is current, 200 with the post. When the slug or the username has changed since, 301 with a `Location` header and a `moved` body carrying the canonical path, so a client that does not follow redirects can still update its link. Old slugs redirect for as long as the post exists.
         */
        get: operations["resolveBlogPost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blog/authors/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** An author's public page */
        get: operations["getBlogAuthor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blog/authors/{username}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * An author's published posts
         * @description Sortable by `published_at` (default, newest first), `like_count` and `view_count`.
         */
        get: operations["listBlogAuthorPosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blog/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Blog categories with post counts
         * @description The 21 library categories, each with how many published posts it holds. Not paged; categories with no posts are included with `post_count` 0.
         */
        get: operations["listBlogCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blog/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Blog tags with post counts
         * @description `q` matches the start of the tag name. Sortable by `post_count` (default, largest first) and `name`.
         */
        get: operations["listBlogTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blog/posts/{post_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The narrated audio of a post
         * @description A signed, short-lived URL for the narration in `lang` (the original when omitted), with its duration and chapter marks. `status: stale` means the text changed after the narration was recorded; the audio still plays and a new take is on its way. `status: none` means there is no narration in that language; `available_langs` lists the ones that exist.
         */
        get: operations["getBlogPostAudio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blog/posts/{post_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        /**
         * A post's comments, with their replies
         * @description Top-level comments, each carrying its replies (one level only) in `replies`. Comments held for moderation are shown to their authors only. Sortable by `created_at` (default, oldest first) or `-created_at`.
         */
        get: operations["listBlogComments"];
        put?: never;
        /**
         * Comment on a post, or reply to a comment
         * @description `parent_id` makes it a reply; a reply to a reply is refused (`validation_failed` on `/body/parent_id`), since threads are one level deep. First comments from new accounts may be held for moderation (`status: pending`).
         */
        post: operations["createBlogComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blog/posts/{post_id}/comments/{comment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: components["parameters"]["PostId"];
                comment_id: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete my comment
         * @description Own comments only. A comment with replies becomes a "deleted" placeholder so the replies keep their place.
         */
        delete: operations["deleteBlogComment"];
        options?: never;
        head?: never;
        /**
         * Edit my comment
         * @description Own comments only. The comment shows `edited_at` afterwards.
         */
        patch: operations["updateBlogComment"];
        trace?: never;
    };
    "/blog/posts/{post_id}/comments/{comment_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report a comment to the moderators
         * @description One report per member per comment; reporting again updates the reason. Moderators act on it from the Admin surface.
         */
        post: operations["reportBlogComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blog/posts/{post_id}/like": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Like a post
         * @description Idempotent; liking twice is not an error.
         */
        put: operations["likeBlogPost"];
        post?: never;
        /** Remove my like from a post */
        delete: operations["unlikeBlogPost"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blog/posters/{poster_id}/like": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                poster_id: components["parameters"]["PosterId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Like a blog poster
         * @description Idempotent; liking twice is not an error.
         */
        put: operations["likeBlogPoster"];
        post?: never;
        /** Remove my like from a blog poster */
        delete: operations["unlikeBlogPoster"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blog/posts/{post_id}/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Count a read
         * @description Call once when a reader opens a post. Views are de-duplicated per `visit_id` (one per browser or app session) for 24 hours, so a reload never counts twice. Signed-in and anonymous readers alike; the caller's IP address is used only for abuse limits and is not stored with the view.
         */
        post: operations["recordBlogPostView"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blog/posts/{post_id}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report a problem in a post
         * @description Tell the author and the blog team what is wrong and where: a broken layout, a wrong fact, a figure that does not render, a quiz that does not answer. `where` pins it to a section or a figure. To attach a screenshot, send `screenshot` and PUT the image to the returned `screenshot_upload` ticket (PNG, JPEG or WebP, up to 5 MB); the report is filed either way. The reporter is emailed when the report is closed, and can follow it in `GET /me/reports`.
         */
        post: operations["createBlogReaderReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blog/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My drafts and posts in the studio
         * @description The caller's own posts in every state. Editors may pass `author` to see another author's. Filter by `status`. Sortable by `updated_at` (default, newest first), `created_at` and `title`.
         */
        get: operations["listBlogDrafts"];
        put?: never;
        /**
         * Start a new draft
         * @description The caller becomes the author and holds the draft lock at once (`lock` in the response). `slug` defaults to one made from the title; a slug the author already uses answers `slug_exists`.
         */
        post: operations["createBlogDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blog/drafts/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        /**
         * Open a draft
         * @description The full draft with its current lock holder. The `ETag` is the version to send in `If-Match` on the next save. When the draft was based on a published version that has since changed, it is rebased first and `rebased` is true.
         */
        get: operations["getBlogDraft"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Save a draft
         * @description Needs both `If-Match` (the version last read) and `X-Draft-Lock` (the token from taking the lock). Someone else holding the lock answers 409 `lock_held` with the holder and when the lock expires; a save that lost a race answers 412 `version_conflict`. Every save writes a revision. Changing the slug of a published post keeps the old address redirecting.
         */
        patch: operations["updateBlogDraft"];
        trace?: never;
    };
    "/blog/drafts/{post_id}/lock": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Take, renew or steal the draft lock
         * @description A lock lasts 5 minutes. Calling again with your current `X-Draft-Lock` renews it (send this every minute or two while the editor is open). Another holder answers 409 `lock_held`; `steal: true` takes the lock anyway (the author and editors only) and the previous holder's next save gets `lock_held`.
         */
        post: operations["acquireBlogDraftLock"];
        /**
         * Release the draft lock
         * @description Call when the editor closes. Releasing a lock that already expired or passed to someone else is not an error.
         */
        delete: operations["releaseBlogDraftLock"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blog/drafts/{post_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A draft's revision history
         * @description Newest first. Content is not included; restore a revision to see it in the editor.
         */
        get: operations["listBlogDraftRevisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blog/drafts/{post_id}/revisions/{revision_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore an earlier revision
         * @description Puts the revision's title, excerpt and content back into the draft as a NEW revision, so nothing is lost and a restore can itself be undone. Needs the lock and `If-Match`, like a save.
         */
        post: operations["restoreBlogDraftRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example poster_1Vb8Zr3Kq6Tw */
        PosterId: string;
        /** @example revision_4Nc7Hx2Pd9Sm */
        RevisionId: string;
        LockToken: string;
        /** @enum {string} */
        DraftStatus: "draft" | "in_review" | "scheduled" | "published" | "archived";
        TagRef: {
            slug: components["schemas"]["Slug"];
            name: string;
            color?: string | null;
        };
        LangEdition: {
            lang: components["schemas"]["LangCode"];
            title: string;
            has_audio: boolean;
            audio_seconds?: number | null;
        };
        /**
         * @description A published post as it appears in a list.
         * @example {
         *       "id": "post_3Kf9Wq1Rb7Zc",
         *       "slug": "arabian-nights-one-thousand-and-one-nights",
         *       "canonical_path": "/blog/bilgrami/arabian-nights-one-thousand-and-one-nights",
         *       "lang": "en",
         *       "title": "One Thousand and One Nights: the frame that saved a life",
         *       "excerpt": "Shahrazad's stories were never the point. The frame was.",
         *       "featured_image_url": "https://cdn.ilm.red/blog/post_3Kf9Wq1Rb7Zc/hero.webp",
         *       "author": {
         *         "id": "user_4Fq9ZtW1Lm8K",
         *         "username": "bilgrami",
         *         "display_name": "Syed Bilgrami",
         *         "avatar_url": null
         *       },
         *       "categories": [
         *         {
         *           "slug": "fiction",
         *           "name": "Fiction",
         *           "emoji": "📖"
         *         }
         *       ],
         *       "tags": [
         *         {
         *           "slug": "storytelling",
         *           "name": "Storytelling",
         *           "color": "#8a4fff"
         *         }
         *       ],
         *       "reading_minutes": 12,
         *       "has_audio": true,
         *       "is_featured": false,
         *       "is_pinned": false,
         *       "like_count": 88,
         *       "comment_count": 14,
         *       "view_count": 3120,
         *       "published_at": "2026-09-01T06:00:00Z"
         *     }
         */
        PostCard: {
            id: components["schemas"]["PostId"];
            slug: components["schemas"]["Slug"];
            canonical_path: string;
            lang: components["schemas"]["LangCode"];
            title: string;
            excerpt?: string | null;
            /** Format: uri */
            featured_image_url?: string | null;
            author: components["schemas"]["UserSummary"];
            categories?: components["schemas"]["CategoryRef"][];
            tags?: components["schemas"]["TagRef"][];
            reading_minutes?: number | null;
            has_audio?: boolean;
            is_featured?: boolean;
            is_pinned?: boolean;
            like_count?: number;
            comment_count?: number;
            view_count?: number;
            published_at: components["schemas"]["Timestamp"];
        };
        /**
         * @description A published post with its content. `content_html` is sanitised HTML for the requested language; `requested_lang` differs from `lang` when the requested edition does not exist.
         * @example {
         *       "id": "post_3Kf9Wq1Rb7Zc",
         *       "slug": "arabian-nights-one-thousand-and-one-nights",
         *       "canonical_path": "/blog/bilgrami/arabian-nights-one-thousand-and-one-nights",
         *       "lang": "ur",
         *       "requested_lang": "ur",
         *       "title": "الف لیلہ و لیلہ",
         *       "excerpt": "شہرزاد کی کہانیاں اصل بات نہیں تھیں۔",
         *       "content_html": "<article><h2>…</h2><p>…</p></article>",
         *       "featured_image_url": "https://cdn.ilm.red/blog/post_3Kf9Wq1Rb7Zc/hero.webp",
         *       "author": {
         *         "id": "user_4Fq9ZtW1Lm8K",
         *         "username": "bilgrami",
         *         "display_name": "Syed Bilgrami",
         *         "avatar_url": null
         *       },
         *       "categories": [
         *         {
         *           "slug": "fiction",
         *           "name": "Fiction",
         *           "emoji": "📖"
         *         }
         *       ],
         *       "tags": [
         *         {
         *           "slug": "storytelling",
         *           "name": "Storytelling",
         *           "color": "#8a4fff"
         *         }
         *       ],
         *       "available_langs": [
         *         {
         *           "lang": "en",
         *           "title": "One Thousand and One Nights: the frame that saved a life",
         *           "has_audio": true,
         *           "audio_seconds": 1432
         *         },
         *         {
         *           "lang": "ur",
         *           "title": "الف لیلہ و لیلہ",
         *           "has_audio": true,
         *           "audio_seconds": 1510
         *         }
         *       ],
         *       "reading_minutes": 12,
         *       "word_count": 2890,
         *       "like_count": 88,
         *       "comment_count": 14,
         *       "view_count": 3120,
         *       "liked_by_me": false,
         *       "comments_open": true,
         *       "published_at": "2026-09-01T06:00:00Z",
         *       "updated_at": "2026-09-03T10:20:00Z"
         *     }
         */
        PublishedPost: {
            id: components["schemas"]["PostId"];
            slug: components["schemas"]["Slug"];
            canonical_path: string;
            lang: components["schemas"]["LangCode"];
            requested_lang: components["schemas"]["LangCode"];
            title: string;
            excerpt?: string | null;
            content_html: string;
            /** Format: uri */
            featured_image_url?: string | null;
            author: components["schemas"]["UserSummary"];
            categories?: components["schemas"]["CategoryRef"][];
            tags?: components["schemas"]["TagRef"][];
            available_langs: components["schemas"]["LangEdition"][];
            reading_minutes?: number | null;
            word_count?: number | null;
            like_count?: number;
            comment_count?: number;
            view_count?: number;
            /** @description Always false for anonymous callers. */
            liked_by_me: boolean;
            comments_open?: boolean;
            published_at: components["schemas"]["Timestamp"];
            /** Format: date-time */
            updated_at?: string | null;
        };
        /**
         * @example {
         *       "moved": true,
         *       "post_id": "post_3Kf9Wq1Rb7Zc",
         *       "canonical_path": "/blog/bilgrami/arabian-nights-one-thousand-and-one-nights"
         *     }
         */
        PostMoved: {
            /** @constant */
            moved: true;
            post_id: components["schemas"]["PostId"];
            canonical_path: string;
        };
        /**
         * @example {
         *       "user": {
         *         "id": "user_4Fq9ZtW1Lm8K",
         *         "username": "bilgrami",
         *         "display_name": "Syed Bilgrami",
         *         "avatar_url": null
         *       },
         *       "bio": "Reader, writer, collector of old Urdu print.",
         *       "post_count": 139,
         *       "like_count": 4210,
         *       "langs": [
         *         "en",
         *         "ur"
         *       ],
         *       "first_published_at": "2025-11-02T08:00:00Z",
         *       "last_published_at": "2026-09-01T06:00:00Z"
         *     }
         */
        Author: {
            user: components["schemas"]["UserSummary"];
            bio?: string | null;
            post_count: number;
            /** @description Likes across all published posts. */
            like_count: number;
            langs?: components["schemas"]["LangCode"][];
            /** Format: date-time */
            first_published_at?: string | null;
            /** Format: date-time */
            last_published_at?: string | null;
        };
        /**
         * @example {
         *       "category": {
         *         "slug": "fiction",
         *         "name": "Fiction",
         *         "emoji": "📖",
         *         "color": "#8a4fff"
         *       },
         *       "post_count": 42
         *     }
         */
        CategoryCount: {
            category: components["schemas"]["CategoryRef"];
            post_count: number;
        };
        /**
         * @example {
         *       "slug": "storytelling",
         *       "name": "Storytelling",
         *       "description": null,
         *       "color": "#8a4fff",
         *       "post_count": 17
         *     }
         */
        Tag: {
            slug: components["schemas"]["Slug"];
            name: string;
            description?: string | null;
            color?: string | null;
            post_count: number;
        };
        /**
         * @example {
         *       "post_id": "post_3Kf9Wq1Rb7Zc",
         *       "lang": "en",
         *       "status": "ready",
         *       "url": "https://media.ilm.red/blog-audio/post_3Kf9Wq1Rb7Zc/en.mp3?sig=abc123",
         *       "expires_at": "2026-09-22T19:04:05Z",
         *       "duration_seconds": 1432.4,
         *       "voice": "warm-narrator",
         *       "chapters": [
         *         {
         *           "title": "The king's bargain",
         *           "start_seconds": 0,
         *           "section_index": 0
         *         },
         *         {
         *           "title": "The frame",
         *           "start_seconds": 311.2,
         *           "section_index": 1
         *         }
         *       ],
         *       "available_langs": [
         *         "en",
         *         "ur"
         *       ],
         *       "updated_at": "2026-09-02T14:00:00Z"
         *     }
         */
        PostAudio: {
            post_id: components["schemas"]["PostId"];
            lang: components["schemas"]["LangCode"];
            /** @enum {string} */
            status: "ready" | "stale" | "none";
            /**
             * Format: uri
             * @description Signed; fetch before `expires_at`.
             */
            url?: string | null;
            /** Format: date-time */
            expires_at?: string | null;
            duration_seconds?: number | null;
            voice?: string | null;
            chapters?: {
                title: string;
                start_seconds: number;
                section_index?: number | null;
            }[];
            available_langs: components["schemas"]["LangCode"][];
            /** Format: date-time */
            updated_at?: string | null;
        };
        /**
         * @example {
         *       "id": "cmt_7Yd3Bn8Kw2Pf",
         *       "post_id": "post_3Kf9Wq1Rb7Zc",
         *       "parent_id": null,
         *       "author": {
         *         "id": "user_9Rt2Xc5Vb1Hn",
         *         "username": "amna_reads",
         *         "display_name": "Amna Qureshi",
         *         "avatar_url": null
         *       },
         *       "body": "The point about the frame being the real story changed how I read the whole book.",
         *       "status": "visible",
         *       "is_mine": false,
         *       "created_at": "2026-09-02T07:15:00Z",
         *       "edited_at": null
         *     }
         */
        Comment: {
            id: components["schemas"]["CommentId"];
            post_id: components["schemas"]["PostId"];
            parent_id: components["schemas"]["CommentId"] | null;
            author: components["schemas"]["UserSummary"];
            body: string;
            /**
             * @description `pending` is held for moderation and visible to its author only; `deleted` is a placeholder with an empty body.
             * @enum {string}
             */
            status: "visible" | "pending" | "deleted";
            is_mine?: boolean;
            created_at: components["schemas"]["Timestamp"];
            /** Format: date-time */
            edited_at?: string | null;
        };
        CommentWithReplies: components["schemas"]["Comment"] & {
            reply_count: number;
            /** @description Oldest first, at most 50; when `reply_count` is larger the rest are omitted. */
            replies: components["schemas"]["Comment"][];
        };
        CommentCreate: {
            body: string;
            parent_id?: components["schemas"]["CommentId"];
        };
        CommentPatch: {
            body?: string;
        };
        CommentReportCreate: {
            /** @enum {string} */
            reason: "spam" | "abuse" | "harassment" | "off_topic" | "misinformation" | "other";
            note?: string;
        };
        /**
         * @example {
         *       "liked": true,
         *       "like_count": 89
         *     }
         */
        LikeState: {
            liked: boolean;
            like_count: number;
        };
        ViewRecord: {
            /** @description A random id the client keeps for one browser or app session. */
            visit_id: string;
            lang?: components["schemas"]["LangCode"];
            /** Format: uri */
            referrer?: string;
        };
        ReaderReportCreate: {
            /** @enum {string} */
            kind: "layout" | "figure" | "quiz" | "audio" | "translation" | "wrong_fact" | "typo" | "broken_link" | "other";
            /** @description What is wrong. */
            description: string;
            /** @description Where it is. Any of these that help. */
            where?: {
                lang?: components["schemas"]["LangCode"];
                section_index?: number;
                figure_index?: number;
                /** @description The text around the problem. */
                quote?: string;
                /** @description Screen width in CSS pixels, for layout problems. */
                viewport_width?: number;
            };
            /** @description Announce a screenshot to get an upload ticket for it. */
            screenshot?: {
                /** @enum {string} */
                content_type: "image/png" | "image/jpeg" | "image/webp";
                bytes: number;
            };
        };
        /**
         * @example {
         *       "report": {
         *         "id": "rpt_2Lk9Wm4Zx7Qd",
         *         "post_id": "post_3Kf9Wq1Rb7Zc",
         *         "kind": "figure",
         *         "status": "open",
         *         "created_at": "2026-09-22T18:04:05Z"
         *       },
         *       "screenshot_upload": {
         *         "upload_url": "https://uploads.ilm.red/blog-report-shots/rpt_2Lk9Wm4Zx7Qd.png?sig=abc123",
         *         "method": "PUT",
         *         "headers": {
         *           "Content-Type": "image/png"
         *         },
         *         "expires_at": "2026-09-22T18:19:05Z",
         *         "max_bytes": 5242880
         *       }
         *     }
         */
        ReaderReportCreated: {
            report: {
                id: components["schemas"]["ReportId"];
                post_id: components["schemas"]["PostId"];
                kind: string;
                /** @enum {string} */
                status: "open" | "triaged" | "fixed" | "declined";
                created_at: components["schemas"]["Timestamp"];
            };
            /** @description Where to PUT the screenshot, or null when none was announced. */
            screenshot_upload: components["schemas"]["UploadTicket"] | null;
        };
        /**
         * @example {
         *       "lock_token": "lk_9f3a2c7e1b4d8a6f",
         *       "holder": {
         *         "id": "user_4Fq9ZtW1Lm8K",
         *         "username": "bilgrami",
         *         "display_name": "Syed Bilgrami",
         *         "avatar_url": null
         *       },
         *       "acquired_at": "2026-09-22T18:00:00Z",
         *       "expires_at": "2026-09-22T18:05:00Z"
         *     }
         */
        DraftLock: {
            lock_token: components["schemas"]["LockToken"];
            holder: components["schemas"]["UserSummary"];
            acquired_at?: components["schemas"]["Timestamp"];
            expires_at: components["schemas"]["Timestamp"];
        };
        LockRequest: {
            /** @default false */
            steal: boolean;
        };
        LockHeldProblem: components["schemas"]["Problem"] & {
            holder: components["schemas"]["UserSummary"];
            expires_at: components["schemas"]["Timestamp"];
        };
        /**
         * @example {
         *       "id": "post_8Qm2Tc5Vn1Rx",
         *       "slug": "the-lost-libraries-of-timbuktu",
         *       "title": "The lost libraries of Timbuktu",
         *       "lang": "en",
         *       "status": "draft",
         *       "author": {
         *         "id": "user_4Fq9ZtW1Lm8K",
         *         "username": "bilgrami",
         *         "display_name": "Syed Bilgrami",
         *         "avatar_url": null
         *       },
         *       "word_count": 1240,
         *       "locked_by": null,
         *       "published_at": null,
         *       "updated_at": "2026-09-22T17:48:00Z"
         *     }
         */
        DraftSummary: {
            id: components["schemas"]["PostId"];
            slug: components["schemas"]["Slug"];
            title: string;
            lang: components["schemas"]["LangCode"];
            status: components["schemas"]["DraftStatus"];
            author?: components["schemas"]["UserSummary"];
            word_count?: number | null;
            locked_by?: components["schemas"]["UserSummary"] | null;
            /** Format: date-time */
            published_at?: string | null;
            updated_at: components["schemas"]["Timestamp"];
        };
        /**
         * @example {
         *       "id": "post_8Qm2Tc5Vn1Rx",
         *       "slug": "the-lost-libraries-of-timbuktu",
         *       "canonical_path": null,
         *       "title": "The lost libraries of Timbuktu",
         *       "lang": "en",
         *       "status": "draft",
         *       "excerpt": "Seven hundred thousand manuscripts, and the families who hid them.",
         *       "content": "<p>In 2013 …</p>",
         *       "featured_image_url": null,
         *       "category": {
         *         "slug": "history",
         *         "name": "History",
         *         "emoji": "🏛️"
         *       },
         *       "tags": [
         *         {
         *           "slug": "manuscripts",
         *           "name": "Manuscripts",
         *           "color": null
         *         }
         *       ],
         *       "author": {
         *         "id": "user_4Fq9ZtW1Lm8K",
         *         "username": "bilgrami",
         *         "display_name": "Syed Bilgrami",
         *         "avatar_url": null
         *       },
         *       "lock": {
         *         "holder": {
         *           "id": "user_4Fq9ZtW1Lm8K",
         *           "username": "bilgrami",
         *           "display_name": "Syed Bilgrami",
         *           "avatar_url": null
         *         },
         *         "expires_at": "2026-09-22T18:05:00Z",
         *         "lock_token": "lk_9f3a2c7e1b4d8a6f"
         *       },
         *       "rebased": false,
         *       "word_count": 1240,
         *       "published_at": null,
         *       "created_at": "2026-09-20T09:00:00Z",
         *       "updated_at": "2026-09-22T17:48:00Z"
         *     }
         */
        Draft: {
            id: components["schemas"]["PostId"];
            slug: components["schemas"]["Slug"];
            /** @description Set once the post is published. */
            canonical_path?: string | null;
            title: string;
            lang: components["schemas"]["LangCode"];
            status: components["schemas"]["DraftStatus"];
            excerpt?: string | null;
            /** @description The draft body as HTML. */
            content: string;
            /** Format: uri */
            featured_image_url?: string | null;
            category?: components["schemas"]["CategoryRef"] | null;
            tags?: components["schemas"]["TagRef"][];
            author: components["schemas"]["UserSummary"];
            /** @description The current lock. `lock_token` is present only when the caller holds it. */
            lock: {
                holder: components["schemas"]["UserSummary"];
                expires_at: components["schemas"]["Timestamp"];
                lock_token?: components["schemas"]["LockToken"];
            } | null;
            /** @description True when opening the draft rebased it on a newer published version. */
            rebased: boolean;
            word_count?: number | null;
            /** Format: date-time */
            published_at?: string | null;
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
        };
        DraftCreate: {
            title: string;
            lang: components["schemas"]["LangCode"];
            slug?: components["schemas"]["Slug"];
            excerpt?: string;
            /** @description HTML. Sanitised on save. */
            content?: string;
            category?: components["schemas"]["Slug"];
            tags?: components["schemas"]["Slug"][];
        };
        DraftPatch: {
            title?: string;
            slug?: components["schemas"]["Slug"];
            excerpt?: string | null;
            /** @description HTML. Sanitised on save. */
            content?: string;
            category?: string | null;
            tags?: components["schemas"]["Slug"][];
            /** @description A label for this revision in the history. */
            note?: string;
        };
        /**
         * @example {
         *       "id": "revision_4Nc7Hx2Pd9Sm",
         *       "post_id": "post_8Qm2Tc5Vn1Rx",
         *       "title": "The lost libraries of Timbuktu",
         *       "excerpt": "Seven hundred thousand manuscripts, and the families who hid them.",
         *       "note": "Tightened the opening",
         *       "content_length": 8412,
         *       "edited_by": {
         *         "id": "user_4Fq9ZtW1Lm8K",
         *         "username": "bilgrami",
         *         "display_name": "Syed Bilgrami",
         *         "avatar_url": null
         *       },
         *       "created_at": "2026-09-22T17:48:00Z"
         *     }
         */
        Revision: {
            id: components["schemas"]["RevisionId"];
            post_id: components["schemas"]["PostId"];
            title?: string | null;
            excerpt?: string | null;
            note?: string | null;
            content_length?: number | null;
            edited_by?: components["schemas"]["UserSummary"] | null;
            created_at: components["schemas"]["Timestamp"];
        };
        /**
         * @description Lowercase words joined by hyphens.
         * @example arabian-nights-one-thousand-and-one-nights
         */
        Slug: string;
        /** @example bilgrami */
        Username: string;
        /** @description Every list returns this envelope. `next_cursor` is null on the last page. Lists that can count cheaply also return `total` when asked (each list says so); `total_capped` is true when the count stopped at the list's cap. */
        Page: {
            data: unknown[];
            next_cursor: string | null;
            total?: number;
            total_capped?: boolean;
        };
        /** @description RFC 9457 problem document. Branch on `slug` (also the last segment of `type`), show `title`, quote `request_id`. */
        Problem: {
            /**
             * Format: uri
             * @example https://api.ilm.red/problems/not_found
             */
            type: string;
            slug: components["schemas"]["ProblemSlug"];
            title: string;
            status: number;
            detail?: string;
            request_id: string;
        };
        ReportId: string;
        CommentId: string;
        /**
         * @description BCP 47 language tag.
         * @example ur
         * @example en
         * @example ar
         */
        LangCode: string;
        ValidationProblem: components["schemas"]["Problem"] & {
            errors: components["schemas"]["FieldError"][];
        };
        /** @example post_3Kf9Wq1Rb7Zc */
        PostId: string;
        /**
         * @description The stable part of a problem. Branch on this, never on `title` or `detail`.
         * @enum {string}
         */
        ProblemSlug: "unauthorized" | "key_invalid" | "key_revoked" | "key_expired" | "scope_missing" | "not_club_admin" | "club_quota_reached" | "internal_only" | "not_found" | "term_not_found" | "slug_exists" | "edge_would_cycle" | "drop_not_ready" | "needs_text" | "needs_pages" | "needs_translation" | "paper_locked" | "term_has_edges" | "paper_not_in_club" | "revision_required" | "plan_refused" | "duplicate_brief" | "review_forbidden" | "already_reviewed" | "club_required" | "brief_invalid" | "cost_cap_exceeded" | "repair_invalid" | "idempotency_conflict" | "validation_failed" | "unsupported_kind" | "rate_limited" | "extract_rate_limited" | "agreement_required" | "agreement_version_stale" | "over_ceiling" | "top_up_limit" | "method_unavailable" | "self_confirm_forbidden" | "internal_error" | "forbidden" | "premium_required" | "insufficient_credits" | "reauth_required" | "version_conflict" | "conflict" | "gone" | "payload_too_large" | "unsupported_media_type" | "quote_expired" | "agent_cap_reached" | "lock_held";
        /** @example user_4Fq9ZtW1Lm8K */
        UserId: string;
        /** @description How a person appears anywhere they are named. Never an email. */
        UserSummary: {
            id: components["schemas"]["UserId"];
            /** @description Null for a member who has not picked a username yet. */
            username: components["schemas"]["Username"] | null;
            display_name: string;
            /** Format: uri */
            avatar_url?: string | null;
        };
        CategoryRef: {
            slug: components["schemas"]["Slug"];
            name: string;
            emoji: string;
            color?: string;
        };
        /**
         * Format: date-time
         * @example 2026-09-22T18:04:05Z
         */
        Timestamp: string;
        /** Format: uri */
        Url: string;
        /** @description Where to send a file. PUT the bytes to `upload_url` with the given headers before `expires_at`, then call the confirming endpoint the operation names. This is the one place the client talks to storage directly, and only with this signed URL. */
        UploadTicket: {
            upload_url: components["schemas"]["Url"];
            /** @constant */
            method: "PUT";
            headers: {
                [key: string]: string;
            };
            expires_at: components["schemas"]["Timestamp"];
            max_bytes: number;
        };
        FieldError: {
            /**
             * @description Where the problem is, as a JSON Pointer into the request, prefixed with its part.
             * @example /body/title
             * @example /query/limit
             * @example /path/book_id
             * @example /header/Idempotency-Key
             */
            path: string;
            /**
             * @description Which rule failed.
             * @enum {string}
             */
            code: "required" | "type" | "enum" | "const" | "pattern" | "format" | "min_length" | "max_length" | "minimum" | "maximum" | "multiple_of" | "min_items" | "max_items" | "unique_items" | "unknown_field" | "one_of";
            /** @example must be at most 200 characters */
            message: string;
            /** @description The limit that was broken, when the rule has one (a length, a bound, the allowed values). */
            limit?: unknown;
        };
    };
    responses: {
        /** @description Someone else holds the draft lock (`lock_held`). The problem names the holder and when the lock expires. */
        LockHeld: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["LockHeldProblem"];
            };
        };
        /** @description The request failed validation (`validation_failed`). `errors` lists every failing field, not just the first. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ValidationProblem"];
            };
        };
        /** @description Too many requests (`rate_limited`). Retry after the `Retry-After` header. */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No such resource, or one the caller may not see (`not_found`). The two are deliberately indistinguishable. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No credential, or a credential that is not valid (`unauthorized`, `key_invalid`, `key_revoked`, `key_expired`, `reauth_required`). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The caller is known but may not do this (`forbidden`, `scope_missing`, `premium_required`, `internal_only`). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Done. No body. */
        NoContent: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description `If-Match` did not match the current version (`version_conflict`). Read again and retry. */
        VersionConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        Username: components["schemas"]["Username"];
        CommentId: components["schemas"]["CommentId"];
        PosterId: components["schemas"]["PosterId"];
        RevisionId: components["schemas"]["RevisionId"];
        /** @description The lock token from `POST /blog/drafts/{post_id}/lock` (or from creating the draft). */
        DraftLock: components["schemas"]["LockToken"];
        /** @description BCP 47 language tag. A missing translation falls back to the original text plus `available_langs`. */
        Lang: components["schemas"]["LangCode"];
        /** @description A field name, prefixed with `-` for descending. Each list documents the fields it allows. */
        Sort: string;
        /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
        Cursor: string;
        /** @description Page size. */
        Limit: number;
        PostId: components["schemas"]["PostId"];
        Slug: components["schemas"]["Slug"];
        /** @description Required on this call because it creates something or spends credits. See IdempotencyKey. */
        IdempotencyKeyRequired: string;
        /** @description Replay protection for 24 hours. The same key with the same body replays the first response; the same key with a different body is refused with `idempotency_conflict`. */
        IdempotencyKey: string;
        /** @description The `ETag` from your last read. A stale value is refused with `version_conflict` (412). */
        IfMatch: string;
    };
    requestBodies: never;
    headers: {
        /** @description Version of the resource, for caching and for `If-Match` on the next write. */
        ETag: string;
        /** @description URL of the resource just created. */
        Location: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listBlogFeed: {
        parameters: {
            query?: {
                q?: string;
                category?: components["schemas"]["Slug"];
                tag?: components["schemas"]["Slug"];
                author?: components["schemas"]["Username"];
                /** @description BCP 47 language tag. A missing translation falls back to the original text plus `available_langs`. */
                lang?: components["parameters"]["Lang"];
                /** @description A field name, prefixed with `-` for descending. Each list documents the fields it allows. */
                sort?: components["parameters"]["Sort"];
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of posts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["PostCard"][];
                    };
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    getPublishedBlogPost: {
        parameters: {
            query?: {
                /** @description BCP 47 language tag. A missing translation falls back to the original text plus `available_langs`. */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path: {
                post_id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The post. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishedPost"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    resolveBlogPost: {
        parameters: {
            query?: {
                /** @description BCP 47 language tag. A missing translation falls back to the original text plus `available_langs`. */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path: {
                username: components["schemas"]["Username"];
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The post. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishedPost"];
                };
            };
            /** @description The post moved to a new address. */
            301: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostMoved"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getBlogAuthor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: components["parameters"]["Username"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The author. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Author"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listBlogAuthorPosts: {
        parameters: {
            query?: {
                /** @description BCP 47 language tag. A missing translation falls back to the original text plus `available_langs`. */
                lang?: components["parameters"]["Lang"];
                /** @description A field name, prefixed with `-` for descending. Each list documents the fields it allows. */
                sort?: components["parameters"]["Sort"];
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                username: components["parameters"]["Username"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of posts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["PostCard"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listBlogCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All categories. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CategoryCount"][];
                    };
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    listBlogTags: {
        parameters: {
            query?: {
                q?: string;
                /** @description A field name, prefixed with `-` for descending. Each list documents the fields it allows. */
                sort?: components["parameters"]["Sort"];
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of tags. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["Tag"][];
                    };
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    getBlogPostAudio: {
        parameters: {
            query?: {
                /** @description BCP 47 language tag. A missing translation falls back to the original text plus `available_langs`. */
                lang?: components["parameters"]["Lang"];
            };
            header?: never;
            path: {
                post_id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The narration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostAudio"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listBlogComments: {
        parameters: {
            query?: {
                /** @description A field name, prefixed with `-` for descending. Each list documents the fields it allows. */
                sort?: components["parameters"]["Sort"];
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                post_id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of top-level comments. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["CommentWithReplies"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    createBlogComment: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on this call because it creates something or spends credits. See IdempotencyKey. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path: {
                post_id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentCreate"];
            };
        };
        responses: {
            /** @description The new comment. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Comments are closed on this post (`conflict`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    deleteBlogComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: components["parameters"]["PostId"];
                comment_id: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateBlogComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: components["parameters"]["PostId"];
                comment_id: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentPatch"];
            };
        };
        responses: {
            /** @description The edited comment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    reportBlogComment: {
        parameters: {
            query?: never;
            header?: {
                /** @description Replay protection for 24 hours. The same key with the same body replays the first response; the same key with a different body is refused with `idempotency_conflict`. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                post_id: components["parameters"]["PostId"];
                comment_id: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentReportCreate"];
            };
        };
        responses: {
            /** @description The report is with the moderators. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        report_id: components["schemas"]["ReportId"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    likeBlogPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The post's like state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LikeState"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    unlikeBlogPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The post's like state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LikeState"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    likeBlogPoster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                poster_id: components["parameters"]["PosterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The poster's like state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LikeState"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    unlikeBlogPoster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                poster_id: components["parameters"]["PosterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The poster's like state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LikeState"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    recordBlogPostView: {
        parameters: {
            query?: never;
            header?: {
                /** @description Replay protection for 24 hours. The same key with the same body replays the first response; the same key with a different body is refused with `idempotency_conflict`. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                post_id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewRecord"];
            };
        };
        responses: {
            204: components["responses"]["NoContent"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    createBlogReaderReport: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on this call because it creates something or spends credits. See IdempotencyKey. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path: {
                post_id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReaderReportCreate"];
            };
        };
        responses: {
            /** @description The report, and where to upload the screenshot when one was announced. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReaderReportCreated"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    listBlogDrafts: {
        parameters: {
            query?: {
                status?: components["schemas"]["DraftStatus"];
                author?: components["schemas"]["Username"];
                /** @description A field name, prefixed with `-` for descending. Each list documents the fields it allows. */
                sort?: components["parameters"]["Sort"];
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of drafts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["DraftSummary"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    createBlogDraft: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on this call because it creates something or spends credits. See IdempotencyKey. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftCreate"];
            };
        };
        responses: {
            /** @description The new draft. */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description The author already has a post with this slug (`slug_exists`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    getBlogDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The draft. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateBlogDraft: {
        parameters: {
            query?: never;
            header: {
                /** @description The `ETag` from your last read. A stale value is refused with `version_conflict` (412). */
                "If-Match"?: components["parameters"]["IfMatch"];
                /** @description The lock token from `POST /blog/drafts/{post_id}/lock` (or from creating the draft). */
                "X-Draft-Lock": components["parameters"]["DraftLock"];
            };
            path: {
                post_id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftPatch"];
            };
        };
        responses: {
            /** @description The saved draft. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["LockHeld"];
            412: components["responses"]["VersionConflict"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    acquireBlogDraftLock: {
        parameters: {
            query?: never;
            header?: {
                /** @description Replay protection for 24 hours. The same key with the same body replays the first response; the same key with a different body is refused with `idempotency_conflict`. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /** @description Your current lock token, to renew it. */
                "X-Draft-Lock"?: components["schemas"]["LockToken"];
            };
            path: {
                post_id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LockRequest"];
            };
        };
        responses: {
            /** @description The lock is yours. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftLock"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["LockHeld"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    releaseBlogDraftLock: {
        parameters: {
            query?: never;
            header: {
                /** @description The lock token from `POST /blog/drafts/{post_id}/lock` (or from creating the draft). */
                "X-Draft-Lock": components["parameters"]["DraftLock"];
            };
            path: {
                post_id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listBlogDraftRevisions: {
        parameters: {
            query?: {
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                post_id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of revisions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["Revision"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    restoreBlogDraftRevision: {
        parameters: {
            query?: never;
            header: {
                /** @description The `ETag` from your last read. A stale value is refused with `version_conflict` (412). */
                "If-Match"?: components["parameters"]["IfMatch"];
                /** @description The lock token from `POST /blog/drafts/{post_id}/lock` (or from creating the draft). */
                "X-Draft-Lock": components["parameters"]["DraftLock"];
                /** @description Replay protection for 24 hours. The same key with the same body replays the first response; the same key with a different body is refused with `idempotency_conflict`. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                post_id: components["parameters"]["PostId"];
                revision_id: components["parameters"]["RevisionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The draft with the revision restored. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["LockHeld"];
            412: components["responses"]["VersionConflict"];
        };
    };
}
