// COPIED from ilm-red-unbound/packages/api-client by scripts/sync-api-client.mjs. Do not edit here.
// GENERATED by scripts/build-api-client.mjs from api/openapi/*.json. Do not edit by hand;
// change the contract in openapi/ and run `npm run api:spec`.

/* eslint-disable */
export interface paths {
    "/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse the catalog
         * @description Public books to anyone. Signed-in callers also get members books, their own books and books shared with them. Filter by `category`, `lang` (the book's original language or any language it has text in) and a free-text `q` (fuzzy on title, author and description; typos tolerated). Sortable by `uploaded_at` (default, newest first), `title`, `view_count`, `rating` and `featured_at`; when `q` is present and no `sort` is given, results come in relevance order.
         */
        get: operations["listBooks"];
        put?: never;
        /**
         * Start uploading a book
         * @description Creates a draft book owned by the caller and returns an `UploadTicket`. PUT the file (PDF, EPUB, TXT or MOBI, up to 200 MB) to the ticket's URL, then call `POST /books/{book_id}/upload-complete` to start processing. The draft is visible only to its owner until processing finishes; an unconfirmed draft is removed after 24 hours.
         */
        post: operations["createBook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the 21 category portals
         * @description All categories in one page (`next_cursor` is always null), in display order, with counts of public books and blog posts.
         */
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one category portal */
        get: operations["getCategory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/by-slug/{category}/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a book by its public URL
         * @description The same answer as `GET /books/{book_id}`, found by the category and slug in the book's web address. Takes the same `include`.
         */
        get: operations["getBookBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{book_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        /**
         * Get a book
         * @description One round trip for the reader. `include=pages` adds the page count's first window of page images (up to 10 pages starting at the caller's last page, or page 1); `include=progress` adds the caller's reading progress (null for anonymous callers). Either include makes the response caller-specific (`Cache-Control: private, no-cache`).
         */
        get: operations["getBook"];
        put?: never;
        post?: never;
        /**
         * Delete my book
         * @description Owner only; anyone else gets `not_found`. Removes the book from the library at once, with its pages, text, translations, narration, ratings and Q&A. Readers' notes on it are kept but point at a deleted book. Cannot be undone.
         */
        delete: operations["deleteBook"];
        options?: never;
        head?: never;
        /**
         * Edit my book's details
         * @description Owner only: the member who uploaded the book. Anyone else gets `not_found`. Send only the fields to change. Changing `visibility` to `public` makes the book appear in the catalog once processing has finished (to `members`, in the catalog of signed-in members only); any narrower change removes it from those listings at once. `shared_with` applies only when `visibility` is `shared`.
         */
        patch: operations["updateBook"];
        trace?: never;
    };
    "/books/{book_id}/upload-complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm the upload and start processing
         * @description Owner only. Call after the PUT to the `UploadTicket` succeeded. The file is checked (type, size, and the optional `sha256`), then page rendering, OCR, translations and narration are queued. Follow them with `GET /books/{book_id}/processing`. Calling it again on a book that is already processing returns the same job.
         */
        post: operations["completeBookUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{book_id}/processing": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        /**
         * Processing status of my book, stage by stage
         * @description Owner only; anyone else gets `not_found`. Poll every few seconds while `status` is `queued` or `running`; send `If-None-Match` to get cheap `304`s.
         */
        get: operations["getBookProcessing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{book_id}/pages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        /**
         * Page images for a range of pages
         * @description Page numbers, sizes and short-lived signed image URLs (thumbnail, medium and high resolution) for pages `from` to `to`, at most 50 pages per call. Ask again for fresh URLs after `expires_at`. `next_from` is the first page of the following window, or null at the end of the book.
         */
        get: operations["listBookPages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{book_id}/pages/{n}/text": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: components["parameters"]["BookId"];
                /** @description 1-based page number. */
                n: components["parameters"]["PageNumber"];
            };
            cookie?: never;
        };
        /**
         * Text of one page
         * @description The page's text in `lang` (default: the book's original language). When there is no translation into `lang`, the original text comes back with `fallback: true` and `available_langs` listing what does exist. `dir` gives the text direction and `revision` changes whenever the text is corrected.
         */
        get: operations["getBookPageText"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{book_id}/text": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        /**
         * Text of a range of pages
         * @description Text for pages `from` to `to` (at most 50) in `lang`, with the same fallback rule as a single page: when the book has no text in `lang` the original comes back with `fallback: true` and `available_langs`. Pages without text yet are listed with `text: null`.
         */
        get: operations["getBookText"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{book_id}/editions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        /**
         * Languages this book can be read or heard in
         * @description One entry per language that has any text, translation or narration, with coverage as a percentage of pages. The original language is listed first. All in one page (`next_cursor` is always null).
         */
        get: operations["listBookEditions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{book_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        /**
         * Narration tracks with playable URLs
         * @description Narration for the book in `lang` (default: the original language), one track per page, in page order. Give `page` for a single page's track(s); otherwise page through with `cursor`. URLs are signed and expire after 60 minutes; ask again for fresh ones. A track marked `stale` was recorded before the page text was last corrected.
         */
        get: operations["listBookAudio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{book_id}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        /**
         * The book's table of contents
         * @description Chapters in reading order. An empty list means the book has no detected chapters.
         */
        get: operations["listBookChapters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search the whole library
         * @description Matches books (title, author, description) and the text of their pages, in the books the caller can read. Each hit is either a `book` hit or a `page` hit with a snippet; matched words in `snippet` are wrapped in `<mark>` and `</mark>` and nothing else is HTML. Ordered by relevance. `kind` narrows to one hit type.
         */
        get: operations["searchLibrary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{book_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        /**
         * Search inside one book
         * @description Page hits with snippets, in page order. `lang` searches that translation (default: the original text). Snippets mark matched words with `<mark>` and `</mark>`. `match_count` on each hit lets the reader cycle through matches on the page.
         */
        get: operations["searchBook"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{book_id}/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        /**
         * Rating summary and written reviews
         * @description `summary` has the average, count and star distribution; `data` pages through ratings that have review text, newest first (sortable by `created_at` and `stars`). `mine` is the caller's own rating, or null (always null for anonymous callers, and its presence makes the response `private`).
         */
        get: operations["listBookRatings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{book_id}/ratings/mine": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Rate a book (or change my rating)
         * @description One rating per member per book; a second PUT replaces the first. The summary is recalculated before the response.
         */
        put: operations["rateBook"];
        post?: never;
        /**
         * Remove my rating
         * @description Removing a rating that does not exist is not an error.
         */
        delete: operations["deleteMyBookRating"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{book_id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        /**
         * Public questions and answers about a book
         * @description Published questions, sortable by `net_votes` (default, highest first), `created_at` and `answered_at`. `answered=true` shows only answered questions. Featured questions come first whatever the sort.
         */
        get: operations["listBookQuestions"];
        put?: never;
        /**
         * Ask a public question about a book
         * @description The question is held for moderation (`status: pending`) and is visible only to its author until published. Answers come from the library team or the book's owner.
         */
        post: operations["askBookQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{book_id}/questions/{question_id}/votes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: components["parameters"]["BookId"];
                question_id: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Vote a question up or down
         * @description One vote per member per question; a new vote replaces the old one, and `none` withdraws it. Repeating the same vote is not an error. Members cannot vote on their own question.
         */
        post: operations["voteOnBookQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{book_id}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report a problem with a book
         * @description `wrong_text`, `broken_page`, `bad_translation` and `other` go to the library team; `page` points them at the spot. `copyright_notice` is a formal notice from a rights holder (or someone acting for one) and needs the claimant's name, email and postal address, the work claimed, a statement, the two sworn affirmations and a signature. Follow up in `GET /me/reports`.
         */
        post: operations["reportBook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example qa_8Hn2Kd5Lp0Qe */
        QuestionId: string;
        /**
         * @description One of the 21 category portals.
         * @enum {string}
         */
        CategorySlug: "fiction" | "non-fiction" | "science" | "technology" | "history" | "biography" | "self-help" | "business" | "education" | "children" | "romance" | "mystery" | "fantasy" | "science-fiction" | "horror" | "poetry" | "drama" | "philosophy" | "religion" | "medical" | "other";
        /**
         * @description `public`: in the catalog and readable by anyone, signed in or not. `members`: readable by any signed-in member and listed in their catalog, never shown to anonymous callers. `private`: only the uploader. `shared`: the uploader plus the members listed in `shared_with`.
         * @enum {string}
         */
        BookVisibility: "public" | "members" | "private" | "shared";
        /** @enum {string} */
        TextDirection: "rtl" | "ltr";
        /**
         * @description `draft` until the upload is confirmed, `processing` while pages and text are produced, then `ready` (or `failed`).
         * @enum {string}
         */
        BookStatus: "draft" | "processing" | "ready" | "failed";
        /**
         * @example {
         *       "id": "book_2mCq1kZ9xTb4",
         *       "slug": "arabian-nights-one-thousand-and-one-nights",
         *       "title": "Arabian Nights: One Thousand and One Nights",
         *       "subtitle": null,
         *       "author": "Anonymous, tr. Richard F. Burton",
         *       "description": "The frame tale of Shahrazad and the stories she tells to stay alive.",
         *       "language": "en",
         *       "dir": "ltr",
         *       "category": {
         *         "slug": "fiction",
         *         "name": "Fiction",
         *         "emoji": "📖",
         *         "color": "#8B5CF6"
         *       },
         *       "tags": [
         *         "classics",
         *         "folklore"
         *       ],
         *       "cover_url": "https://cdn.ilm.red/covers/book_2mCq1kZ9xTb4.webp",
         *       "visibility": "public",
         *       "status": "ready",
         *       "page_count": 412,
         *       "text_langs": [
         *         "en",
         *         "ur",
         *         "ar"
         *       ],
         *       "has_audio": true,
         *       "series": null,
         *       "is_original_work": false,
         *       "download_allowed": false,
         *       "rating": {
         *         "average": 4.6,
         *         "count": 38
         *       },
         *       "view_count": 12840,
         *       "uploader": {
         *         "id": "user_4Fq9ZtW1Lm8K",
         *         "username": "bilgrami",
         *         "display_name": "Bill Bilgrami",
         *         "avatar_url": null
         *       },
         *       "is_mine": false,
         *       "featured_at": "2026-08-01T09:00:00Z",
         *       "uploaded_at": "2026-03-14T11:20:00Z",
         *       "updated_at": "2026-09-20T07:45:12Z"
         *     }
         */
        Book: {
            id: components["schemas"]["BookId"];
            slug: components["schemas"]["Slug"];
            title: string;
            subtitle?: string | null;
            author?: string | null;
            description?: string | null;
            language: components["schemas"]["LangCode"];
            dir: components["schemas"]["TextDirection"];
            category: components["schemas"]["CategoryRef"];
            tags?: string[];
            /** Format: uri */
            cover_url?: string | null;
            visibility: components["schemas"]["BookVisibility"];
            status: components["schemas"]["BookStatus"];
            page_count: number;
            /** @description Languages with text for at least one page, original first. */
            text_langs: components["schemas"]["LangCode"][];
            has_audio: boolean;
            series?: {
                name: string;
                order?: number | null;
            } | null;
            /** @description The uploader affirmed they wrote this work. */
            is_original_work?: boolean;
            download_allowed?: boolean;
            rating: {
                average: number | null;
                count: number;
            };
            view_count?: number;
            uploader: components["schemas"]["UserSummary"];
            /** @description True when the caller uploaded this book. Always false for anonymous callers. */
            is_mine?: boolean;
            /** Format: date-time */
            featured_at?: string | null;
            uploaded_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
        };
        /** @description A book, plus the extras asked for with `include`. */
        BookDetail: components["schemas"]["Book"] & {
            /** @description Present with `include=pages`. The first window of page images. */
            pages?: components["schemas"]["PageWindow"];
            /** @description Present with `include=progress`. Null for anonymous callers. */
            progress?: components["schemas"]["ReaderProgress"] | null;
        };
        /**
         * @description The caller's progress in this book (the same record as `GET /me/progress/{book_id}`).
         * @example {
         *       "last_page": 37,
         *       "furthest_page": 41,
         *       "percent": 9.95,
         *       "seconds_read": 5410,
         *       "updated_at": "2026-09-21T22:10:03Z"
         *     }
         */
        ReaderProgress: {
            last_page: number;
            furthest_page: number;
            percent: number;
            seconds_read: number;
            /** Format: date-time */
            updated_at?: string | null;
        };
        /**
         * @example {
         *       "slug": "history",
         *       "name": "History",
         *       "emoji": "🏛️",
         *       "color": "#B45309",
         *       "description": "Empires, archives and the people who lived through them.",
         *       "book_count": 214,
         *       "post_count": 37
         *     }
         */
        Category: {
            slug: components["schemas"]["CategorySlug"];
            name: string;
            emoji: string;
            color: string;
            description?: string | null;
            /** @description Public books in this category. */
            book_count: number;
            /** @description Published blog posts in this category. */
            post_count: number;
        };
        /**
         * @example {
         *       "page": 37,
         *       "width": 1654,
         *       "height": 2339,
         *       "status": "ready",
         *       "thumbnail": {
         *         "url": "https://cdn.ilm.red/p/book_2mCq1kZ9xTb4/37/t.webp?sig=Zk3q",
         *         "width": 200,
         *         "height": 283,
         *         "expires_at": "2026-09-22T19:04:05Z"
         *       },
         *       "medium": {
         *         "url": "https://cdn.ilm.red/p/book_2mCq1kZ9xTb4/37/m.webp?sig=Zk3q",
         *         "width": 900,
         *         "height": 1273,
         *         "expires_at": "2026-09-22T19:04:05Z"
         *       },
         *       "high_res": {
         *         "url": "https://cdn.ilm.red/p/book_2mCq1kZ9xTb4/37/h.webp?sig=Zk3q",
         *         "width": 1654,
         *         "height": 2339,
         *         "expires_at": "2026-09-22T19:04:05Z"
         *       },
         *       "bytes": {
         *         "thumbnail": 9214,
         *         "medium": 118340,
         *         "high_res": 402118
         *       }
         *     }
         */
        PageImage: {
            page: number;
            /** @description Width of the high-resolution image in pixels. */
            width: number;
            height: number;
            /** @enum {string} */
            status: "ready" | "pending" | "failed";
            thumbnail?: components["schemas"]["ImageRef"];
            medium?: components["schemas"]["ImageRef"];
            high_res?: components["schemas"]["ImageRef"];
            /** @description File sizes so a client on a metered connection can choose. */
            bytes?: {
                thumbnail?: number | null;
                medium?: number | null;
                high_res?: number | null;
            };
        };
        /** @description A range of pages; the documented exception to cursor pagination. */
        PageWindow: {
            from: number;
            to: number;
            /** @description Pages in the whole book. */
            page_count: number;
            data: components["schemas"]["PageImage"][];
            /** @description First page of the next window; null at the end of the book. */
            next_from: number | null;
        };
        /**
         * @description `original`: extracted or OCR text of the original. `edited`: corrected by a person. `translation`: machine translation. `translation_edited`: translation reviewed by a person.
         * @enum {string}
         */
        TextSource: "original" | "edited" | "translation" | "translation_edited";
        /**
         * @example {
         *       "book_id": "book_2mCq1kZ9xTb4",
         *       "page": 37,
         *       "lang": "ur",
         *       "requested_lang": "ur",
         *       "fallback": false,
         *       "dir": "rtl",
         *       "revision": 3,
         *       "source": "translation_edited",
         *       "text": "شہرزاد نے کہا کہ اے بادشاہ، میں نے سنا ہے...",
         *       "available_langs": [
         *         "en",
         *         "ur",
         *         "ar"
         *       ]
         *     }
         */
        PageText: {
            book_id: components["schemas"]["BookId"];
            page: number;
            lang: components["schemas"]["LangCode"];
            requested_lang: components["schemas"]["LangCode"];
            /** @description True when `lang` is the original because no text exists in `requested_lang`. */
            fallback: boolean;
            dir: components["schemas"]["TextDirection"];
            /** @description Increases whenever this page's text in this language changes. */
            revision: number;
            source: components["schemas"]["TextSource"];
            text: string;
            available_langs: components["schemas"]["LangCode"][];
        };
        /**
         * @description Text for a range of pages; the documented exception to cursor pagination.
         * @example {
         *       "book_id": "book_2mCq1kZ9xTb4",
         *       "lang": "en",
         *       "requested_lang": "sw",
         *       "fallback": true,
         *       "dir": "ltr",
         *       "available_langs": [
         *         "en",
         *         "ur",
         *         "ar"
         *       ],
         *       "from": 1,
         *       "to": 2,
         *       "page_count": 412,
         *       "next_from": 3,
         *       "data": [
         *         {
         *           "page": 1,
         *           "text": "THE BOOK OF THE THOUSAND NIGHTS AND A NIGHT",
         *           "revision": 1,
         *           "source": "original"
         *         },
         *         {
         *           "page": 2,
         *           "text": null,
         *           "revision": 0,
         *           "source": null
         *         }
         *       ]
         *     }
         */
        TextWindow: {
            book_id: components["schemas"]["BookId"];
            lang: components["schemas"]["LangCode"];
            requested_lang: components["schemas"]["LangCode"];
            fallback: boolean;
            dir: components["schemas"]["TextDirection"];
            available_langs: components["schemas"]["LangCode"][];
            from: number;
            to: number;
            page_count: number;
            next_from: number | null;
            data: {
                page: number;
                /** @description Null when the page has no text yet. */
                text: string | null;
                revision: number;
                source: components["schemas"]["TextSource"] | null;
            }[];
        };
        /**
         * @example {
         *       "lang": "ur",
         *       "label": "اردو",
         *       "is_original": false,
         *       "dir": "rtl",
         *       "text_pct": 100,
         *       "human_reviewed_pct": 22.5,
         *       "narration_pct": 64.1,
         *       "voices": [
         *         "ur-female-1"
         *       ]
         *     }
         */
        Edition: {
            lang: components["schemas"]["LangCode"];
            /** @description The language's name in that language. */
            label: string;
            is_original: boolean;
            dir: components["schemas"]["TextDirection"];
            /** @description Pages with text in this language (original or translation). */
            text_pct: number;
            /** @description Pages whose text a person has corrected or reviewed. */
            human_reviewed_pct?: number;
            /** @description Pages with current (not stale) narration. */
            narration_pct: number;
            voices: string[];
        };
        /**
         * @example {
         *       "page": 37,
         *       "lang": "ur",
         *       "voice": "ur-female-1",
         *       "url": "https://cdn.ilm.red/a/book_2mCq1kZ9xTb4/ur/37.mp3?sig=Qa7w",
         *       "expires_at": "2026-09-22T19:04:05Z",
         *       "duration_ms": 142380,
         *       "stale": false
         *     }
         */
        AudioTrack: {
            page: number;
            lang: components["schemas"]["LangCode"];
            voice: string;
            url: components["schemas"]["Url"];
            expires_at: components["schemas"]["Timestamp"];
            duration_ms: number | null;
            /** @description Recorded before the page text last changed; a fresh recording is on its way. */
            stale: boolean;
        };
        /**
         * @example {
         *       "index": 3,
         *       "title": "The Tale of the Fisherman and the Jinni",
         *       "start_page": 37
         *     }
         */
        Chapter: {
            index: number;
            title: string;
            start_page: number | null;
        };
        BookSummary: {
            id: components["schemas"]["BookId"];
            slug: components["schemas"]["Slug"];
            title: string;
            author?: string | null;
            category: components["schemas"]["CategoryRef"];
            /** Format: uri */
            cover_url?: string | null;
            language?: components["schemas"]["LangCode"];
        };
        /**
         * @example {
         *       "kind": "page",
         *       "book": {
         *         "id": "book_2mCq1kZ9xTb4",
         *         "slug": "arabian-nights-one-thousand-and-one-nights",
         *         "title": "Arabian Nights: One Thousand and One Nights",
         *         "author": "Anonymous",
         *         "category": {
         *           "slug": "fiction",
         *           "name": "Fiction",
         *           "emoji": "📖"
         *         },
         *         "cover_url": null,
         *         "language": "en"
         *       },
         *       "page": 37,
         *       "lang": "en",
         *       "snippet": "...the fisherman cast his net and drew up a <mark>brass jar</mark> sealed with lead...",
         *       "score": 0.82
         *     }
         */
        SearchHit: {
            /** @enum {string} */
            kind: "book" | "page";
            book: components["schemas"]["BookSummary"];
            /** @description Set on `page` hits. */
            page?: number | null;
            /** @description Language of the matched text on `page` hits. */
            lang?: string | null;
            /** @description Matched words wrapped in `<mark>`; nothing else is HTML. */
            snippet?: string | null;
            /** @description Relevance, only comparable within one response. */
            score: number;
        };
        /**
         * @example {
         *       "page": 37,
         *       "lang": "en",
         *       "snippet": "...drew up a <mark>brass jar</mark> sealed with lead...",
         *       "match_count": 2
         *     }
         */
        PageHit: {
            page: number;
            lang: components["schemas"]["LangCode"];
            snippet: string;
            match_count: number;
        };
        /**
         * @example {
         *       "average": 4.6,
         *       "count": 38,
         *       "distribution": {
         *         "1": 0,
         *         "2": 1,
         *         "3": 2,
         *         "4": 8,
         *         "5": 27
         *       }
         *     }
         */
        RatingSummary: {
            average: number | null;
            count: number;
            /** @description Count of ratings per star value. */
            distribution: {
                1: number;
                2: number;
                3: number;
                4: number;
                5: number;
            };
        };
        /**
         * @example {
         *       "user": {
         *         "id": "user_4Fq9ZtW1Lm8K",
         *         "username": "bilgrami",
         *         "display_name": "Bill Bilgrami",
         *         "avatar_url": null
         *       },
         *       "stars": 5,
         *       "review": "The Urdu translation reads beautifully.",
         *       "created_at": "2026-09-02T10:00:00Z",
         *       "updated_at": null
         *     }
         */
        Rating: {
            user?: components["schemas"]["UserSummary"];
            stars: number;
            review?: string | null;
            created_at: components["schemas"]["Timestamp"];
            /** Format: date-time */
            updated_at?: string | null;
        };
        RatingSave: {
            stars: number;
            /** @description Optional written review; null clears it. */
            review?: string | null;
        };
        /**
         * @example {
         *       "id": "qa_8Hn2Kd5Lp0Qe",
         *       "book_id": "book_2mCq1kZ9xTb4",
         *       "title": "Why does Shahrazad start with the merchant?",
         *       "question": "Why does the first night open with the merchant and the jinni rather than the fisherman?",
         *       "page": 12,
         *       "answer": "The merchant's tale sets up the ransom-by-story pattern that frames the whole collection.",
         *       "answered_at": "2026-09-10T14:02:00Z",
         *       "status": "published",
         *       "featured": false,
         *       "tags": [
         *         "structure"
         *       ],
         *       "upvotes": 14,
         *       "downvotes": 1,
         *       "net_votes": 13,
         *       "my_vote": null,
         *       "asked_by": {
         *         "id": "user_4Fq9ZtW1Lm8K",
         *         "username": "bilgrami",
         *         "display_name": "Bill Bilgrami",
         *         "avatar_url": null
         *       },
         *       "created_at": "2026-09-09T08:30:00Z"
         *     }
         */
        Question: {
            id: components["schemas"]["QuestionId"];
            book_id: components["schemas"]["BookId"];
            title?: string | null;
            question: string;
            page?: number | null;
            answer?: string | null;
            /** Format: date-time */
            answered_at?: string | null;
            /**
             * @description `pending` questions are shown only to their author.
             * @enum {string}
             */
            status: "pending" | "published";
            featured: boolean;
            tags?: string[];
            upvotes: number;
            downvotes: number;
            net_votes: number;
            /**
             * @description Always null for anonymous callers.
             * @enum {string|null}
             */
            my_vote?: "up" | "down" | null;
            asked_by: components["schemas"]["UserSummary"];
            created_at: components["schemas"]["Timestamp"];
        };
        QuestionCreate: {
            title?: string;
            question: string;
            page?: number;
            tags?: string[];
        };
        QuestionVote: {
            /**
             * @description `none` withdraws my vote.
             * @enum {string}
             */
            vote: "up" | "down" | "none";
            /** @description Optional reason, shown to moderators only. */
            explanation?: string;
        };
        /**
         * @example {
         *       "question_id": "qa_8Hn2Kd5Lp0Qe",
         *       "upvotes": 15,
         *       "downvotes": 1,
         *       "net_votes": 14,
         *       "my_vote": "up"
         *     }
         */
        QuestionVotes: {
            question_id: components["schemas"]["QuestionId"];
            upvotes: number;
            downvotes: number;
            net_votes: number;
            /** @enum {string|null} */
            my_vote: "up" | "down" | null;
        };
        BookReportCreate: {
            /** @enum {string} */
            kind: "wrong_text" | "broken_page" | "bad_translation" | "other";
            page?: number;
            lang?: components["schemas"]["LangCode"];
            details: string;
        };
        CopyrightNoticeCreate: {
            /** @constant */
            kind: "copyright_notice";
            page?: number;
            claimant: {
                name: string;
                /** Format: email */
                email: string;
                address: string;
                phone?: string;
                /** @description The rights holder, when the claimant is an agent. */
                acting_for?: string;
            };
            /** @description The copyrighted work claimed to be infringed. */
            work_identified: string;
            /** @description Which part of this book infringes it, when not the whole book. */
            material_identified?: string;
            statement: string;
            /**
             * @description I believe in good faith that this use is not authorised by the owner, its agent or the law.
             * @constant
             */
            good_faith_statement: true;
            /**
             * @description Under penalty of perjury, the information is accurate and I am the owner or authorised to act for them.
             * @constant
             */
            perjury_statement: true;
            /** @description Full name, typed, as an electronic signature. */
            signature: string;
        };
        /**
         * @example {
         *       "id": "rpt_5Tg1Hw8Nc2Ma",
         *       "kind": "broken_page",
         *       "status": "open",
         *       "created_at": "2026-09-22T18:04:05Z"
         *     }
         */
        ReportReceipt: {
            id: components["schemas"]["ReportId"];
            /** @enum {string} */
            kind: "wrong_text" | "broken_page" | "bad_translation" | "copyright_notice" | "other";
            /** @enum {string} */
            status: "open";
            created_at: components["schemas"]["Timestamp"];
        };
        BookCreate: {
            title: string;
            subtitle?: string;
            author?: string;
            description?: string;
            language: components["schemas"]["LangCode"];
            category: components["schemas"]["CategorySlug"];
            visibility: components["schemas"]["BookVisibility"];
            /** @description Usernames who may read the book when `visibility` is `shared`. */
            shared_with?: components["schemas"]["Username"][];
            /** @default false */
            is_original_work: boolean;
            /**
             * @description I own this work or have the right to share it under the visibility chosen.
             * @constant
             */
            rights_affirmed: true;
            file: {
                name: string;
                /** @enum {string} */
                content_type: "application/pdf" | "application/epub+zip" | "text/plain" | "application/x-mobipocket-ebook";
                bytes: number;
            };
        };
        /**
         * @example {
         *       "book": {
         *         "id": "book_9Pr3Tz6Yc1Df",
         *         "slug": "my-grandfathers-letters",
         *         "title": "My Grandfather's Letters",
         *         "subtitle": null,
         *         "author": "Bill Bilgrami",
         *         "description": null,
         *         "language": "ur",
         *         "dir": "rtl",
         *         "category": {
         *           "slug": "biography",
         *           "name": "Biography",
         *           "emoji": "👤",
         *           "color": "#0EA5E9"
         *         },
         *         "tags": [],
         *         "cover_url": null,
         *         "visibility": "private",
         *         "status": "draft",
         *         "page_count": 0,
         *         "text_langs": [],
         *         "has_audio": false,
         *         "series": null,
         *         "is_original_work": false,
         *         "download_allowed": false,
         *         "rating": {
         *           "average": null,
         *           "count": 0
         *         },
         *         "view_count": 0,
         *         "uploader": {
         *           "id": "user_4Fq9ZtW1Lm8K",
         *           "username": "bilgrami",
         *           "display_name": "Bill Bilgrami",
         *           "avatar_url": null
         *         },
         *         "is_mine": true,
         *         "featured_at": null,
         *         "uploaded_at": "2026-09-22T18:04:05Z",
         *         "updated_at": "2026-09-22T18:04:05Z"
         *       },
         *       "upload": {
         *         "upload_url": "https://uploads.ilm.red/books/book_9Pr3Tz6Yc1Df?sig=Lw2x",
         *         "method": "PUT",
         *         "headers": {
         *           "Content-Type": "application/pdf"
         *         },
         *         "expires_at": "2026-09-22T19:04:05Z",
         *         "max_bytes": 209715200
         *       }
         *     }
         */
        BookDraftCreated: {
            book: components["schemas"]["Book"];
            upload: components["schemas"]["UploadTicket"];
        };
        UploadComplete: {
            /** @description Hex SHA-256 of the uploaded file; when given, a mismatch is refused. */
            sha256?: string;
        };
        BookPatch: {
            title?: string;
            subtitle?: string | null;
            author?: string | null;
            description?: string | null;
            language?: components["schemas"]["LangCode"];
            category?: components["schemas"]["CategorySlug"];
            visibility?: components["schemas"]["BookVisibility"];
            shared_with?: components["schemas"]["Username"][];
            tags?: string[];
            series_name?: string | null;
            series_order?: number | null;
            download_allowed?: boolean;
        };
        ProcessingStage: {
            /** @enum {string} */
            stage: "upload" | "pages" | "ocr" | "translations" | "audio";
            /** @enum {string} */
            status: "pending" | "running" | "done" | "failed" | "skipped";
            /** @description Units finished (pages, or page-languages for translations and audio). */
            done: number;
            total: number;
            /** @description For `translations` and `audio`, the languages being produced. */
            langs?: components["schemas"]["LangCode"][];
            /** @description A short explanation when the stage failed or was skipped. */
            message?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        /**
         * @example {
         *       "book_id": "book_9Pr3Tz6Yc1Df",
         *       "status": "running",
         *       "percent": 46,
         *       "job_id": "job_1Ab2Cd3Ef4Gh",
         *       "stages": [
         *         {
         *           "stage": "upload",
         *           "status": "done",
         *           "done": 1,
         *           "total": 1,
         *           "updated_at": "2026-09-22T18:06:00Z"
         *         },
         *         {
         *           "stage": "pages",
         *           "status": "done",
         *           "done": 212,
         *           "total": 212,
         *           "updated_at": "2026-09-22T18:09:30Z"
         *         },
         *         {
         *           "stage": "ocr",
         *           "status": "running",
         *           "done": 95,
         *           "total": 212,
         *           "updated_at": "2026-09-22T18:12:02Z"
         *         },
         *         {
         *           "stage": "translations",
         *           "status": "pending",
         *           "done": 0,
         *           "total": 424,
         *           "langs": [
         *             "en",
         *             "ar"
         *           ]
         *         },
         *         {
         *           "stage": "audio",
         *           "status": "pending",
         *           "done": 0,
         *           "total": 212,
         *           "langs": [
         *             "ur"
         *           ]
         *         }
         *       ]
         *     }
         */
        BookProcessing: {
            book_id: components["schemas"]["BookId"];
            /** @enum {string} */
            status: "draft" | "queued" | "running" | "done" | "failed";
            percent: number;
            job_id?: components["schemas"]["JobId"] | null;
            stages: components["schemas"]["ProcessingStage"][];
        };
        /** @description Every list returns this envelope. `next_cursor` is null on the last page. */
        Page: {
            data: unknown[];
            next_cursor: string | null;
        };
        /** @description RFC 9457 problem document. Branch on `slug` (also the last segment of `type`), show `title`, quote `request_id`. */
        Problem: {
            /**
             * Format: uri
             * @example https://api.ilm.red/problems/not_found
             */
            type: string;
            slug: components["schemas"]["ProblemSlug"];
            title: string;
            status: number;
            detail?: string;
            request_id: string;
        };
        /** @description Returned with 202 by anything that runs longer than a request. */
        QueuedWork: {
            job_id: components["schemas"]["JobId"];
            /** @enum {string} */
            status: "queued" | "running" | "done" | "failed" | "cancelled";
            estimate?: components["schemas"]["PriceEstimate"];
        };
        ValidationProblem: components["schemas"]["Problem"] & {
            errors: components["schemas"]["FieldError"][];
        };
        /**
         * @description BCP 47 language tag.
         * @example ur
         * @example en
         * @example ar
         */
        LangCode: string;
        /**
         * @description The stable part of a problem. Branch on this, never on `title` or `detail`.
         * @enum {string}
         */
        ProblemSlug: "unauthorized" | "key_invalid" | "key_revoked" | "key_expired" | "scope_missing" | "not_club_admin" | "club_quota_reached" | "internal_only" | "not_found" | "term_not_found" | "slug_exists" | "edge_would_cycle" | "drop_not_ready" | "needs_text" | "needs_pages" | "needs_translation" | "paper_locked" | "term_has_edges" | "paper_not_in_club" | "revision_required" | "plan_refused" | "duplicate_brief" | "review_forbidden" | "already_reviewed" | "club_required" | "brief_invalid" | "cost_cap_exceeded" | "repair_invalid" | "idempotency_conflict" | "validation_failed" | "unsupported_kind" | "rate_limited" | "extract_rate_limited" | "internal_error" | "forbidden" | "premium_required" | "insufficient_credits" | "reauth_required" | "version_conflict" | "conflict" | "gone" | "payload_too_large" | "unsupported_media_type" | "quote_expired" | "agent_cap_reached" | "lock_held";
        /**
         * @description Lowercase words joined by hyphens.
         * @example arabian-nights-one-thousand-and-one-nights
         */
        Slug: string;
        /** @example book_2mCq1kZ9xTb4 */
        BookId: string;
        JobId: string;
        /** @description What a call will cost before it runs. `low` and `high` are null when the kind has never been measured. */
        PriceEstimate: {
            credits_low: number | null;
            credits_high: number | null;
            /** @enum {string} */
            source: "measured" | "kind_spread" | "uncalibrated";
        };
        FieldError: {
            /**
             * @description Where the problem is, as a JSON Pointer into the request, prefixed with its part.
             * @example /body/title
             * @example /query/limit
             * @example /path/book_id
             * @example /header/Idempotency-Key
             */
            path: string;
            /**
             * @description Which rule failed.
             * @enum {string}
             */
            code: "required" | "type" | "enum" | "const" | "pattern" | "format" | "min_length" | "max_length" | "minimum" | "maximum" | "multiple_of" | "min_items" | "max_items" | "unique_items" | "unknown_field" | "one_of";
            /** @example must be at most 200 characters */
            message: string;
            /** @description The limit that was broken, when the rule has one (a length, a bound, the allowed values). */
            limit?: unknown;
        };
        CategoryRef: {
            slug: components["schemas"]["Slug"];
            name: string;
            emoji: string;
            color?: string;
        };
        /** @example user_4Fq9ZtW1Lm8K */
        UserId: string;
        /** @example bilgrami */
        Username: string;
        /** @description How a person appears anywhere they are named. Never an email. */
        UserSummary: {
            id: components["schemas"]["UserId"];
            username: components["schemas"]["Username"];
            display_name: string;
            /** Format: uri */
            avatar_url?: string | null;
        };
        /**
         * Format: date-time
         * @example 2026-09-22T18:04:05Z
         */
        Timestamp: string;
        /** Format: uri */
        Url: string;
        /** @description A signed, short-lived image URL. Fetch it before `expires_at`; ask again after. */
        ImageRef: {
            url: components["schemas"]["Url"];
            width?: number;
            height?: number;
            expires_at: components["schemas"]["Timestamp"];
        };
        ReportId: string;
        /** @description Where to send a file. PUT the bytes to `upload_url` with the given headers before `expires_at`, then call the confirming endpoint the operation names. This is the one place the client talks to storage directly, and only with this signed URL. */
        UploadTicket: {
            upload_url: components["schemas"]["Url"];
            /** @constant */
            method: "PUT";
            headers: {
                [key: string]: string;
            };
            expires_at: components["schemas"]["Timestamp"];
            max_bytes: number;
        };
    };
    responses: {
        /** @description Unchanged since the `ETag` sent in `If-None-Match`. No body. */
        NotModified: {
            headers: {
                ETag: components["headers"]["ETag"];
                "Cache-Control": components["headers"]["CacheControl"];
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description The file is larger than 200 MB (`payload_too_large`). */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The file is not a PDF, EPUB, TXT or MOBI, or its contents do not match its declared type (`unsupported_media_type`). */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No credential, or a credential that is not valid (`unauthorized`, `key_invalid`, `key_revoked`, `key_expired`, `reauth_required`). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The request failed validation (`validation_failed`). `errors` lists every failing field, not just the first. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ValidationProblem"];
            };
        };
        /** @description Too many requests (`rate_limited`). Retry after the `Retry-After` header. */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The caller is known but may not do this (`forbidden`, `scope_missing`, `premium_required`, `internal_only`). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No such resource, or one the caller may not see (`not_found`). The two are deliberately indistinguishable. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description `If-Match` did not match the current version (`version_conflict`). Read again and retry. */
        VersionConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Done. No body. */
        NoContent: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: {
        /** @description The `ETag` from your last read. When nothing changed the answer is `304` with no body. */
        IfNoneMatch: string;
        /** @description Extras to return with the book, comma separated. */
        Include: ("pages" | "progress")[];
        /** @description First page of the window (1-based). Default 1. */
        From: number;
        /** @description Last page of the window, inclusive. Default `from + 49`, capped at the book's last page. At most 50 pages per call. */
        To: number;
        /** @description What to look for. Words are matched in any order; quote a phrase to match it exactly. */
        Query: string;
        QuestionId: components["schemas"]["QuestionId"];
        /** @description BCP 47 language tag. A missing translation falls back to the original text plus `available_langs`. */
        Lang: components["schemas"]["LangCode"];
        /** @description A field name, prefixed with `-` for descending. Each list documents the fields it allows. */
        Sort: string;
        /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
        Cursor: string;
        /** @description Page size. */
        Limit: number;
        /** @description Required on this call because it creates something or spends credits. See IdempotencyKey. */
        IdempotencyKeyRequired: string;
        Slug: components["schemas"]["Slug"];
        BookId: components["schemas"]["BookId"];
        /** @description The `ETag` from your last read. A stale value is refused with `version_conflict` (412). */
        IfMatch: string;
        /** @description Replay protection for 24 hours. The same key with the same body replays the first response; the same key with a different body is refused with `idempotency_conflict`. */
        IdempotencyKey: string;
        /** @description 1-based page number. */
        PageNumber: number;
    };
    requestBodies: never;
    headers: {
        /** @description How long the edge and the client may keep this response. Public, caller-independent answers carry `public` with `s-maxage` for the Cloudflare edge; anything that depends on the caller carries `private, no-cache`. See the API description for the values per route. */
        CacheControl: string;
        /** @description Version of the resource, for caching and for `If-Match` on the next write. */
        ETag: string;
        /** @description URL of the resource just created. */
        Location: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listBooks: {
        parameters: {
            query?: {
                category?: components["schemas"]["CategorySlug"];
                /** @description BCP 47 language tag. A missing translation falls back to the original text plus `available_langs`. */
                lang?: components["parameters"]["Lang"];
                /** @description Free text; fuzzy match on title, author and description. */
                q?: string;
                /** @description A field name, prefixed with `-` for descending. Each list documents the fields it allows. */
                sort?: components["parameters"]["Sort"];
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description The `ETag` from your last read. When nothing changed the answer is `304` with no body. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of books. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["Book"][];
                    };
                };
            };
            304: components["responses"]["NotModified"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    createBook: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on this call because it creates something or spends credits. See IdempotencyKey. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookCreate"];
            };
        };
        responses: {
            /** @description The draft and where to upload the file. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDraftCreated"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description The same `Idempotency-Key` was reused with a different body (`idempotency_conflict`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: {
                /** @description The `ETag` from your last read. When nothing changed the answer is `304` with no body. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every category. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["Category"][];
                    };
                };
            };
            304: components["responses"]["NotModified"];
            429: components["responses"]["RateLimited"];
        };
    };
    getCategory: {
        parameters: {
            query?: never;
            header?: {
                /** @description The `ETag` from your last read. When nothing changed the answer is `304` with no body. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path: {
                slug: components["schemas"]["CategorySlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The category. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            304: components["responses"]["NotModified"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    getBookBySlug: {
        parameters: {
            query?: {
                /** @description Extras to return with the book, comma separated. */
                include?: components["parameters"]["Include"];
            };
            header?: {
                /** @description The `ETag` from your last read. When nothing changed the answer is `304` with no body. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path: {
                category: components["schemas"]["CategorySlug"];
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The book. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDetail"];
                };
            };
            304: components["responses"]["NotModified"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getBook: {
        parameters: {
            query?: {
                /** @description Extras to return with the book, comma separated. */
                include?: components["parameters"]["Include"];
            };
            header?: {
                /** @description The `ETag` from your last read. When nothing changed the answer is `304` with no body. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The book, with the requested includes. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDetail"];
                };
            };
            304: components["responses"]["NotModified"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    deleteBook: {
        parameters: {
            query?: never;
            header?: {
                /** @description The `ETag` from your last read. A stale value is refused with `version_conflict` (412). */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["VersionConflict"];
        };
    };
    updateBook: {
        parameters: {
            query?: never;
            header?: {
                /** @description The `ETag` from your last read. A stale value is refused with `version_conflict` (412). */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookPatch"];
            };
        };
        responses: {
            /** @description The updated book. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Book"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description The book is under a copyright takedown and its visibility cannot be changed (`forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Another of my books in the same category already uses this title's slug (`slug_exists`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            412: components["responses"]["VersionConflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    completeBookUpload: {
        parameters: {
            query?: never;
            header?: {
                /** @description Replay protection for 24 hours. The same key with the same body replays the first response; the same key with a different body is refused with `idempotency_conflict`. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UploadComplete"];
            };
        };
        responses: {
            /** @description Processing queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueuedWork"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description No file has arrived at the upload URL yet, the ticket expired, or the file's hash does not match `sha256` (`conflict`). A book already in the library with the same file answers `slug_exists` with the existing book's id in `detail`. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getBookProcessing: {
        parameters: {
            query?: never;
            header?: {
                /** @description The `ETag` from your last read. When nothing changed the answer is `304` with no body. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The processing status. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookProcessing"];
                };
            };
            304: components["responses"]["NotModified"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listBookPages: {
        parameters: {
            query?: {
                /** @description First page of the window (1-based). Default 1. */
                from?: components["parameters"]["From"];
                /** @description Last page of the window, inclusive. Default `from + 49`, capped at the book's last page. At most 50 pages per call. */
                to?: components["parameters"]["To"];
            };
            header?: {
                /** @description The `ETag` from your last read. When nothing changed the answer is `304` with no body. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested window of pages. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageWindow"];
                };
            };
            304: components["responses"]["NotModified"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description `to` is before `from`, or the range is wider than 50 pages (`validation_failed`). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblem"];
                };
            };
        };
    };
    getBookPageText: {
        parameters: {
            query?: {
                /** @description BCP 47 language tag. A missing translation falls back to the original text plus `available_langs`. */
                lang?: components["parameters"]["Lang"];
            };
            header?: {
                /** @description The `ETag` from your last read. When nothing changed the answer is `304` with no body. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path: {
                book_id: components["parameters"]["BookId"];
                /** @description 1-based page number. */
                n: components["parameters"]["PageNumber"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The page text. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageText"];
                };
            };
            304: components["responses"]["NotModified"];
            401: components["responses"]["Unauthorized"];
            /** @description No such book or page, or the page has no text yet (`not_found`, or `needs_text` while OCR is still running). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    getBookText: {
        parameters: {
            query?: {
                /** @description First page of the window (1-based). Default 1. */
                from?: components["parameters"]["From"];
                /** @description Last page of the window, inclusive. Default `from + 49`, capped at the book's last page. At most 50 pages per call. */
                to?: components["parameters"]["To"];
                /** @description BCP 47 language tag. A missing translation falls back to the original text plus `available_langs`. */
                lang?: components["parameters"]["Lang"];
            };
            header?: {
                /** @description The `ETag` from your last read. When nothing changed the answer is `304` with no body. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The text of the requested pages. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextWindow"];
                };
            };
            304: components["responses"]["NotModified"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description `to` is before `from`, or the range is wider than 50 pages (`validation_failed`). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ValidationProblem"];
                };
            };
        };
    };
    listBookEditions: {
        parameters: {
            query?: never;
            header?: {
                /** @description The `ETag` from your last read. When nothing changed the answer is `304` with no body. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every edition of the book. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["Edition"][];
                    };
                };
            };
            304: components["responses"]["NotModified"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listBookAudio: {
        parameters: {
            query?: {
                /** @description BCP 47 language tag. A missing translation falls back to the original text plus `available_langs`. */
                lang?: components["parameters"]["Lang"];
                /** @description Only this page's track(s). */
                page?: number;
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description The `ETag` from your last read. When nothing changed the answer is `304` with no body. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of tracks. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["AudioTrack"][];
                    };
                };
            };
            304: components["responses"]["NotModified"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listBookChapters: {
        parameters: {
            query?: {
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description The `ETag` from your last read. When nothing changed the answer is `304` with no body. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of chapters. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["Chapter"][];
                    };
                };
            };
            304: components["responses"]["NotModified"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    searchLibrary: {
        parameters: {
            query: {
                /** @description What to look for. Words are matched in any order; quote a phrase to match it exactly. */
                q: components["parameters"]["Query"];
                /** @description BCP 47 language tag. A missing translation falls back to the original text plus `available_langs`. */
                lang?: components["parameters"]["Lang"];
                category?: components["schemas"]["CategorySlug"];
                kind?: "all" | "book" | "page";
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of hits. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["SearchHit"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    searchBook: {
        parameters: {
            query: {
                /** @description What to look for. Words are matched in any order; quote a phrase to match it exactly. */
                q: components["parameters"]["Query"];
                /** @description BCP 47 language tag. A missing translation falls back to the original text plus `available_langs`. */
                lang?: components["parameters"]["Lang"];
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of page hits. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["PageHit"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    listBookRatings: {
        parameters: {
            query?: {
                /** @description A field name, prefixed with `-` for descending. Each list documents the fields it allows. */
                sort?: components["parameters"]["Sort"];
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description The `ETag` from your last read. When nothing changed the answer is `304` with no body. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The summary and one page of reviews. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        summary: components["schemas"]["RatingSummary"];
                        mine: components["schemas"]["Rating"] | null;
                        data?: components["schemas"]["Rating"][];
                    };
                };
            };
            304: components["responses"]["NotModified"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    rateBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatingSave"];
            };
        };
        responses: {
            /** @description My rating and the new summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        mine: components["schemas"]["Rating"];
                        summary: components["schemas"]["RatingSummary"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    deleteMyBookRating: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listBookQuestions: {
        parameters: {
            query?: {
                answered?: boolean;
                /** @description A field name, prefixed with `-` for descending. Each list documents the fields it allows. */
                sort?: components["parameters"]["Sort"];
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description The `ETag` from your last read. When nothing changed the answer is `304` with no body. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of questions. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "Cache-Control": components["headers"]["CacheControl"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["Question"][];
                    };
                };
            };
            304: components["responses"]["NotModified"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    askBookQuestion: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on this call because it creates something or spends credits. See IdempotencyKey. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionCreate"];
            };
        };
        responses: {
            /** @description The question, pending moderation. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description The same `Idempotency-Key` was reused with a different body (`idempotency_conflict`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    voteOnBookQuestion: {
        parameters: {
            query?: never;
            header?: {
                /** @description Replay protection for 24 hours. The same key with the same body replays the first response; the same key with a different body is refused with `idempotency_conflict`. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                book_id: components["parameters"]["BookId"];
                question_id: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionVote"];
            };
        };
        responses: {
            /** @description The new tallies and my vote. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionVotes"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description The caller asked this question (`forbidden`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    reportBook: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on this call because it creates something or spends credits. See IdempotencyKey. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path: {
                book_id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookReportCreate"] | components["schemas"]["CopyrightNoticeCreate"];
            };
        };
        responses: {
            /** @description The report was received. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportReceipt"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description The same `Idempotency-Key` was reused with a different body (`idempotency_conflict`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
}
