// COPIED from ilm-red-unbound/packages/api-client by scripts/sync-api-client.mjs. Do not edit here.
// GENERATED by scripts/build-api-client.mjs from api/openapi/*.json. Do not edit by hand;
// change the contract in openapi/ and run `npm run api:spec`.

/* eslint-disable */
export interface paths {
    "/finance/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The month's headline numbers
         * @description Revenue, refunds, AI spend at provider cost, gross margin, active premium members and MRR for one month.
         */
        get: operations["financeGetKpis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List payments
         * @description Filter by `status`, `provider` and `since`. Sortable by `created_at` (default, newest first) and `amount`.
         */
        get: operations["financeListPayments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/payments/{payment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                payment_id: components["parameters"]["PaymentId"];
            };
            cookie?: never;
        };
        /** Get one payment */
        get: operations["financeGetPayment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/payments/{payment_id}/refunds": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                payment_id: components["parameters"]["PaymentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refund a payment, in full or in part
         * @description Omit `amount` for a full refund of what is still refundable. The provider refund is issued first; the credits the payment granted are then clawed back in proportion to the amount refunded (never below zero; any shortfall is reported in `credits_unrecovered`). Pass `refund_request_id` to settle a member's refund request with this refund. An amount above what is refundable is refused with `conflict`.
         */
        post: operations["financeRefundPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/refund-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List members' refund requests
         * @description Filter by `status`. Oldest first by default; sortable by `created_at` and `amount`.
         */
        get: operations["financeListRefundRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/refund-requests/{request_id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: components["parameters"]["RefundRequestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decline a refund request
         * @description The reason is shown to the member. To approve, refund the payment with `refund_request_id` set.
         */
        post: operations["financeDeclineRefundRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/premium-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List premium access requests
         * @description Oldest pending first by default. Filter by `status`. Sortable by `created_at` and `reviewed_at`.
         */
        get: operations["financeListPremiumRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/premium-requests/{request_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a premium access request
         * @description Grants the member the plan for `duration_days` without a payment, and tells them by notification and email. No money moves, but the grant gives paid access, so `X-Audit-Reason` is required and lands in the finance audit log.
         */
        post: operations["financeApprovePremiumRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/premium-requests/{request_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject a premium access request
         * @description The member sees `reason` in their notification, so write it for them. Requires `X-Audit-Reason` (the internal note for the finance audit log, never shown to the member).
         */
        post: operations["financeRejectPremiumRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/users/{user_id}/credits": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Grant or remove a member's credits
         * @description `credits` is signed: positive grants, negative removes. A removal larger than the member's balance is refused with `conflict`; nothing is taken below zero. Granted credits may carry an `expires_at`.
         */
        post: operations["financeAdjustUserCredits"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/credits/monthly-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run the monthly credit reset
         * @description Resets every member's monthly allowance for `month`. `?estimate=true` is a dry run: it reports who would be affected and how many credits would be granted, and changes nothing. A month already reset is refused with `conflict`.
         */
        post: operations["financeResetMonthlyCredits"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/cost-refunds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List credits returned for failed or bad runs
         * @description Newest first. Filter by `user_id` and `since`.
         */
        get: operations["financeListCostRefunds"];
        put?: never;
        /**
         * Give credits back for a failed or bad run
         * @description Name the `job_id` or the `order_id` the member paid for. The credits go to the member who was charged, and cannot exceed what that job or order charged (less anything already returned); more is refused with `conflict`.
         */
        post: operations["financeCreateCostRefund"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * AI usage and spend for a month
         * @description Grouped by `by` (default `kind`). Each row carries credits charged, the cost at list price, and the cost at provider price. Rows are sorted by credits, largest first.
         */
        get: operations["financeGetUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/reconciliation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reconcile a month against the providers
         * @description Provider payouts, recorded payments and credits granted, side by side, with every discrepancy found.
         */
        get: operations["financeGetReconciliation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/reconciliation/{month}/mark-reconciled": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Calendar month, `YYYY-MM`. */
                month: components["parameters"]["MonthPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close a month as reconciled
         * @description Refused with `conflict` while discrepancies remain, unless `accept_discrepancies` is true (the reason header then says why they are accepted). A month cannot be closed before it ends.
         */
        post: operations["financeMarkMonthReconciled"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Processing prices per kind and model */
        get: operations["financeListRates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change processing prices
         * @description Entries are matched by `kind` and `model`; send only the fields to change. New prices apply to estimates and jobs created after the change, never to jobs already queued.
         */
        patch: operations["financeUpdateRates"];
        trace?: never;
    };
    "/finance/billing-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Markup, monthly allowances and the per-member daily cap */
        get: operations["financeGetBillingConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change the markup, allowances or daily cap
         * @description Send only the fields to change; `monthly_allowances` entries are merged by `plan_id`.
         */
        patch: operations["financeUpdateBillingConfig"];
        trace?: never;
    };
    "/finance/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List premium plans
         * @description Filter by `active`.
         */
        get: operations["financeListPlans"];
        put?: never;
        /** Create a premium plan */
        post: operations["financeCreatePlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: components["parameters"]["PlanId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change a premium plan
         * @description Send only the fields to change. A new price applies to new subscriptions and to existing ones at their next renewal. Deactivating a plan hides it from checkout; current subscribers keep it.
         */
        patch: operations["financeUpdatePlan"];
        trace?: never;
    };
    "/finance/processors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List payment processors
         * @description Settings only. Keys and secrets are never returned; `credentials_verified` says whether the stored ones work.
         */
        get: operations["financeListProcessors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/processors/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: components["parameters"]["ProviderPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change a processor's settings
         * @description Send only the fields to change. Turning on `live` needs verified credentials and is refused with `conflict` otherwise. Credentials themselves are set outside this API.
         */
        patch: operations["financeUpdateProcessor"];
        trace?: never;
    };
    "/finance/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List invoices
         * @description Filter by `month` and `user_id`. Newest first.
         */
        get: operations["financeListInvoices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/exports/{month}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Calendar month, `YYYY-MM`. */
                month: components["parameters"]["MonthPath"];
            };
            cookie?: never;
        };
        /**
         * Download a month's ledger as CSV
         * @description One row per money or credit movement in the month (payments, refunds, credit grants and removals, cost refunds, monthly resets), with member id, amount, currency, credits, provider reference and audit id. UTF-8 with a header row.
         */
        get: operations["financeExportMonth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The finance audit log
         * @description Every Finance write, newest first. Filter by `since` and `actor`.
         */
        get: operations["financeListAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example plan_3Nc8Vr1Kq6Ty */
        PlanId: string;
        /** @example rfr_6Lp2Xw9Qa1Md */
        RefundRequestId: string;
        /** @example crf_1Zt7Mb4Rw8Kc */
        CostRefundId: string;
        /** @example 2026-08 */
        Month: string;
        /** @enum {string} */
        Provider: "helcim" | "stripe" | "paddle";
        /** @enum {string} */
        PaymentStatus: "pending" | "completed" | "failed" | "cancelled" | "refunded";
        /** @enum {string} */
        RefundRequestStatus: "requested" | "under_review" | "approved" | "denied" | "refunded";
        /** @enum {string} */
        PlanInterval: "monthly" | "yearly" | "one_time";
        Percent: number;
        /** @description Credits, signed. Positive adds, negative removes. */
        SignedCredits: number;
        /** @description An amount in the currency's minor unit. */
        MoneyInput: {
            amount_minor: number;
            currency: string;
        };
        PositiveMoneyInput: {
            amount_minor: number;
            currency: string;
        };
        Reason: string;
        Stamp: {
            audit: components["schemas"]["AuditStamp"];
        };
        /**
         * @example {
         *       "month": "2026-08",
         *       "revenue": {
         *         "amount_minor": 1284500,
         *         "currency": "USD"
         *       },
         *       "refunds": {
         *         "amount_minor": 23900,
         *         "currency": "USD"
         *       },
         *       "ai_spend_at_cost": {
         *         "amount_minor": 311200,
         *         "currency": "USD"
         *       },
         *       "gross_margin": {
         *         "amount_minor": 949400,
         *         "currency": "USD"
         *       },
         *       "gross_margin_pct": 75.3,
         *       "active_premium_members": 812,
         *       "mrr": {
         *         "amount_minor": 971200,
         *         "currency": "USD"
         *       },
         *       "generated_at": "2026-09-22T10:00:00Z"
         *     }
         */
        Kpis: {
            month: components["schemas"]["Month"];
            revenue: components["schemas"]["Money"];
            refunds: components["schemas"]["Money"];
            ai_spend_at_cost: components["schemas"]["Money"];
            gross_margin: components["schemas"]["Money"];
            /** @description Null when there was no revenue. */
            gross_margin_pct: number | null;
            active_premium_members: number;
            mrr: components["schemas"]["Money"];
            generated_at: components["schemas"]["Timestamp"];
        };
        /**
         * @example {
         *       "id": "pay_8Xq2Nc5Vb1Lk",
         *       "member": {
         *         "id": "user_7Tb3Yr2Qc9Pd",
         *         "username": "sana_reads",
         *         "display_name": "Sana Malik",
         *         "avatar_url": null
         *       },
         *       "amount": {
         *         "amount_minor": 1299,
         *         "currency": "USD"
         *       },
         *       "refunded": {
         *         "amount_minor": 0,
         *         "currency": "USD"
         *       },
         *       "provider": "stripe",
         *       "provider_reference": "pi_3PqR7sT2uV",
         *       "status": "completed",
         *       "credits_granted": 1000,
         *       "plan_id": "plan_3Nc8Vr1Kq6Ty",
         *       "receipt_url": null,
         *       "invoice_id": "inv_4Kd9Ws2Pq7Ra",
         *       "created_at": "2026-09-01T12:30:00Z",
         *       "completed_at": "2026-09-01T12:30:04Z"
         *     }
         */
        Payment: {
            id: components["schemas"]["PaymentId"];
            member: components["schemas"]["UserSummary"];
            amount: components["schemas"]["Money"];
            refunded: components["schemas"]["Money"];
            provider: components["schemas"]["Provider"];
            /** @description The provider's payment id, for looking it up in their dashboard. */
            provider_reference?: string | null;
            status: components["schemas"]["PaymentStatus"];
            credits_granted: components["schemas"]["Credits"];
            plan_id?: components["schemas"]["PlanId"] | null;
            /** Format: uri */
            receipt_url?: string | null;
            invoice_id?: components["schemas"]["InvoiceId"] | null;
            created_at: components["schemas"]["Timestamp"];
            /** Format: date-time */
            completed_at?: string | null;
        };
        RefundCreate: {
            /** @description Omit for a full refund of what is still refundable. Must be in the payment's currency. */
            amount?: components["schemas"]["PositiveMoneyInput"];
            refund_request_id?: components["schemas"]["RefundRequestId"];
        };
        /**
         * @example {
         *       "id": "rfd_2Wc6Pz9Lt4Qb",
         *       "payment_id": "pay_8Xq2Nc5Vb1Lk",
         *       "refund_request_id": "rfr_6Lp2Xw9Qa1Md",
         *       "amount": {
         *         "amount_minor": 650,
         *         "currency": "USD"
         *       },
         *       "status": "succeeded",
         *       "provider_reference": "re_3PqR9xY1",
         *       "credits_clawed_back": 500,
         *       "credits_unrecovered": 0,
         *       "created_at": "2026-09-22T10:05:00Z"
         *     }
         */
        Refund: {
            id: components["schemas"]["RefundId"];
            payment_id: components["schemas"]["PaymentId"];
            refund_request_id?: components["schemas"]["RefundRequestId"] | null;
            amount: components["schemas"]["Money"];
            /** @enum {string} */
            status: "pending" | "succeeded" | "failed";
            provider_reference?: string | null;
            credits_clawed_back: components["schemas"]["Credits"];
            credits_unrecovered?: components["schemas"]["Credits"];
            created_at: components["schemas"]["Timestamp"];
        };
        RefundResult: components["schemas"]["Stamp"] & {
            refund: components["schemas"]["Refund"];
            payment: components["schemas"]["Payment"];
        };
        /**
         * @example {
         *       "id": "rfr_6Lp2Xw9Qa1Md",
         *       "payment_id": "pay_8Xq2Nc5Vb1Lk",
         *       "member": {
         *         "id": "user_7Tb3Yr2Qc9Pd",
         *         "username": "sana_reads",
         *         "display_name": "Sana Malik",
         *         "avatar_url": null
         *       },
         *       "claim_type": "failed_processing",
         *       "requested": {
         *         "amount_minor": 650,
         *         "currency": "USD"
         *       },
         *       "refundable": {
         *         "amount_minor": 1299,
         *         "currency": "USD"
         *       },
         *       "reason": "The translation of my book stopped halfway.",
         *       "status": "requested",
         *       "decided_at": null,
         *       "decided_by": null,
         *       "decision_reason": null,
         *       "refund_id": null,
         *       "created_at": "2026-09-21T18:00:00Z"
         *     }
         */
        RefundRequest: {
            id: components["schemas"]["RefundRequestId"];
            payment_id: components["schemas"]["PaymentId"];
            member: components["schemas"]["UserSummary"];
            /** @enum {string} */
            claim_type: "standard" | "error" | "duplicate" | "failed_processing";
            requested: components["schemas"]["Money"];
            refundable: components["schemas"]["Money"];
            /** @description The member's own words. */
            reason?: string | null;
            status: components["schemas"]["RefundRequestStatus"];
            /** Format: date-time */
            decided_at?: string | null;
            decided_by?: components["schemas"]["UserSummary"] | null;
            decision_reason?: string | null;
            refund_id?: components["schemas"]["RefundId"] | null;
            created_at: components["schemas"]["Timestamp"];
        };
        RefundRequestDecline: {
            reason: components["schemas"]["Reason"];
        };
        RefundRequestChange: components["schemas"]["Stamp"] & {
            request: components["schemas"]["RefundRequest"];
        };
        /** @enum {string} */
        PremiumRequestStatus: "pending" | "approved" | "rejected";
        /**
         * @example {
         *       "id": "req_5Wd8Kq2Lm1Za",
         *       "status": "pending",
         *       "requester": {
         *         "id": "user_4Fq9ZtW1Lm8K",
         *         "username": "bilgrami",
         *         "display_name": "Bill Bilgrami",
         *         "avatar_url": null
         *       },
         *       "organization": "Lahore University Library",
         *       "user_type": "educator",
         *       "use_case": "Reading circle of 20 students working through Urdu classics.",
         *       "current_usage": "Free plan, about 5 books a week.",
         *       "interested_features": [
         *         "narration",
         *         "translation"
         *       ],
         *       "team_size": "11-50",
         *       "timeline": "This semester",
         *       "additional_notes": null,
         *       "staff_note": null,
         *       "reviewed_at": null,
         *       "created_at": "2026-09-20T15:40:00Z"
         *     }
         */
        PremiumRequest: {
            id: components["schemas"]["RequestId"];
            status: components["schemas"]["PremiumRequestStatus"];
            requester: components["schemas"]["UserSummary"];
            /**
             * Format: email
             * @description Only for callers holding `view_user_pii`.
             */
            email?: string;
            organization?: string | null;
            /** @description How the requester describes themselves, e.g. `student`, `researcher`, `educator`. */
            user_type: string;
            use_case: string;
            current_usage?: string | null;
            interested_features: string[];
            team_size?: string | null;
            timeline?: string | null;
            additional_notes?: string | null;
            /** @description The note or reason from the decision. */
            staff_note?: string | null;
            reviewed_by?: components["schemas"]["UserSummary"];
            /** Format: date-time */
            reviewed_at?: string | null;
            created_at: components["schemas"]["Timestamp"];
        };
        PremiumApproval: {
            /** @description The plan to grant, e.g. `premium` or `educator`. */
            plan: string;
            duration_days: number;
            /** @description Shown to the member with the approval. */
            note?: string;
        };
        PremiumRejection: {
            reason: string;
        };
        CreditAdjustment: {
            credits: components["schemas"]["SignedCredits"] & unknown;
            /** @description Shown to the member in their credit history. */
            reason: components["schemas"]["Reason"];
            /**
             * Format: date-time
             * @description Only for grants. Unused granted credits lapse at this time.
             */
            expires_at?: string;
        };
        /**
         * @example {
         *       "user_id": "user_7Tb3Yr2Qc9Pd",
         *       "credits": 250,
         *       "balance": 1180.5,
         *       "expires_at": "2026-12-31T23:59:59Z",
         *       "audit": {
         *         "audit_id": "audit_4Tz8Qm1Kc6Wv",
         *         "at": "2026-09-22T10:10:00Z",
         *         "actor": {
         *           "id": "user_4Fq9ZtW1Lm8K",
         *           "username": "bilgrami",
         *           "display_name": "Bilal Bilgrami",
         *           "avatar_url": null
         *         }
         *       }
         *     }
         */
        CreditAdjustmentResult: {
            user_id: components["schemas"]["UserId"];
            credits: components["schemas"]["SignedCredits"];
            balance: components["schemas"]["Credits"];
            /** Format: date-time */
            expires_at?: string | null;
            audit: components["schemas"]["AuditStamp"];
        };
        MonthlyResetRequest: {
            month: components["schemas"]["Month"];
        };
        /**
         * @example {
         *       "month": "2026-10",
         *       "dry_run": true,
         *       "members_affected": 812,
         *       "credits_granted": 812000,
         *       "credits_lapsed": 94210.25,
         *       "audit": null
         *     }
         */
        MonthlyResetResult: {
            month: components["schemas"]["Month"];
            dry_run: boolean;
            members_affected: number;
            credits_granted: components["schemas"]["Credits"];
            credits_lapsed?: components["schemas"]["Credits"];
            /** @description Null on a dry run, which changes nothing. */
            audit?: components["schemas"]["AuditStamp"] | null;
        };
        /**
         * @example {
         *       "id": "crf_1Zt7Mb4Rw8Kc",
         *       "job_id": "job_5Rt8Kq2Mn4Vb",
         *       "order_id": null,
         *       "member": {
         *         "id": "user_7Tb3Yr2Qc9Pd",
         *         "username": "sana_reads",
         *         "display_name": "Sana Malik",
         *         "avatar_url": null
         *       },
         *       "credits": 121,
         *       "reason": "Translation dead-lettered after three provider timeouts.",
         *       "created_at": "2026-09-22T10:12:00Z",
         *       "created_by": {
         *         "id": "user_4Fq9ZtW1Lm8K",
         *         "username": "bilgrami",
         *         "display_name": "Bilal Bilgrami",
         *         "avatar_url": null
         *       }
         *     }
         */
        CostRefund: {
            id: components["schemas"]["CostRefundId"];
            job_id?: components["schemas"]["JobId"] | null;
            order_id?: components["schemas"]["OrderId"] | null;
            member: components["schemas"]["UserSummary"];
            credits: components["schemas"]["Credits"];
            reason: string;
            created_at: components["schemas"]["Timestamp"];
            created_by: components["schemas"]["UserSummary"];
        };
        /** @description Name exactly one of `job_id` or `order_id`. */
        CostRefundCreate: {
            job_id: components["schemas"]["JobId"];
            credits: number;
            reason: components["schemas"]["Reason"];
        } | {
            order_id: components["schemas"]["OrderId"];
            credits: number;
            reason: components["schemas"]["Reason"];
        };
        CostRefundResult: components["schemas"]["Stamp"] & {
            cost_refund: components["schemas"]["CostRefund"];
        };
        /**
         * @example {
         *       "group": {
         *         "by": "kind",
         *         "id": null,
         *         "label": "translate"
         *       },
         *       "credits": 184220,
         *       "cost_at_list": {
         *         "amount_minor": 184220,
         *         "currency": "USD"
         *       },
         *       "cost_at_provider": {
         *         "amount_minor": 121400,
         *         "currency": "USD"
         *       },
         *       "requests": 5321,
         *       "tokens": 91822000
         *     }
         */
        UsageRow: {
            /** @description What the row is for. `id` is the user or club id for those groupings, else null. */
            group: {
                /** @enum {string} */
                by: "user" | "kind" | "model" | "club";
                id?: string | null;
                label: string;
            };
            credits: components["schemas"]["Credits"];
            cost_at_list: components["schemas"]["Money"];
            cost_at_provider: components["schemas"]["Money"];
            requests: number;
            tokens?: number;
        };
        UsageTotals: {
            credits: components["schemas"]["Credits"];
            cost_at_list: components["schemas"]["Money"];
            cost_at_provider: components["schemas"]["Money"];
        };
        /**
         * @example {
         *       "month": "2026-08",
         *       "status": "open",
         *       "provider_payouts": [
         *         {
         *           "provider": "stripe",
         *           "amount": {
         *             "amount_minor": 1240100,
         *             "currency": "USD"
         *           },
         *           "fees": {
         *             "amount_minor": 38100,
         *             "currency": "USD"
         *           }
         *         }
         *       ],
         *       "recorded_payments": {
         *         "amount_minor": 1284500,
         *         "currency": "USD"
         *       },
         *       "credits_granted": 1021400,
         *       "discrepancies": [
         *         {
         *           "type": "missing_payment",
         *           "provider": "stripe",
         *           "payment_id": null,
         *           "provider_reference": "pi_3PqZ1aB7cD",
         *           "expected": {
         *             "amount_minor": 1299,
         *             "currency": "USD"
         *           },
         *           "actual": null,
         *           "detail": "Paid at the provider, no completed payment recorded."
         *         }
         *       ],
         *       "reconciled_at": null,
         *       "reconciled_by": null
         *     }
         */
        Reconciliation: {
            month: components["schemas"]["Month"];
            /** @enum {string} */
            status: "open" | "reconciled";
            provider_payouts: {
                provider: components["schemas"]["Provider"];
                amount: components["schemas"]["Money"];
                fees?: components["schemas"]["Money"];
            }[];
            recorded_payments: components["schemas"]["Money"];
            credits_granted: components["schemas"]["Credits"];
            discrepancies: {
                /** @enum {string} */
                type: "missing_payment" | "missing_payout" | "amount_mismatch" | "credits_mismatch" | "duplicate";
                provider: components["schemas"]["Provider"];
                payment_id?: components["schemas"]["PaymentId"] | null;
                provider_reference?: string | null;
                expected?: components["schemas"]["Money"] | null;
                actual?: components["schemas"]["Money"] | null;
                detail: string;
            }[];
            /** Format: date-time */
            reconciled_at?: string | null;
            reconciled_by?: components["schemas"]["UserSummary"] | null;
        };
        MarkReconciled: {
            /** @default false */
            accept_discrepancies: boolean;
        };
        ReconciliationChange: components["schemas"]["Stamp"] & {
            reconciliation: components["schemas"]["Reconciliation"];
        };
        Rate: {
            kind: string;
            model: string;
            label?: string | null;
            /** @description What one unit is (page, minute, thousand_characters, image). */
            unit: string;
            price_per_unit: components["schemas"]["Credits"];
            /** @description What the provider charges us per unit, in US dollars. */
            provider_cost_usd_per_unit: number;
            margin_pct: number;
            /** @description The model used for this kind when a job names none. */
            is_default: boolean;
            us_based?: boolean;
            updated_at: components["schemas"]["Timestamp"];
        };
        /**
         * @example {
         *       "data": [
         *         {
         *           "kind": "translate",
         *           "model": "claude-sonnet-4-5",
         *           "label": "Translate (standard)",
         *           "unit": "page",
         *           "price_per_unit": 4.5,
         *           "provider_cost_usd_per_unit": 0.031,
         *           "margin_pct": 45.16,
         *           "is_default": true,
         *           "us_based": true,
         *           "updated_at": "2026-09-01T00:00:00Z"
         *         }
         *       ]
         *     }
         */
        RateTable: {
            data: components["schemas"]["Rate"][];
        };
        RatesPatch: {
            rates: {
                kind: string;
                model: string;
                unit?: string;
                price_per_unit?: number;
                provider_cost_usd_per_unit?: number;
                is_default?: boolean;
            }[];
        };
        RateTableChange: components["schemas"]["Stamp"] & {
            rates: components["schemas"]["RateTable"];
        };
        /**
         * @example {
         *       "markup_pct": 45,
         *       "monthly_allowances": [
         *         {
         *           "plan_id": "plan_3Nc8Vr1Kq6Ty",
         *           "credits": 1000
         *         }
         *       ],
         *       "free_monthly_allowance": 50,
         *       "member_daily_cap": 400,
         *       "updated_at": "2026-09-01T00:00:00Z"
         *     }
         */
        BillingConfig: {
            /** @description Added to provider cost to get list price. */
            markup_pct: number;
            monthly_allowances: {
                plan_id: components["schemas"]["PlanId"];
                credits: components["schemas"]["Credits"];
            }[];
            free_monthly_allowance?: components["schemas"]["Credits"];
            /** @description Credits one member may spend per day; null for no cap. */
            member_daily_cap: number | null;
            updated_at: components["schemas"]["Timestamp"];
        };
        BillingConfigPatch: {
            markup_pct?: components["schemas"]["Percent"];
            monthly_allowances?: {
                plan_id: components["schemas"]["PlanId"];
                credits: number;
            }[];
            free_monthly_allowance?: number;
            member_daily_cap?: number | null;
        };
        BillingConfigChange: components["schemas"]["Stamp"] & {
            config: components["schemas"]["BillingConfig"];
        };
        /**
         * @example {
         *       "id": "plan_3Nc8Vr1Kq6Ty",
         *       "name": "Premium monthly",
         *       "description": "Unlimited reading, narration and 1,000 AI credits a month.",
         *       "price": {
         *         "amount_minor": 1299,
         *         "currency": "USD"
         *       },
         *       "interval": "monthly",
         *       "monthly_credits": 1000,
         *       "active": true,
         *       "subscribers": 640,
         *       "created_at": "2026-01-10T00:00:00Z",
         *       "updated_at": "2026-09-01T00:00:00Z"
         *     }
         */
        Plan: {
            id: components["schemas"]["PlanId"];
            name: string;
            description?: string | null;
            price: components["schemas"]["Money"];
            interval: components["schemas"]["PlanInterval"];
            monthly_credits: components["schemas"]["Credits"];
            active: boolean;
            subscribers?: number;
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
        };
        PlanCreate: {
            name: string;
            description?: string;
            price: components["schemas"]["MoneyInput"];
            interval: components["schemas"]["PlanInterval"];
            monthly_credits: number;
            /** @default true */
            active: boolean;
        };
        PlanPatch: {
            name?: string;
            description?: string | null;
            price?: components["schemas"]["MoneyInput"];
            interval?: components["schemas"]["PlanInterval"];
            monthly_credits?: number;
            active?: boolean;
        };
        PlanChange: components["schemas"]["Stamp"] & {
            plan: components["schemas"]["Plan"];
        };
        /**
         * @example {
         *       "provider": "stripe",
         *       "enabled": true,
         *       "live": true,
         *       "checkout_mode": "embedded",
         *       "credentials_verified": true,
         *       "last_webhook_at": "2026-09-22T09:59:40Z",
         *       "updated_at": "2026-08-14T12:00:00Z"
         *     }
         */
        Processor: {
            provider: components["schemas"]["Provider"];
            enabled: boolean;
            /** @description False means test mode. */
            live: boolean;
            /** @enum {string} */
            checkout_mode: "redirect" | "embedded";
            /** @description Whether the stored credentials answered a test call. The credentials are never returned. */
            credentials_verified: boolean;
            /** Format: date-time */
            last_webhook_at?: string | null;
            updated_at: components["schemas"]["Timestamp"];
        };
        ProcessorPatch: {
            enabled?: boolean;
            live?: boolean;
            /** @enum {string} */
            checkout_mode?: "redirect" | "embedded";
        };
        ProcessorChange: components["schemas"]["Stamp"] & {
            processor: components["schemas"]["Processor"];
        };
        /**
         * @example {
         *       "id": "inv_4Kd9Ws2Pq7Ra",
         *       "number": "ILM-2026-09-00412",
         *       "member": {
         *         "id": "user_7Tb3Yr2Qc9Pd",
         *         "username": "sana_reads",
         *         "display_name": "Sana Malik",
         *         "avatar_url": null
         *       },
         *       "month": "2026-09",
         *       "total": {
         *         "amount_minor": 1299,
         *         "currency": "USD"
         *       },
         *       "status": "paid",
         *       "payment_id": "pay_8Xq2Nc5Vb1Lk",
         *       "url": null,
         *       "issued_at": "2026-09-01T12:30:04Z"
         *     }
         */
        Invoice: {
            id: components["schemas"]["InvoiceId"];
            number?: string | null;
            member: components["schemas"]["UserSummary"];
            month: components["schemas"]["Month"];
            total: components["schemas"]["Money"];
            /** @enum {string} */
            status: "open" | "paid" | "refunded" | "partially_refunded" | "void";
            payment_id?: components["schemas"]["PaymentId"] | null;
            /** Format: uri */
            url?: string | null;
            issued_at: components["schemas"]["Timestamp"];
        };
        /**
         * @example {
         *       "id": "audit_4Tz8Qm1Kc6Wv",
         *       "at": "2026-09-22T10:10:00Z",
         *       "actor": {
         *         "id": "user_4Fq9ZtW1Lm8K",
         *         "username": "bilgrami",
         *         "display_name": "Bilal Bilgrami",
         *         "avatar_url": null
         *       },
         *       "action": "financeAdjustUserCredits",
         *       "target": {
         *         "type": "user",
         *         "id": "user_7Tb3Yr2Qc9Pd"
         *       },
         *       "reason": "Goodwill for the stalled translation reported in rfr_6Lp2Xw9Qa1Md.",
         *       "before": {
         *         "balance": 930.5
         *       },
         *       "after": {
         *         "balance": 1180.5
         *       },
         *       "request_id": "req_9Vx3Kp7Wm2Qa"
         *     }
         */
        AuditEntry: {
            id: components["schemas"]["AuditId"];
            at: components["schemas"]["Timestamp"];
            actor: components["schemas"]["UserSummary"];
            /** @description The operationId of the write. */
            action: string;
            target: {
                type: string;
                id: string;
            };
            reason: string;
            before?: Record<string, never> | null;
            after?: Record<string, never> | null;
            request_id?: string | null;
        };
        /** @description Every list returns this envelope. `next_cursor` is null on the last page. */
        Page: {
            data: unknown[];
            next_cursor: string | null;
        };
        /** @description RFC 9457 problem document. Branch on `slug` (also the last segment of `type`), show `title`, quote `request_id`. */
        Problem: {
            /**
             * Format: uri
             * @example https://api.ilm.red/problems/not_found
             */
            type: string;
            slug: components["schemas"]["ProblemSlug"];
            title: string;
            status: number;
            detail?: string;
            request_id: string;
        };
        /**
         * Format: date-time
         * @example 2026-09-22T18:04:05Z
         */
        Timestamp: string;
        /** @description Returned by every staff write, so the caller can quote the audit entry. */
        AuditStamp: {
            audit_id: components["schemas"]["AuditId"];
            at: components["schemas"]["Timestamp"];
            actor: components["schemas"]["UserSummary"];
        };
        /** @example user_4Fq9ZtW1Lm8K */
        UserId: string;
        PaymentId: string;
        RequestId: string;
        ValidationProblem: components["schemas"]["Problem"] & {
            errors: components["schemas"]["FieldError"][];
        };
        /**
         * @description The stable part of a problem. Branch on this, never on `title` or `detail`.
         * @enum {string}
         */
        ProblemSlug: "unauthorized" | "key_invalid" | "key_revoked" | "key_expired" | "scope_missing" | "not_club_admin" | "club_quota_reached" | "internal_only" | "not_found" | "term_not_found" | "slug_exists" | "edge_would_cycle" | "drop_not_ready" | "needs_text" | "needs_pages" | "needs_translation" | "paper_locked" | "term_has_edges" | "paper_not_in_club" | "revision_required" | "plan_refused" | "duplicate_brief" | "review_forbidden" | "already_reviewed" | "club_required" | "brief_invalid" | "cost_cap_exceeded" | "repair_invalid" | "idempotency_conflict" | "validation_failed" | "unsupported_kind" | "rate_limited" | "extract_rate_limited" | "internal_error" | "forbidden" | "premium_required" | "insufficient_credits" | "reauth_required" | "version_conflict" | "conflict" | "gone" | "payload_too_large" | "unsupported_media_type" | "quote_expired" | "agent_cap_reached" | "lock_held";
        AuditId: string;
        /** @description How a person appears anywhere they are named. Never an email. */
        UserSummary: {
            id: components["schemas"]["UserId"];
            username: components["schemas"]["Username"];
            display_name: string;
            /** Format: uri */
            avatar_url?: string | null;
        };
        /** @description An amount in the currency's minor unit (cents for USD). */
        Money: {
            /** @example 1299 */
            amount_minor: number;
            /** @example USD */
            currency: string;
        };
        /** @example bilgrami */
        Username: string;
        /** @description Credits, rounded by the server to four decimal places. One credit is one US cent of model spend at list price. */
        Credits: number;
        InvoiceId: string;
        RefundId: string;
        JobId: string;
        OrderId: string;
        FieldError: {
            /**
             * @description Where the problem is, as a JSON Pointer into the request, prefixed with its part.
             * @example /body/title
             * @example /query/limit
             * @example /path/book_id
             * @example /header/Idempotency-Key
             */
            path: string;
            /**
             * @description Which rule failed.
             * @enum {string}
             */
            code: "required" | "type" | "enum" | "const" | "pattern" | "format" | "min_length" | "max_length" | "minimum" | "maximum" | "multiple_of" | "min_items" | "max_items" | "unique_items" | "unknown_field" | "one_of";
            /** @example must be at most 200 characters */
            message: string;
            /** @description The limit that was broken, when the rule has one (a length, a bound, the allowed values). */
            limit?: unknown;
        };
    };
    responses: {
        /** @description No credential, or a credential that is not valid (`unauthorized`, `key_invalid`, `key_revoked`, `key_expired`, `reauth_required`). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The caller is known but may not do this (`forbidden`, `scope_missing`, `premium_required`, `internal_only`). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The request failed validation (`validation_failed`). `errors` lists every failing field, not just the first. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ValidationProblem"];
            };
        };
        /** @description No such resource, or one the caller may not see (`not_found`). The two are deliberately indistinguishable. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description `If-Match` did not match the current version (`version_conflict`). Read again and retry. */
        VersionConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        PaymentId: components["schemas"]["PaymentId"];
        RefundRequestId: components["schemas"]["RefundRequestId"];
        PremiumRequestId: components["schemas"]["RequestId"];
        PlanId: components["schemas"]["PlanId"];
        ProviderPath: components["schemas"]["Provider"];
        /** @description Calendar month, `YYYY-MM`. */
        MonthPath: components["schemas"]["Month"];
        /** @description Calendar month, `YYYY-MM`. */
        MonthOptional: components["schemas"]["Month"];
        /** @description Calendar month, `YYYY-MM`. */
        Month: string;
        Since: string;
        /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
        Cursor: string;
        /** @description Page size. */
        Limit: number;
        /** @description A field name, prefixed with `-` for descending. Each list documents the fields it allows. */
        Sort: string;
        /** @description Why this change is being made. Stored in the audit log with the actor and the target. */
        AuditReason: string;
        /** @description Required on this call because it creates something or spends credits. See IdempotencyKey. */
        IdempotencyKeyRequired: string;
        /** @description Replay protection for 24 hours. The same key with the same body replays the first response; the same key with a different body is refused with `idempotency_conflict`. */
        IdempotencyKey: string;
        UserId: components["schemas"]["UserId"];
        /** @description When true, return the price of the call and run nothing. */
        Estimate: boolean;
        /** @description The `ETag` from your last read. A stale value is refused with `version_conflict` (412). */
        IfMatch: string;
    };
    requestBodies: never;
    headers: {
        /** @description URL of the resource just created. */
        Location: string;
        /** @description Version of the resource, for caching and for `If-Match` on the next write. */
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    financeGetKpis: {
        parameters: {
            query: {
                /** @description Calendar month, `YYYY-MM`. */
                month: components["parameters"]["Month"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The month's numbers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Kpis"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    financeListPayments: {
        parameters: {
            query?: {
                status?: components["schemas"]["PaymentStatus"];
                provider?: components["schemas"]["Provider"];
                since?: components["parameters"]["Since"];
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
                /** @description A field name, prefixed with `-` for descending. Each list documents the fields it allows. */
                sort?: components["parameters"]["Sort"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of payments. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["Payment"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    financeGetPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                payment_id: components["parameters"]["PaymentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The payment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    financeRefundPayment: {
        parameters: {
            query?: never;
            header: {
                /** @description Why this change is being made. Stored in the audit log with the actor and the target. */
                "X-Audit-Reason": components["parameters"]["AuditReason"];
                /** @description Required on this call because it creates something or spends credits. See IdempotencyKey. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path: {
                payment_id: components["parameters"]["PaymentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefundCreate"];
            };
        };
        responses: {
            /** @description The refund. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefundResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The payment is not completed, is already fully refunded, or the amount exceeds what is refundable (`conflict`); or the key was reused with a different body (`idempotency_conflict`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    financeListRefundRequests: {
        parameters: {
            query?: {
                status?: components["schemas"]["RefundRequestStatus"];
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
                /** @description A field name, prefixed with `-` for descending. Each list documents the fields it allows. */
                sort?: components["parameters"]["Sort"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of refund requests. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["RefundRequest"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    financeDeclineRefundRequest: {
        parameters: {
            query?: never;
            header: {
                /** @description Why this change is being made. Stored in the audit log with the actor and the target. */
                "X-Audit-Reason": components["parameters"]["AuditReason"];
                /** @description Replay protection for 24 hours. The same key with the same body replays the first response; the same key with a different body is refused with `idempotency_conflict`. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                request_id: components["parameters"]["RefundRequestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefundRequestDecline"];
            };
        };
        responses: {
            /** @description The declined request. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefundRequestChange"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The request was already decided (`conflict`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    financeListPremiumRequests: {
        parameters: {
            query?: {
                status?: components["schemas"]["PremiumRequestStatus"];
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
                /** @description A field name, prefixed with `-` for descending. Each list documents the fields it allows. */
                sort?: components["parameters"]["Sort"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of requests. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["PremiumRequest"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    financeApprovePremiumRequest: {
        parameters: {
            query?: never;
            header: {
                /** @description Why this change is being made. Stored in the audit log with the actor and the target. */
                "X-Audit-Reason": components["parameters"]["AuditReason"];
                /** @description Replay protection for 24 hours. The same key with the same body replays the first response; the same key with a different body is refused with `idempotency_conflict`. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                request_id: components["parameters"]["PremiumRequestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PremiumApproval"];
            };
        };
        responses: {
            /** @description The approved request and when the grant ends. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        request: components["schemas"]["PremiumRequest"];
                        premium_until: components["schemas"]["Timestamp"];
                        audit: components["schemas"]["AuditStamp"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The request was already decided (`conflict`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    financeRejectPremiumRequest: {
        parameters: {
            query?: never;
            header: {
                /** @description Why this change is being made. Stored in the audit log with the actor and the target. */
                "X-Audit-Reason": components["parameters"]["AuditReason"];
                /** @description Replay protection for 24 hours. The same key with the same body replays the first response; the same key with a different body is refused with `idempotency_conflict`. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                request_id: components["parameters"]["PremiumRequestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PremiumRejection"];
            };
        };
        responses: {
            /** @description The rejected request. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PremiumRequest"] & components["schemas"]["Stamp"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The request was already decided (`conflict`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    financeAdjustUserCredits: {
        parameters: {
            query?: never;
            header: {
                /** @description Why this change is being made. Stored in the audit log with the actor and the target. */
                "X-Audit-Reason": components["parameters"]["AuditReason"];
                /** @description Required on this call because it creates something or spends credits. See IdempotencyKey. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path: {
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreditAdjustment"];
            };
        };
        responses: {
            /** @description The adjustment and the member's new balance. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditAdjustmentResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The removal exceeds the balance (`conflict`), or the key was reused with a different body (`idempotency_conflict`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    financeResetMonthlyCredits: {
        parameters: {
            query?: {
                /** @description When true, return the price of the call and run nothing. */
                estimate?: components["parameters"]["Estimate"];
            };
            header: {
                /** @description Why this change is being made. Stored in the audit log with the actor and the target. */
                "X-Audit-Reason": components["parameters"]["AuditReason"];
                /** @description Required on this call because it creates something or spends credits. See IdempotencyKey. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonthlyResetRequest"];
            };
        };
        responses: {
            /** @description The reset result, or the dry run when `estimate=true`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyResetResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description That month was already reset (`conflict`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    financeListCostRefunds: {
        parameters: {
            query?: {
                user_id?: components["schemas"]["UserId"];
                since?: components["parameters"]["Since"];
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of cost refunds. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["CostRefund"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    financeCreateCostRefund: {
        parameters: {
            query?: never;
            header: {
                /** @description Why this change is being made. Stored in the audit log with the actor and the target. */
                "X-Audit-Reason": components["parameters"]["AuditReason"];
                /** @description Required on this call because it creates something or spends credits. See IdempotencyKey. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CostRefundCreate"];
            };
        };
        responses: {
            /** @description The cost refund. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostRefundResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description More credits than were charged (`conflict`), or the key was reused with a different body (`idempotency_conflict`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    financeGetUsage: {
        parameters: {
            query: {
                /** @description Calendar month, `YYYY-MM`. */
                month: components["parameters"]["Month"];
                by?: "user" | "kind" | "model" | "club";
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of usage rows, plus the month's totals. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        totals: components["schemas"]["UsageTotals"];
                        data?: components["schemas"]["UsageRow"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    financeGetReconciliation: {
        parameters: {
            query: {
                /** @description Calendar month, `YYYY-MM`. */
                month: components["parameters"]["Month"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The month's reconciliation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reconciliation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    financeMarkMonthReconciled: {
        parameters: {
            query?: never;
            header: {
                /** @description Why this change is being made. Stored in the audit log with the actor and the target. */
                "X-Audit-Reason": components["parameters"]["AuditReason"];
                /** @description Replay protection for 24 hours. The same key with the same body replays the first response; the same key with a different body is refused with `idempotency_conflict`. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description Calendar month, `YYYY-MM`. */
                month: components["parameters"]["MonthPath"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MarkReconciled"];
            };
        };
        responses: {
            /** @description The month, now reconciled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationChange"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Discrepancies remain, the month has not ended, or it is already reconciled (`conflict`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    financeListRates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The rate table. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateTable"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    financeUpdateRates: {
        parameters: {
            query?: never;
            header: {
                /** @description Why this change is being made. Stored in the audit log with the actor and the target. */
                "X-Audit-Reason": components["parameters"]["AuditReason"];
                /** @description The `ETag` from your last read. A stale value is refused with `version_conflict` (412). */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatesPatch"];
            };
        };
        responses: {
            /** @description The updated rate table. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateTableChange"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["VersionConflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    financeGetBillingConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The billing configuration. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingConfig"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    financeUpdateBillingConfig: {
        parameters: {
            query?: never;
            header: {
                /** @description Why this change is being made. Stored in the audit log with the actor and the target. */
                "X-Audit-Reason": components["parameters"]["AuditReason"];
                /** @description The `ETag` from your last read. A stale value is refused with `version_conflict` (412). */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BillingConfigPatch"];
            };
        };
        responses: {
            /** @description The updated configuration. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingConfigChange"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["VersionConflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    financeListPlans: {
        parameters: {
            query?: {
                active?: boolean;
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of plans. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["Plan"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    financeCreatePlan: {
        parameters: {
            query?: never;
            header: {
                /** @description Why this change is being made. Stored in the audit log with the actor and the target. */
                "X-Audit-Reason": components["parameters"]["AuditReason"];
                /** @description Required on this call because it creates something or spends credits. See IdempotencyKey. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanCreate"];
            };
        };
        responses: {
            /** @description The new plan. */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanChange"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description A plan with that name already exists (`conflict`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    financeUpdatePlan: {
        parameters: {
            query?: never;
            header: {
                /** @description Why this change is being made. Stored in the audit log with the actor and the target. */
                "X-Audit-Reason": components["parameters"]["AuditReason"];
                /** @description The `ETag` from your last read. A stale value is refused with `version_conflict` (412). */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                plan_id: components["parameters"]["PlanId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanPatch"];
            };
        };
        responses: {
            /** @description The updated plan. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanChange"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["VersionConflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    financeListProcessors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every processor. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Processor"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    financeUpdateProcessor: {
        parameters: {
            query?: never;
            header: {
                /** @description Why this change is being made. Stored in the audit log with the actor and the target. */
                "X-Audit-Reason": components["parameters"]["AuditReason"];
                /** @description The `ETag` from your last read. A stale value is refused with `version_conflict` (412). */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                provider: components["parameters"]["ProviderPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcessorPatch"];
            };
        };
        responses: {
            /** @description The updated processor. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessorChange"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Going live without verified credentials, or disabling the only enabled processor (`conflict`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            412: components["responses"]["VersionConflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    financeListInvoices: {
        parameters: {
            query?: {
                /** @description Calendar month, `YYYY-MM`. */
                month?: components["parameters"]["MonthOptional"];
                user_id?: components["schemas"]["UserId"];
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of invoices. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["Invoice"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    financeExportMonth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Calendar month, `YYYY-MM`. */
                month: components["parameters"]["MonthPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The CSV file. */
            200: {
                headers: {
                    /** @description Always `attachment; filename="ilm-red-ledger-YYYY-MM.csv"`. */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    financeListAudit: {
        parameters: {
            query?: {
                since?: components["parameters"]["Since"];
                actor?: components["schemas"]["UserId"];
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of audit entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["AuditEntry"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
}
