// COPIED from ilm-red-unbound/packages/api-client by scripts/sync-api-client.mjs. Do not edit here.
// GENERATED by scripts/build-api-client.mjs from api/openapi/*.json. Do not edit by hand;
// change the contract in openapi/ and run `npm run api:spec`.

/* eslint-disable */
export interface paths {
    "/super-admin/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List roles and their permissions */
        get: operations["superAdminListRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/super-admin/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List permission keys and the roles that hold them */
        get: operations["superAdminListPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/super-admin/users/{user_id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Set a person's roles
         * @description Replaces the person's full set of roles with `roles`; send `[]` to leave them an ordinary member. Returns the set before and after. Removing the last `super_admin`, or your own `super_admin` role, is refused with `conflict`. Requires a sign-in within the last 10 minutes (401 `reauth_required` otherwise) and `X-Audit-Reason`.
         */
        put: operations["superAdminSetUserRoles"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/super-admin/role-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History of role grants and removals
         * @description Newest first. Filter by `user_id` (the person whose roles changed) and `since`.
         */
        get: operations["superAdminListRoleLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/super-admin/impersonation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start seeing ilm.red as a member
         * @description Returns a short-lived session token that acts as the target member, for at most 30 minutes. The token cannot reach any staff surface, change the member's password, email, roles or payment details, or start another impersonation; every call made with it is logged against you. Another staff member cannot be impersonated (`forbidden`). One impersonation at a time: starting a second ends the first. Requires a sign-in within the last 10 minutes (401 `reauth_required` otherwise) and `X-Audit-Reason`, which is also shown in the member's account activity.
         */
        post: operations["superAdminStartImpersonation"];
        /**
         * End my impersonation
         * @description Ends the caller's active impersonation and revokes its token at once. Call it with your own session, not the impersonation token. Requires a sign-in within the last 10 minutes (401 `reauth_required` otherwise).
         */
        delete: operations["superAdminEndImpersonation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/super-admin/impersonation/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History of impersonations
         * @description Newest first. Filter by `actor`, `target` (both user ids) and `since`.
         */
        get: operations["superAdminListImpersonationLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/super-admin/feature-flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List feature flags */
        get: operations["superAdminListFeatureFlags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Turn feature flags on or off for everyone
         * @description Entries are matched by `key`; an unknown key is refused with `not_found` (flags are created by the code that reads them). Per-person overrides are unchanged. Requires a sign-in within the last 10 minutes (401 `reauth_required` otherwise) and `X-Audit-Reason`.
         */
        patch: operations["superAdminUpdateFeatureFlags"];
        trace?: never;
    };
    "/super-admin/users/{user_id}/flags": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Set a person's feature flag overrides
         * @description Replaces the person's full set of overrides; a flag left out follows the global setting again. Send `{"flags": {}}` to clear every override. Requires a sign-in within the last 10 minutes (401 `reauth_required` otherwise) and `X-Audit-Reason`.
         */
        put: operations["superAdminSetUserFlags"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/super-admin/site-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get site-wide settings */
        get: operations["superAdminGetSiteSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change site-wide settings
         * @description Send only the keys to change; each value replaces the stored one whole, and `null` restores the default. An unknown key is refused with `validation_failed`. Payment processor settings live in Finance and are refused here. Requires a sign-in within the last 10 minutes (401 `reauth_required` otherwise).
         */
        patch: operations["superAdminUpdateSiteSettings"];
        trace?: never;
    };
    "/super-admin/watermark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the media watermark */
        get: operations["superAdminGetWatermark"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change the media watermark
         * @description Applies to images and audio generated after the change; existing media keep their watermark. Requires a sign-in within the last 10 minutes (401 `reauth_required` otherwise).
         */
        patch: operations["superAdminUpdateWatermark"];
        trace?: never;
    };
    "/super-admin/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every partner API key
         * @description Platform wide: prefix, owner, club, scopes, created, last used and revoked. The key hash is never returned. Filter by `club_id`, `owner` and `revoked`. Sortable by `created_at` (default, newest first) and `last_used_at`.
         */
        get: operations["superAdminListKeys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/super-admin/keys/{key_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: components["parameters"]["KeyId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke any partner key
         * @description The abuse response, as today: the key stops working at once (callers get 401 `key_revoked`) and the owner is notified. Revoking a key that is already revoked is not an error. Requires a sign-in within the last 10 minutes (401 `reauth_required` otherwise) and `X-Audit-Reason`.
         */
        post: operations["superAdminRevokeKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/super-admin/rate-limits/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: components["parameters"]["KeyId"];
            };
            cookie?: never;
        };
        /**
         * A key's rate limits and its last hour of traffic
         * @description The limits in force, plus per-minute read and write counts for the last hour.
         */
        get: operations["superAdminGetKeyRateLimits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change a key's rate limits
         * @description Send only the fields to change, or `reset_to_default: true` alone to go back to the plan's limits. Takes effect within a minute. Requires a sign-in within the last 10 minutes (401 `reauth_required` otherwise) and `X-Audit-Reason`.
         */
        patch: operations["superAdminUpdateKeyRateLimits"];
        trace?: never;
    };
    "/super-admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The audit log of every staff write
         * @description Every staff write across Admin, Content, Ops, Finance and Super admin, newest first, with the before and after state, the reason and the request id. Filter by `actor`, `target` (any prefixed id), `surface` and `since`.
         */
        get: operations["superAdminListAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/super-admin/docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the design documents
         * @description Product and technical design documents (PRDs and TDDs) that are published to super admins. Only documents on the gateway's allowlist appear; the text ships inside the gateway image, never in the website's code, so nobody else can read it by opening the site's files.
         */
        get: operations["superAdminListDocs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/super-admin/docs/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: components["schemas"]["DesignDocId"];
            };
            cookie?: never;
        };
        /**
         * Read one design document
         * @description The document's Markdown, as committed at the version the gateway was built from. Mermaid blocks are returned as text; the screen draws them.
         */
        get: operations["superAdminGetDoc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example imp_5Hq1Zc8Wn3Ld */
        ImpersonationId: string;
        /** @enum {string} */
        RoleName: "super_admin" | "admin" | "moderator" | "editor" | "user" | "premium_user" | "support" | "director_library_operations" | "internal" | "tester" | "ml_engineer" | "finance_incharge" | "ops_admin" | "content_manager" | "customer_service_manager";
        /** @example manage_ai_processing */
        PermissionKey: string;
        /** @example blog_studio */
        FlagKey: string;
        /** @enum {string} */
        Surface: "admin" | "content" | "ops" | "finance" | "super-admin";
        Stamp: {
            audit: components["schemas"]["AuditStamp"];
        };
        /**
         * @example {
         *       "name": "ops_admin",
         *       "description": "Runs the processing queue, schedules, caps and model routing.",
         *       "permissions": [
         *         "manage_ai_processing",
         *         "manage_model_routing",
         *         "view_processing_metrics"
         *       ],
         *       "active": true,
         *       "holders": 3
         *     }
         */
        Role: {
            name: components["schemas"]["RoleName"];
            description: string | null;
            permissions: components["schemas"]["PermissionKey"][];
            active: boolean;
            /** @description How many people hold the role. */
            holders: number;
        };
        /**
         * @example {
         *       "key": "ai_billing_admin",
         *       "resource": "ai_billing",
         *       "action": "admin",
         *       "description": "Change prices, plans and processors; refund; adjust credits.",
         *       "roles": [
         *         "finance_incharge",
         *         "super_admin"
         *       ]
         *     }
         */
        Permission: {
            key: components["schemas"]["PermissionKey"];
            resource: string;
            action: string;
            description?: string | null;
            roles: components["schemas"]["RoleName"][];
        };
        UserRolesPut: {
            /** @description The person's complete set of roles. Omitting a role they hold removes it. */
            roles: components["schemas"]["RoleName"][];
        };
        /**
         * @example {
         *       "user": {
         *         "id": "user_2Ra9Kx4Wm7Qe",
         *         "username": "hamza_ops",
         *         "display_name": "Hamza Qureshi",
         *         "avatar_url": null
         *       },
         *       "before": [
         *         "ops_admin"
         *       ],
         *       "after": [
         *         "ops_admin",
         *         "ml_engineer"
         *       ],
         *       "added": [
         *         "ml_engineer"
         *       ],
         *       "removed": [],
         *       "audit": {
         *         "audit_id": "audit_7Kw3Pn9Zq2Lc",
         *         "at": "2026-09-22T10:20:00Z",
         *         "actor": {
         *           "id": "user_4Fq9ZtW1Lm8K",
         *           "username": "bilgrami",
         *           "display_name": "Bilal Bilgrami",
         *           "avatar_url": null
         *         }
         *       }
         *     }
         */
        UserRolesChange: {
            user: components["schemas"]["UserSummary"];
            before: components["schemas"]["RoleName"][];
            after: components["schemas"]["RoleName"][];
            added: components["schemas"]["RoleName"][];
            removed: components["schemas"]["RoleName"][];
            audit: components["schemas"]["AuditStamp"];
        };
        /**
         * @example {
         *       "at": "2026-09-22T10:20:00Z",
         *       "user": {
         *         "id": "user_2Ra9Kx4Wm7Qe",
         *         "username": "hamza_ops",
         *         "display_name": "Hamza Qureshi",
         *         "avatar_url": null
         *       },
         *       "action": "granted",
         *       "role": "ml_engineer",
         *       "by": {
         *         "id": "user_4Fq9ZtW1Lm8K",
         *         "username": "bilgrami",
         *         "display_name": "Bilal Bilgrami",
         *         "avatar_url": null
         *       },
         *       "reason": "Owns model evaluation from October.",
         *       "audit_id": "audit_7Kw3Pn9Zq2Lc"
         *     }
         */
        RoleLogEntry: {
            at: components["schemas"]["Timestamp"];
            user: components["schemas"]["UserSummary"];
            /** @enum {string} */
            action: "granted" | "removed";
            role: components["schemas"]["RoleName"];
            by: components["schemas"]["UserSummary"];
            reason?: string | null;
            audit_id?: components["schemas"]["AuditId"] | null;
        };
        ImpersonationStart: {
            user_id: components["schemas"]["UserId"];
            /** @default 15 */
            minutes: number;
        };
        /**
         * @example {
         *       "id": "imp_5Hq1Zc8Wn3Ld",
         *       "target": {
         *         "id": "user_7Tb3Yr2Qc9Pd",
         *         "username": "sana_reads",
         *         "display_name": "Sana Malik",
         *         "avatar_url": null
         *       },
         *       "session_token": "eyJhbGciOiJIUzI1NiJ9.eyJpbXAiOnRydWV9.c2lnbmF0dXJl",
         *       "expires_at": "2026-09-22T10:45:00Z",
         *       "audit": {
         *         "audit_id": "audit_1Mv6Qz3Rk8Wp",
         *         "at": "2026-09-22T10:30:00Z",
         *         "actor": {
         *           "id": "user_4Fq9ZtW1Lm8K",
         *           "username": "bilgrami",
         *           "display_name": "Bilal Bilgrami",
         *           "avatar_url": null
         *         }
         *       }
         *     }
         */
        ImpersonationSession: {
            id: components["schemas"]["ImpersonationId"];
            target: components["schemas"]["UserSummary"];
            /** @description Send as `Authorization Bearer` on api.ilm.red calls. Never stored by the server in readable form. */
            session_token: string;
            expires_at: components["schemas"]["Timestamp"];
            audit: components["schemas"]["AuditStamp"];
        };
        ImpersonationEnded: {
            id: components["schemas"]["ImpersonationId"];
            target: components["schemas"]["UserSummary"];
            ended_at: components["schemas"]["Timestamp"];
            audit: components["schemas"]["AuditStamp"];
        };
        /**
         * @example {
         *       "id": "imp_5Hq1Zc8Wn3Ld",
         *       "actor": {
         *         "id": "user_4Fq9ZtW1Lm8K",
         *         "username": "bilgrami",
         *         "display_name": "Bilal Bilgrami",
         *         "avatar_url": null
         *       },
         *       "target": {
         *         "id": "user_7Tb3Yr2Qc9Pd",
         *         "username": "sana_reads",
         *         "display_name": "Sana Malik",
         *         "avatar_url": null
         *       },
         *       "reason": "Reproduce the reader crash reported in rpt_2Lk8Qw1Zn5Tb.",
         *       "started_at": "2026-09-22T10:30:00Z",
         *       "expires_at": "2026-09-22T10:45:00Z",
         *       "ended_at": "2026-09-22T10:38:12Z",
         *       "ended_by": "actor",
         *       "requests": 41
         *     }
         */
        ImpersonationLogEntry: {
            id: components["schemas"]["ImpersonationId"];
            actor: components["schemas"]["UserSummary"];
            target: components["schemas"]["UserSummary"];
            reason: string;
            started_at: components["schemas"]["Timestamp"];
            expires_at: components["schemas"]["Timestamp"];
            /** Format: date-time */
            ended_at?: string | null;
            /** @enum {string} */
            ended_by?: "actor" | "expiry" | "replaced" | "revoked";
            /** @description Calls made with the impersonation token. */
            requests?: number;
        };
        /**
         * @example {
         *       "key": "blog_studio",
         *       "description": "The blog writing studio for authors.",
         *       "enabled": false,
         *       "overrides": {
         *         "on": 14,
         *         "off": 0
         *       },
         *       "updated_at": "2026-09-15T08:00:00Z"
         *     }
         */
        FeatureFlag: {
            key: components["schemas"]["FlagKey"];
            description?: string | null;
            enabled: boolean;
            /** @description How many people have a per-person override. */
            overrides: {
                on: number;
                off: number;
            };
            /** Format: date-time */
            updated_at: string | null;
        };
        FeatureFlagsPatch: {
            flags: {
                key: components["schemas"]["FlagKey"];
                enabled?: boolean;
                description?: string;
            }[];
        };
        FeatureFlagsChange: components["schemas"]["Stamp"] & {
            data: components["schemas"]["FeatureFlag"][];
        };
        UserFlagsPut: {
            /** @description Flag key to on (`true`) or off (`false`) for this person. Keys must be existing flag keys. */
            flags: {
                [key: string]: boolean;
            };
        };
        /**
         * @example {
         *       "user": {
         *         "id": "user_7Tb3Yr2Qc9Pd",
         *         "username": "sana_reads",
         *         "display_name": "Sana Malik",
         *         "avatar_url": null
         *       },
         *       "before": {},
         *       "after": {
         *         "blog_studio": true
         *       },
         *       "audit": {
         *         "audit_id": "audit_3Pw7Lc2Xn9Rv",
         *         "at": "2026-09-22T10:40:00Z",
         *         "actor": {
         *           "id": "user_4Fq9ZtW1Lm8K",
         *           "username": "bilgrami",
         *           "display_name": "Bilal Bilgrami",
         *           "avatar_url": null
         *         }
         *       }
         *     }
         */
        UserFlagsChange: {
            user: components["schemas"]["UserSummary"];
            before: {
                [key: string]: boolean;
            };
            after: {
                [key: string]: boolean;
            };
            audit: components["schemas"]["AuditStamp"];
        };
        /** @description A setting's value. Its shape depends on the key. */
        SettingValue: string | number | boolean | Record<string, never> | unknown[] | null;
        /**
         * @example {
         *       "settings": {
         *         "maintenance_banner": null,
         *         "signups_open": true,
         *         "default_interface_lang": "ur",
         *         "max_upload_mb": 200
         *       },
         *       "updated_at": "2026-09-10T12:00:00Z",
         *       "updated_by": {
         *         "id": "user_4Fq9ZtW1Lm8K",
         *         "username": "bilgrami",
         *         "display_name": "Bilal Bilgrami",
         *         "avatar_url": null
         *       }
         *     }
         */
        SiteSettings: {
            /** @description Setting key to value. */
            settings: {
                [key: string]: components["schemas"]["SettingValue"];
            };
            updated_at: components["schemas"]["Timestamp"];
            updated_by?: components["schemas"]["UserSummary"] | null;
        };
        SiteSettingsPatch: {
            /** @description Setting key to its new value; `null` restores the default. */
            settings: {
                [key: string]: components["schemas"]["SettingValue"];
            };
        };
        SiteSettingsChange: components["schemas"]["Stamp"] & components["schemas"]["SiteSettings"];
        /**
         * @example {
         *       "text": "ilm.red",
         *       "opacity": 0.18,
         *       "updated_at": "2026-07-01T00:00:00Z"
         *     }
         */
        Watermark: {
            text: string;
            opacity: number;
            updated_at: components["schemas"]["Timestamp"];
        };
        WatermarkPatch: {
            /** @description An empty string turns the watermark off. */
            text?: string;
            opacity?: number;
        };
        WatermarkChange: components["schemas"]["Stamp"] & components["schemas"]["Watermark"];
        /**
         * @example {
         *       "id": "key_9Bn4Tw2Qx7Mc",
         *       "name": "Reading circle bot",
         *       "prefix": "ilm_sk_live_7fQ2",
         *       "owner": {
         *         "id": "user_7Tb3Yr2Qc9Pd",
         *         "username": "sana_reads",
         *         "display_name": "Sana Malik",
         *         "avatar_url": null
         *       },
         *       "club": {
         *         "id": "club_7Kd0Wq2Rf1Ab",
         *         "name": "Urdu Classics Circle"
         *       },
         *       "scopes": [
         *         "library:read"
         *       ],
         *       "created_at": "2026-06-02T09:00:00Z",
         *       "expires_at": null,
         *       "last_used_at": "2026-09-22T09:59:58Z",
         *       "revoked_at": null,
         *       "revoked_by": null
         *     }
         */
        ApiKey: {
            id: components["schemas"]["KeyId"];
            name: string;
            /** @description The first characters of the key, enough to recognise it. The rest is never stored readably. */
            prefix: string;
            owner: components["schemas"]["UserSummary"];
            club?: {
                id: components["schemas"]["ClubId"];
                name: string;
            } | null;
            scopes: string[];
            created_at: components["schemas"]["Timestamp"];
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: date-time */
            last_used_at?: string | null;
            /** Format: date-time */
            revoked_at?: string | null;
            revoked_by?: components["schemas"]["UserSummary"] | null;
        };
        ApiKeyChange: components["schemas"]["Stamp"] & {
            key: components["schemas"]["ApiKey"];
        };
        RateLimitSettings: {
            reads_per_minute: number;
            writes_per_minute: number;
            burst: number;
        };
        /**
         * @example {
         *       "key_id": "key_9Bn4Tw2Qx7Mc",
         *       "limits": {
         *         "reads_per_minute": 600,
         *         "writes_per_minute": 60,
         *         "burst": 30
         *       },
         *       "is_default": true,
         *       "last_hour": [
         *         {
         *           "bucket": "reads",
         *           "window_start": "2026-09-22T09:59:00Z",
         *           "count": 212,
         *           "limited": 0
         *         }
         *       ]
         *     }
         */
        KeyRateLimits: {
            key_id: components["schemas"]["KeyId"];
            limits: components["schemas"]["RateLimitSettings"];
            /** @description True when the key uses the default limits. */
            is_default: boolean;
            /** @description One row per bucket per minute with traffic, oldest first. */
            last_hour: {
                /** @enum {string} */
                bucket: "reads" | "writes";
                window_start: components["schemas"]["Timestamp"];
                count: number;
                /** @description Requests refused with `rate_limited` in the window. */
                limited?: number;
            }[];
        };
        KeyRateLimitsPatch: {
            reads_per_minute?: number;
            writes_per_minute?: number;
            burst?: number;
        } | {
            /** @constant */
            reset_to_default: true;
        };
        KeyRateLimitsChange: components["schemas"]["Stamp"] & components["schemas"]["KeyRateLimits"];
        /**
         * @example {
         *       "id": "audit_7Kw3Pn9Zq2Lc",
         *       "at": "2026-09-22T10:20:00Z",
         *       "actor": {
         *         "id": "user_4Fq9ZtW1Lm8K",
         *         "username": "bilgrami",
         *         "display_name": "Bilal Bilgrami",
         *         "avatar_url": null
         *       },
         *       "impersonating": null,
         *       "surface": "super-admin",
         *       "action": "superAdminSetUserRoles",
         *       "target": {
         *         "type": "user",
         *         "id": "user_2Ra9Kx4Wm7Qe"
         *       },
         *       "reason": "Owns model evaluation from October.",
         *       "before": {
         *         "roles": [
         *           "ops_admin"
         *         ]
         *       },
         *       "after": {
         *         "roles": [
         *           "ops_admin",
         *           "ml_engineer"
         *         ]
         *       },
         *       "request_id": "req_4Nq8Zw1Kt6Pb"
         *     }
         */
        AuditEntry: {
            id: components["schemas"]["AuditId"];
            at: components["schemas"]["Timestamp"];
            actor: components["schemas"]["UserSummary"];
            impersonating?: components["schemas"]["UserSummary"] | null;
            surface: components["schemas"]["Surface"];
            /** @description The operationId of the write. */
            action: string;
            target: {
                type: string;
                /** @description The prefixed id of what changed. */
                id: string;
            };
            reason?: string | null;
            before?: Record<string, never> | null;
            after?: Record<string, never> | null;
            request_id: string;
        };
        /**
         * @description A stable name for the document, for example `book-reader-prd`.
         * @example book-reader-prd
         */
        DesignDocId: string;
        DesignDocSummary: {
            id: components["schemas"]["DesignDocId"];
            title: string;
            /** @description For grouping, for example `Reader` or `API`. */
            area: string;
            /** @enum {string} */
            kind: "prd" | "tdd" | "reference" | "plan";
            updated_at: components["schemas"]["Timestamp"];
        };
        DesignDoc: components["schemas"]["DesignDocSummary"] & {
            markdown: string;
            /** @description The release the gateway was built from, for example `1.402.0`. */
            version: string;
        };
        /** @description RFC 9457 problem document. Branch on `slug` (also the last segment of `type`), show `title`, quote `request_id`. */
        Problem: {
            /**
             * Format: uri
             * @example https://api.ilm.red/problems/not_found
             */
            type: string;
            slug: components["schemas"]["ProblemSlug"];
            title: string;
            status: number;
            detail?: string;
            request_id: string;
        };
        /** @example user_4Fq9ZtW1Lm8K */
        UserId: string;
        /** @description Every list returns this envelope. `next_cursor` is null on the last page. Lists that can count cheaply also return `total` when asked (each list says so); `total_capped` is true when the count stopped at the list's cap. */
        Page: {
            data: unknown[];
            next_cursor: string | null;
            total?: number;
            total_capped?: boolean;
        };
        /** @example club_7Kd0Wq2Rf1Ab */
        ClubId: string;
        KeyId: string;
        /**
         * @description The stable part of a problem. Branch on this, never on `title` or `detail`.
         * @enum {string}
         */
        ProblemSlug: "unauthorized" | "key_invalid" | "key_revoked" | "key_expired" | "scope_missing" | "not_club_admin" | "club_quota_reached" | "internal_only" | "not_found" | "term_not_found" | "slug_exists" | "edge_would_cycle" | "drop_not_ready" | "needs_text" | "needs_pages" | "needs_translation" | "paper_locked" | "term_has_edges" | "paper_not_in_club" | "revision_required" | "plan_refused" | "duplicate_brief" | "review_forbidden" | "already_reviewed" | "club_required" | "brief_invalid" | "cost_cap_exceeded" | "repair_invalid" | "idempotency_conflict" | "validation_failed" | "unsupported_kind" | "rate_limited" | "extract_rate_limited" | "agreement_required" | "agreement_version_stale" | "over_ceiling" | "top_up_limit" | "method_unavailable" | "self_confirm_forbidden" | "internal_error" | "forbidden" | "premium_required" | "insufficient_credits" | "reauth_required" | "version_conflict" | "conflict" | "gone" | "payload_too_large" | "unsupported_media_type" | "quote_expired" | "agent_cap_reached" | "lock_held";
        ValidationProblem: components["schemas"]["Problem"] & {
            errors: components["schemas"]["FieldError"][];
        };
        AuditId: string;
        /**
         * Format: date-time
         * @example 2026-09-22T18:04:05Z
         */
        Timestamp: string;
        /** @description How a person appears anywhere they are named. Never an email. */
        UserSummary: {
            id: components["schemas"]["UserId"];
            /** @description Null for a member who has not picked a username yet. */
            username: components["schemas"]["Username"] | null;
            display_name: string;
            /** Format: uri */
            avatar_url?: string | null;
        };
        /** @description Returned by every staff write, so the caller can quote the audit entry. */
        AuditStamp: {
            audit_id: components["schemas"]["AuditId"];
            at: components["schemas"]["Timestamp"];
            actor: components["schemas"]["UserSummary"];
        };
        /** @example bilgrami */
        Username: string;
        FieldError: {
            /**
             * @description Where the problem is, as a JSON Pointer into the request, prefixed with its part.
             * @example /body/title
             * @example /query/limit
             * @example /path/book_id
             * @example /header/Idempotency-Key
             */
            path: string;
            /**
             * @description Which rule failed.
             * @enum {string}
             */
            code: "required" | "type" | "enum" | "const" | "pattern" | "format" | "min_length" | "max_length" | "minimum" | "maximum" | "multiple_of" | "min_items" | "max_items" | "unique_items" | "unknown_field" | "one_of";
            /** @example must be at most 200 characters */
            message: string;
            /** @description The limit that was broken, when the rule has one (a length, a bound, the allowed values). */
            limit?: unknown;
        };
    };
    responses: {
        /** @description No credential, or a credential that is not valid (`unauthorized`, `key_invalid`, `key_revoked`, `key_expired`, `reauth_required`). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The caller is known but may not do this (`forbidden`, `scope_missing`, `premium_required`, `internal_only`). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No such resource, or one the caller may not see (`not_found`). The two are deliberately indistinguishable. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description `If-Match` did not match the current version (`version_conflict`). Read again and retry. */
        VersionConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The request failed validation (`validation_failed`). `errors` lists every failing field, not just the first. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ValidationProblem"];
            };
        };
    };
    parameters: {
        KeyId: components["schemas"]["KeyId"];
        UserId: components["schemas"]["UserId"];
        /** @description Why this change is being made. Stored in the audit log with the actor and the target. */
        AuditReason: string;
        /** @description The `ETag` from your last read. A stale value is refused with `version_conflict` (412). */
        IfMatch: string;
        Since: string;
        /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
        Cursor: string;
        /** @description Page size. */
        Limit: number;
        /** @description Required on this call because it creates something or spends credits. See IdempotencyKey. */
        IdempotencyKeyRequired: string;
        /** @description A field name, prefixed with `-` for descending. Each list documents the fields it allows. */
        Sort: string;
        /** @description Replay protection for 24 hours. The same key with the same body replays the first response; the same key with a different body is refused with `idempotency_conflict`. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: {
        /** @description Version of the resource, for caching and for `If-Match` on the next write. */
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    superAdminListRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every role. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Role"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    superAdminListPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every permission. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Permission"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    superAdminSetUserRoles: {
        parameters: {
            query?: never;
            header: {
                /** @description Why this change is being made. Stored in the audit log with the actor and the target. */
                "X-Audit-Reason": components["parameters"]["AuditReason"];
                /** @description The `ETag` from your last read. A stale value is refused with `version_conflict` (412). */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRolesPut"];
            };
        };
        responses: {
            /** @description The roles before and after. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRolesChange"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The change would remove the last super admin, or your own super admin role (`conflict`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            412: components["responses"]["VersionConflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    superAdminListRoleLog: {
        parameters: {
            query?: {
                user_id?: components["schemas"]["UserId"];
                since?: components["parameters"]["Since"];
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of role changes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["RoleLogEntry"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    superAdminStartImpersonation: {
        parameters: {
            query?: never;
            header: {
                /** @description Why this change is being made. Stored in the audit log with the actor and the target. */
                "X-Audit-Reason": components["parameters"]["AuditReason"];
                /** @description Required on this call because it creates something or spends credits. See IdempotencyKey. */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImpersonationStart"];
            };
        };
        responses: {
            /** @description The impersonation session. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImpersonationSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    superAdminEndImpersonation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The ended impersonation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImpersonationEnded"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    superAdminListImpersonationLog: {
        parameters: {
            query?: {
                actor?: components["schemas"]["UserId"];
                target?: components["schemas"]["UserId"];
                since?: components["parameters"]["Since"];
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of impersonations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["ImpersonationLogEntry"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    superAdminListFeatureFlags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every flag. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FeatureFlag"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    superAdminUpdateFeatureFlags: {
        parameters: {
            query?: never;
            header: {
                /** @description Why this change is being made. Stored in the audit log with the actor and the target. */
                "X-Audit-Reason": components["parameters"]["AuditReason"];
                /** @description The `ETag` from your last read. A stale value is refused with `version_conflict` (412). */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeatureFlagsPatch"];
            };
        };
        responses: {
            /** @description Every flag, after the change. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureFlagsChange"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["VersionConflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    superAdminSetUserFlags: {
        parameters: {
            query?: never;
            header: {
                /** @description Why this change is being made. Stored in the audit log with the actor and the target. */
                "X-Audit-Reason": components["parameters"]["AuditReason"];
                /** @description The `ETag` from your last read. A stale value is refused with `version_conflict` (412). */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserFlagsPut"];
            };
        };
        responses: {
            /** @description The overrides before and after. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserFlagsChange"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            412: components["responses"]["VersionConflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    superAdminGetSiteSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every setting. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteSettings"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    superAdminUpdateSiteSettings: {
        parameters: {
            query?: never;
            header?: {
                /** @description The `ETag` from your last read. A stale value is refused with `version_conflict` (412). */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteSettingsPatch"];
            };
        };
        responses: {
            /** @description Every setting, after the change. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteSettingsChange"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            412: components["responses"]["VersionConflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    superAdminGetWatermark: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The watermark. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Watermark"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    superAdminUpdateWatermark: {
        parameters: {
            query?: never;
            header?: {
                /** @description The `ETag` from your last read. A stale value is refused with `version_conflict` (412). */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatermarkPatch"];
            };
        };
        responses: {
            /** @description The updated watermark. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatermarkChange"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            412: components["responses"]["VersionConflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    superAdminListKeys: {
        parameters: {
            query?: {
                club_id?: components["schemas"]["ClubId"];
                owner?: components["schemas"]["UserId"];
                revoked?: boolean;
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
                /** @description A field name, prefixed with `-` for descending. Each list documents the fields it allows. */
                sort?: components["parameters"]["Sort"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of keys. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["ApiKey"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    superAdminRevokeKey: {
        parameters: {
            query?: never;
            header: {
                /** @description Why this change is being made. Stored in the audit log with the actor and the target. */
                "X-Audit-Reason": components["parameters"]["AuditReason"];
                /** @description Replay protection for 24 hours. The same key with the same body replays the first response; the same key with a different body is refused with `idempotency_conflict`. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                key_id: components["parameters"]["KeyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The revoked key. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyChange"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    superAdminGetKeyRateLimits: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: components["parameters"]["KeyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The limits and recent traffic. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyRateLimits"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    superAdminUpdateKeyRateLimits: {
        parameters: {
            query?: never;
            header: {
                /** @description Why this change is being made. Stored in the audit log with the actor and the target. */
                "X-Audit-Reason": components["parameters"]["AuditReason"];
                /** @description The `ETag` from your last read. A stale value is refused with `version_conflict` (412). */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                key_id: components["parameters"]["KeyId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeyRateLimitsPatch"];
            };
        };
        responses: {
            /** @description The limits after the change. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyRateLimitsChange"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The key is revoked (`conflict`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            412: components["responses"]["VersionConflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    superAdminListAudit: {
        parameters: {
            query?: {
                actor?: components["schemas"]["UserId"];
                /** @description Any prefixed id, such as `book_…`, `user_…` or `key_…`. */
                target?: string;
                surface?: components["schemas"]["Surface"];
                since?: components["parameters"]["Since"];
                /** @description Opaque cursor from the previous page's `next_cursor`. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Page size. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of audit entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"] & {
                        data?: components["schemas"]["AuditEntry"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    superAdminListDocs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The documents, grouped by area. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DesignDocSummary"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    superAdminGetDoc: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string;
            };
            path: {
                doc_id: components["schemas"]["DesignDocId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The document. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesignDoc"];
                };
            };
            /** @description Unchanged since the `ETag` sent. No body. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
