// COPIED from ilm-red-unbound/packages/api-client by scripts/sync-api-client.mjs. Do not edit here.
// GENERATED by scripts/build-api-client.mjs from api/openapi/*.json. Do not edit by hand;
// change the contract in openapi/ and run `npm run api:spec`.

/** Which host serves a surface: the public plane or the staff plane. */
export const SURFACE_HOST = {
  "admin": "staff",
  "ai": "public",
  "blog": "public",
  "books": "public",
  "clubs": "public",
  "content": "staff",
  "finance": "staff",
  "me": "public",
  "ops": "staff",
  "premium": "public",
  "super-admin": "staff"
} as const;

/** operationId → [HTTP method, path template] for every surface. */
export const OPERATIONS = {
  "admin": {
    "adminListBooks": [
      "GET",
      "/admin/books"
    ],
    "adminGetBook": [
      "GET",
      "/admin/books/{book_id}"
    ],
    "adminUpdateBook": [
      "PATCH",
      "/admin/books/{book_id}"
    ],
    "adminListBookAudit": [
      "GET",
      "/admin/books/{book_id}/audit"
    ],
    "adminRevertBookChange": [
      "POST",
      "/admin/books/{book_id}/audit/{entry_id}/revert"
    ],
    "adminListReports": [
      "GET",
      "/admin/reports"
    ],
    "adminGetReport": [
      "GET",
      "/admin/reports/{report_id}"
    ],
    "adminResolveReport": [
      "POST",
      "/admin/reports/{report_id}/resolve"
    ],
    "adminListIssues": [
      "GET",
      "/admin/issues"
    ],
    "adminGetIssue": [
      "GET",
      "/admin/issues/{issue_id}"
    ],
    "adminUpdateIssue": [
      "PATCH",
      "/admin/issues/{issue_id}"
    ],
    "adminReplyToIssue": [
      "POST",
      "/admin/issues/{issue_id}/responses"
    ],
    "adminListPronunciationFlags": [
      "GET",
      "/admin/pronunciation-flags"
    ],
    "adminResolvePronunciationFlag": [
      "POST",
      "/admin/pronunciation-flags/{flag_id}/resolve"
    ],
    "adminListCopyrightNotices": [
      "GET",
      "/admin/copyright-notices"
    ],
    "adminGetCopyrightNotice": [
      "GET",
      "/admin/copyright-notices/{notice_id}"
    ],
    "adminDecideCopyrightNotice": [
      "POST",
      "/admin/copyright-notices/{notice_id}/decide"
    ],
    "adminListSuggestions": [
      "GET",
      "/admin/suggestions"
    ],
    "adminUpdateSuggestion": [
      "PATCH",
      "/admin/suggestions/{suggestion_id}"
    ],
    "adminListClubs": [
      "GET",
      "/admin/clubs"
    ],
    "adminUpdateClub": [
      "PATCH",
      "/admin/clubs/{club_id}"
    ],
    "adminListAddonReviews": [
      "GET",
      "/admin/addons/review"
    ],
    "adminDecideAddon": [
      "POST",
      "/admin/addons/{addon_id}/decide"
    ],
    "adminListUsers": [
      "GET",
      "/admin/users"
    ],
    "adminGetUser": [
      "GET",
      "/admin/users/{user_id}"
    ],
    "adminListInbox": [
      "GET",
      "/admin/inbox"
    ],
    "adminGetInboxMessage": [
      "GET",
      "/admin/inbox/{message_id}"
    ],
    "adminUpdateInboxMessage": [
      "PATCH",
      "/admin/inbox/{message_id}"
    ],
    "adminReplyToInboxMessage": [
      "POST",
      "/admin/inbox/{message_id}/reply"
    ]
  },
  "ai": {
    "listAiModels": [
      "GET",
      "/ai/models"
    ],
    "listAiSessions": [
      "GET",
      "/ai/sessions"
    ],
    "createAiSession": [
      "POST",
      "/ai/sessions"
    ],
    "getAiSession": [
      "GET",
      "/ai/sessions/{session_id}"
    ],
    "askAiQuestion": [
      "POST",
      "/ai/sessions/{session_id}/messages"
    ],
    "rateAiMessage": [
      "POST",
      "/ai/sessions/{session_id}/messages/{message_id}/rating"
    ],
    "publishAiMessage": [
      "POST",
      "/ai/sessions/{session_id}/messages/{message_id}/publish"
    ],
    "createAiSummary": [
      "POST",
      "/ai/summaries"
    ],
    "explainTerm": [
      "GET",
      "/ai/terms/{slug}/explain"
    ],
    "createAiTranslation": [
      "POST",
      "/ai/translations"
    ],
    "createAiCouncilReview": [
      "POST",
      "/ai/council/reviews"
    ],
    "getAiRun": [
      "GET",
      "/ai/runs/{run_id}"
    ],
    "listAiAgentConnections": [
      "GET",
      "/ai/agents"
    ],
    "updateAiAgentConnection": [
      "PATCH",
      "/ai/agents/{agent_id}"
    ],
    "revokeAiAgentConnection": [
      "DELETE",
      "/ai/agents/{agent_id}"
    ],
    "registerAiAgentClient": [
      "POST",
      "/ai/oauth/register"
    ],
    "exchangeAiAgentToken": [
      "POST",
      "/ai/oauth/token"
    ],
    "revokeAiAgentToken": [
      "POST",
      "/ai/oauth/revoke"
    ],
    "getAiAgentAuthorizeInfo": [
      "GET",
      "/ai/oauth/authorize-info"
    ],
    "grantAiAgentConsent": [
      "POST",
      "/ai/oauth/consent"
    ]
  },
  "blog": {
    "listBlogFeed": [
      "GET",
      "/blog/feed"
    ],
    "getPublishedBlogPost": [
      "GET",
      "/blog/feed/{post_id}"
    ],
    "resolveBlogPost": [
      "GET",
      "/blog/feed/by-slug/{username}/{slug}"
    ],
    "getBlogAuthor": [
      "GET",
      "/blog/authors/{username}"
    ],
    "listBlogAuthorPosts": [
      "GET",
      "/blog/authors/{username}/posts"
    ],
    "listBlogCategories": [
      "GET",
      "/blog/categories"
    ],
    "listBlogTags": [
      "GET",
      "/blog/tags"
    ],
    "getBlogPostAudio": [
      "GET",
      "/blog/posts/{post_id}/audio"
    ],
    "listBlogComments": [
      "GET",
      "/blog/posts/{post_id}/comments"
    ],
    "createBlogComment": [
      "POST",
      "/blog/posts/{post_id}/comments"
    ],
    "updateBlogComment": [
      "PATCH",
      "/blog/posts/{post_id}/comments/{comment_id}"
    ],
    "deleteBlogComment": [
      "DELETE",
      "/blog/posts/{post_id}/comments/{comment_id}"
    ],
    "reportBlogComment": [
      "POST",
      "/blog/posts/{post_id}/comments/{comment_id}/report"
    ],
    "likeBlogPost": [
      "PUT",
      "/blog/posts/{post_id}/like"
    ],
    "unlikeBlogPost": [
      "DELETE",
      "/blog/posts/{post_id}/like"
    ],
    "likeBlogPoster": [
      "PUT",
      "/blog/posters/{poster_id}/like"
    ],
    "unlikeBlogPoster": [
      "DELETE",
      "/blog/posters/{poster_id}/like"
    ],
    "recordBlogPostView": [
      "POST",
      "/blog/posts/{post_id}/views"
    ],
    "createBlogReaderReport": [
      "POST",
      "/blog/posts/{post_id}/reports"
    ],
    "listBlogDrafts": [
      "GET",
      "/blog/drafts"
    ],
    "createBlogDraft": [
      "POST",
      "/blog/drafts"
    ],
    "getBlogDraft": [
      "GET",
      "/blog/drafts/{post_id}"
    ],
    "updateBlogDraft": [
      "PATCH",
      "/blog/drafts/{post_id}"
    ],
    "acquireBlogDraftLock": [
      "POST",
      "/blog/drafts/{post_id}/lock"
    ],
    "releaseBlogDraftLock": [
      "DELETE",
      "/blog/drafts/{post_id}/lock"
    ],
    "listBlogDraftRevisions": [
      "GET",
      "/blog/drafts/{post_id}/revisions"
    ],
    "restoreBlogDraftRevision": [
      "POST",
      "/blog/drafts/{post_id}/revisions/{revision_id}/restore"
    ]
  },
  "books": {
    "listBooks": [
      "GET",
      "/books"
    ],
    "createBook": [
      "POST",
      "/books"
    ],
    "listCategories": [
      "GET",
      "/categories"
    ],
    "getCategory": [
      "GET",
      "/categories/{slug}"
    ],
    "getBookBySlug": [
      "GET",
      "/books/by-slug/{category}/{slug}"
    ],
    "getBook": [
      "GET",
      "/books/{book_id}"
    ],
    "updateBook": [
      "PATCH",
      "/books/{book_id}"
    ],
    "deleteBook": [
      "DELETE",
      "/books/{book_id}"
    ],
    "completeBookUpload": [
      "POST",
      "/books/{book_id}/upload-complete"
    ],
    "getBookProcessing": [
      "GET",
      "/books/{book_id}/processing"
    ],
    "listBookPages": [
      "GET",
      "/books/{book_id}/pages"
    ],
    "getBookReadiness": [
      "GET",
      "/books/{book_id}/readiness"
    ],
    "getMedia": [
      "GET",
      "/media/{token}"
    ],
    "getBookPageText": [
      "GET",
      "/books/{book_id}/pages/{n}/text"
    ],
    "getBookText": [
      "GET",
      "/books/{book_id}/text"
    ],
    "listBookEditions": [
      "GET",
      "/books/{book_id}/editions"
    ],
    "listBookAudio": [
      "GET",
      "/books/{book_id}/audio"
    ],
    "listBookChapters": [
      "GET",
      "/books/{book_id}/chapters"
    ],
    "searchLibrary": [
      "GET",
      "/search"
    ],
    "searchBook": [
      "GET",
      "/books/{book_id}/search"
    ],
    "listBookRatings": [
      "GET",
      "/books/{book_id}/ratings"
    ],
    "rateBook": [
      "PUT",
      "/books/{book_id}/ratings/mine"
    ],
    "deleteMyBookRating": [
      "DELETE",
      "/books/{book_id}/ratings/mine"
    ],
    "listBookQuestions": [
      "GET",
      "/books/{book_id}/questions"
    ],
    "askBookQuestion": [
      "POST",
      "/books/{book_id}/questions"
    ],
    "voteOnBookQuestion": [
      "POST",
      "/books/{book_id}/questions/{question_id}/votes"
    ],
    "reportBook": [
      "POST",
      "/books/{book_id}/reports"
    ],
    "listSimilarBooks": [
      "GET",
      "/books/{book_id}/similar"
    ],
    "recordBookView": [
      "POST",
      "/books/{book_id}/views"
    ],
    "createBookDownload": [
      "POST",
      "/books/{book_id}/download"
    ],
    "streamBookEvents": [
      "GET",
      "/books/{book_id}/events"
    ],
    "listPageFlags": [
      "GET",
      "/books/{book_id}/pages/{n}/flags"
    ],
    "flagPageText": [
      "POST",
      "/books/{book_id}/pages/{n}/flags"
    ],
    "defineWord": [
      "GET",
      "/words/{word}/definition"
    ],
    "pronounceWord": [
      "GET",
      "/words/{word}/pronunciation"
    ]
  },
  "clubs": {
    "listDiscoverableClubs": [
      "GET",
      "/clubs/discover"
    ],
    "getClubBySlug": [
      "GET",
      "/clubs/by-slug/{slug}"
    ],
    "getClub": [
      "GET",
      "/clubs/{club_id}"
    ],
    "deleteClub": [
      "DELETE",
      "/clubs/{club_id}"
    ],
    "createClubCoverUpload": [
      "POST",
      "/clubs/{club_id}/cover"
    ],
    "joinClub": [
      "POST",
      "/clubs/{club_id}/join"
    ],
    "leaveClub": [
      "POST",
      "/clubs/{club_id}/leave"
    ],
    "listClubMembers": [
      "GET",
      "/clubs/{club_id}/members"
    ],
    "updateClubMember": [
      "PATCH",
      "/clubs/{club_id}/members/{user_id}"
    ],
    "removeClubMember": [
      "DELETE",
      "/clubs/{club_id}/members/{user_id}"
    ],
    "listClubInvites": [
      "GET",
      "/clubs/{club_id}/invites"
    ],
    "createClubInvites": [
      "POST",
      "/clubs/{club_id}/invites"
    ],
    "revokeClubInvite": [
      "DELETE",
      "/clubs/{club_id}/invites/{invite_id}"
    ],
    "listClubBooks": [
      "GET",
      "/clubs/{club_id}/books"
    ],
    "proposeClubBook": [
      "POST",
      "/clubs/{club_id}/books"
    ],
    "approveClubBook": [
      "POST",
      "/clubs/{club_id}/books/{book_id}/approve"
    ],
    "rejectClubBook": [
      "POST",
      "/clubs/{club_id}/books/{book_id}/reject"
    ],
    "setClubBookPolicy": [
      "PUT",
      "/clubs/{club_id}/book-policy"
    ],
    "listClubThreads": [
      "GET",
      "/clubs/{club_id}/threads"
    ],
    "createClubThread": [
      "POST",
      "/clubs/{club_id}/threads"
    ],
    "deleteClubThread": [
      "DELETE",
      "/clubs/{club_id}/threads/{thread_id}"
    ],
    "listClubThreadReplies": [
      "GET",
      "/clubs/{club_id}/threads/{thread_id}/replies"
    ],
    "createClubThreadReply": [
      "POST",
      "/clubs/{club_id}/threads/{thread_id}/replies"
    ],
    "deleteClubThreadReply": [
      "DELETE",
      "/clubs/{club_id}/threads/{thread_id}/replies/{reply_id}"
    ],
    "castClubVote": [
      "POST",
      "/clubs/{club_id}/votes"
    ],
    "getClubLeaderboard": [
      "GET",
      "/clubs/{club_id}/leaderboard"
    ],
    "listClubQuestions": [
      "GET",
      "/clubs/{club_id}/questions"
    ]
  },
  "content": {
    "contentListArticles": [
      "GET",
      "/content/help/articles"
    ],
    "contentCreateArticle": [
      "POST",
      "/content/help/articles"
    ],
    "contentGetArticle": [
      "GET",
      "/content/help/articles/{article_id}"
    ],
    "contentUpdateArticle": [
      "PATCH",
      "/content/help/articles/{article_id}"
    ],
    "contentDeleteArticle": [
      "DELETE",
      "/content/help/articles/{article_id}"
    ],
    "contentPublishArticle": [
      "POST",
      "/content/help/articles/{article_id}/publish"
    ],
    "contentCreateArticleScreenshot": [
      "POST",
      "/content/help/articles/{article_id}/screenshots"
    ],
    "contentListHelpCategories": [
      "GET",
      "/content/help/categories"
    ],
    "contentCreateHelpCategory": [
      "POST",
      "/content/help/categories"
    ],
    "contentReorderHelpCategories": [
      "PUT",
      "/content/help/categories/order"
    ],
    "contentGetHelpCategory": [
      "GET",
      "/content/help/categories/{slug}"
    ],
    "contentUpdateHelpCategory": [
      "PATCH",
      "/content/help/categories/{slug}"
    ],
    "contentDeleteHelpCategory": [
      "DELETE",
      "/content/help/categories/{slug}"
    ],
    "contentListAnnouncements": [
      "GET",
      "/content/announcements"
    ],
    "contentCreateAnnouncement": [
      "POST",
      "/content/announcements"
    ],
    "contentGetAnnouncement": [
      "GET",
      "/content/announcements/{announcement_id}"
    ],
    "contentUpdateAnnouncement": [
      "PATCH",
      "/content/announcements/{announcement_id}"
    ],
    "contentDeleteAnnouncement": [
      "DELETE",
      "/content/announcements/{announcement_id}"
    ],
    "contentScheduleAnnouncement": [
      "POST",
      "/content/announcements/{announcement_id}/schedule"
    ],
    "contentPublishAnnouncement": [
      "POST",
      "/content/announcements/{announcement_id}/publish"
    ],
    "contentListUiStrings": [
      "GET",
      "/content/ui-strings"
    ],
    "contentUpdateUiString": [
      "PATCH",
      "/content/ui-strings/{key}"
    ],
    "contentReviewUiStrings": [
      "POST",
      "/content/ui-strings/review"
    ],
    "contentTranslateUiStrings": [
      "POST",
      "/content/ui-strings/translate"
    ],
    "contentListBookRevisions": [
      "GET",
      "/content/books/{book_id}/revisions"
    ],
    "contentPublishTextCorrection": [
      "POST",
      "/content/books/{book_id}/corrections/publish"
    ],
    "contentListReadingPresets": [
      "GET",
      "/content/reading-presets"
    ],
    "contentCreateReadingPreset": [
      "POST",
      "/content/reading-presets"
    ],
    "contentGetReadingPreset": [
      "GET",
      "/content/reading-presets/{preset_id}"
    ],
    "contentUpdateReadingPreset": [
      "PATCH",
      "/content/reading-presets/{preset_id}"
    ],
    "contentDeleteReadingPreset": [
      "DELETE",
      "/content/reading-presets/{preset_id}"
    ],
    "contentListBackgrounds": [
      "GET",
      "/content/backgrounds"
    ],
    "contentCreateBackground": [
      "POST",
      "/content/backgrounds"
    ],
    "contentGetBackground": [
      "GET",
      "/content/backgrounds/{background_id}"
    ],
    "contentUpdateBackground": [
      "PATCH",
      "/content/backgrounds/{background_id}"
    ],
    "contentDeleteBackground": [
      "DELETE",
      "/content/backgrounds/{background_id}"
    ],
    "contentReplaceBackgroundImage": [
      "POST",
      "/content/backgrounds/{background_id}/image"
    ],
    "contentListTermVisualTemplates": [
      "GET",
      "/content/term-visuals/templates"
    ],
    "contentCreateTermVisualTemplate": [
      "POST",
      "/content/term-visuals/templates"
    ],
    "contentGetTermVisualTemplate": [
      "GET",
      "/content/term-visuals/templates/{template_id}"
    ],
    "contentUpdateTermVisualTemplate": [
      "PATCH",
      "/content/term-visuals/templates/{template_id}"
    ],
    "contentDeleteTermVisualTemplate": [
      "DELETE",
      "/content/term-visuals/templates/{template_id}"
    ],
    "contentListTermVisualPrompts": [
      "GET",
      "/content/term-visuals/prompts"
    ],
    "contentCreateTermVisualPrompt": [
      "POST",
      "/content/term-visuals/prompts"
    ],
    "contentGetTermVisualPrompt": [
      "GET",
      "/content/term-visuals/prompts/{style}"
    ],
    "contentUpdateTermVisualPrompt": [
      "PATCH",
      "/content/term-visuals/prompts/{style}"
    ],
    "contentDeleteTermVisualPrompt": [
      "DELETE",
      "/content/term-visuals/prompts/{style}"
    ],
    "contentListTermVisualPromptVersions": [
      "GET",
      "/content/term-visuals/prompts/{style}/versions"
    ],
    "contentListTermVisualGenerations": [
      "GET",
      "/content/term-visuals/generations"
    ],
    "contentListPrompts": [
      "GET",
      "/content/prompts"
    ],
    "contentGetPrompt": [
      "GET",
      "/content/prompts/{key}"
    ],
    "contentUpdatePrompt": [
      "PATCH",
      "/content/prompts/{key}"
    ],
    "contentListPromptVersions": [
      "GET",
      "/content/prompts/{key}/versions"
    ],
    "contentRestorePromptVersion": [
      "POST",
      "/content/prompts/{key}/versions/{version}/restore"
    ],
    "contentListCategories": [
      "GET",
      "/content/categories"
    ],
    "contentUpdateCategory": [
      "PATCH",
      "/content/categories/{slug}"
    ],
    "contentListDailyCards": [
      "GET",
      "/content/daily-cards"
    ],
    "contentCreateDailyCard": [
      "POST",
      "/content/daily-cards"
    ],
    "contentGetDailyCard": [
      "GET",
      "/content/daily-cards/{card_id}"
    ],
    "contentUpdateDailyCard": [
      "PATCH",
      "/content/daily-cards/{card_id}"
    ],
    "contentDeleteDailyCard": [
      "DELETE",
      "/content/daily-cards/{card_id}"
    ],
    "contentListQuotes": [
      "GET",
      "/content/quotes"
    ],
    "contentCreateQuote": [
      "POST",
      "/content/quotes"
    ],
    "contentGetQuote": [
      "GET",
      "/content/quotes/{quotation_id}"
    ],
    "contentUpdateQuote": [
      "PATCH",
      "/content/quotes/{quotation_id}"
    ],
    "contentDeleteQuote": [
      "DELETE",
      "/content/quotes/{quotation_id}"
    ]
  },
  "finance": {
    "financeGetKpis": [
      "GET",
      "/finance/kpis"
    ],
    "financeListPayments": [
      "GET",
      "/finance/payments"
    ],
    "financeGetPayment": [
      "GET",
      "/finance/payments/{payment_id}"
    ],
    "financeRefundPayment": [
      "POST",
      "/finance/payments/{payment_id}/refunds"
    ],
    "financeListRefundRequests": [
      "GET",
      "/finance/refund-requests"
    ],
    "financeDeclineRefundRequest": [
      "POST",
      "/finance/refund-requests/{request_id}/decline"
    ],
    "financeListPremiumRequests": [
      "GET",
      "/finance/premium-requests"
    ],
    "financeApprovePremiumRequest": [
      "POST",
      "/finance/premium-requests/{request_id}/approve"
    ],
    "financeRejectPremiumRequest": [
      "POST",
      "/finance/premium-requests/{request_id}/reject"
    ],
    "financeAdjustUserCredits": [
      "POST",
      "/finance/users/{user_id}/credits"
    ],
    "financeResetMonthlyCredits": [
      "POST",
      "/finance/credits/monthly-reset"
    ],
    "financeListCostRefunds": [
      "GET",
      "/finance/cost-refunds"
    ],
    "financeCreateCostRefund": [
      "POST",
      "/finance/cost-refunds"
    ],
    "financeGetUsage": [
      "GET",
      "/finance/usage"
    ],
    "financeGetReconciliation": [
      "GET",
      "/finance/reconciliation"
    ],
    "financeMarkMonthReconciled": [
      "POST",
      "/finance/reconciliation/{month}/mark-reconciled"
    ],
    "financeListRates": [
      "GET",
      "/finance/rates"
    ],
    "financeUpdateRates": [
      "PATCH",
      "/finance/rates"
    ],
    "financeGetBillingConfig": [
      "GET",
      "/finance/billing-config"
    ],
    "financeUpdateBillingConfig": [
      "PATCH",
      "/finance/billing-config"
    ],
    "financeListPlans": [
      "GET",
      "/finance/plans"
    ],
    "financeCreatePlan": [
      "POST",
      "/finance/plans"
    ],
    "financeUpdatePlan": [
      "PATCH",
      "/finance/plans/{plan_id}"
    ],
    "financeListProcessors": [
      "GET",
      "/finance/processors"
    ],
    "financeUpdateProcessor": [
      "PATCH",
      "/finance/processors/{provider}"
    ],
    "financeListInvoices": [
      "GET",
      "/finance/invoices"
    ],
    "financeExportMonth": [
      "GET",
      "/finance/exports/{month}"
    ],
    "financeListAudit": [
      "GET",
      "/finance/audit"
    ],
    "financeRecordManualPayment": [
      "POST",
      "/finance/manual-payments"
    ],
    "financeListCreditGrants": [
      "GET",
      "/finance/credit-grants"
    ],
    "financeDecideCreditGrant": [
      "POST",
      "/finance/credit-grants/{grant_id}/decision"
    ],
    "financeListAccounts": [
      "GET",
      "/finance/accounts"
    ],
    "financeGetAccountStatement": [
      "GET",
      "/finance/accounts/{user_id}/statement"
    ],
    "financeGetAccountChecks": [
      "GET",
      "/finance/accounts/{user_id}/checks"
    ],
    "financeSetAccountGapStatus": [
      "POST",
      "/finance/accounts/{user_id}/gap-status"
    ],
    "financeSetCreditLimit": [
      "PUT",
      "/finance/accounts/{user_id}/credit-limit"
    ],
    "financeListAgreementVersions": [
      "GET",
      "/finance/billing-agreement/versions"
    ],
    "financeCreateAgreementDraft": [
      "POST",
      "/finance/billing-agreement/versions"
    ],
    "financeUpdateAgreementDraft": [
      "PATCH",
      "/finance/billing-agreement/versions/{version}"
    ],
    "financePublishAgreementVersion": [
      "POST",
      "/finance/billing-agreement/versions/{version}/publish"
    ],
    "financeListAgreementAcceptances": [
      "GET",
      "/finance/billing-agreement/versions/{version}/acceptances"
    ],
    "financeListTopUps": [
      "GET",
      "/finance/top-ups"
    ],
    "financeGetTopUp": [
      "GET",
      "/finance/top-ups/{top_up_id}"
    ],
    "financeConfirmTopUp": [
      "POST",
      "/finance/top-ups/{top_up_id}/confirm"
    ],
    "financeRejectTopUp": [
      "POST",
      "/finance/top-ups/{top_up_id}/reject"
    ],
    "financeMatchBankLines": [
      "POST",
      "/finance/top-ups/matches"
    ],
    "financeListPaymentMethods": [
      "GET",
      "/finance/payment-methods"
    ],
    "financeUpdatePaymentMethod": [
      "PATCH",
      "/finance/payment-methods/{method}"
    ]
  },
  "me": {
    "getMe": [
      "GET",
      "/me"
    ],
    "updateMe": [
      "PATCH",
      "/me"
    ],
    "deleteMe": [
      "DELETE",
      "/me"
    ],
    "createMyAvatarUpload": [
      "POST",
      "/me/avatar"
    ],
    "requestMyDataExport": [
      "POST",
      "/me/export"
    ],
    "createMyDatabaseSession": [
      "POST",
      "/me/database-session"
    ],
    "getMyEntitlements": [
      "GET",
      "/me/entitlements"
    ],
    "getMyPreferences": [
      "GET",
      "/me/preferences"
    ],
    "updateMyPreferences": [
      "PATCH",
      "/me/preferences"
    ],
    "getMyShelfCounts": [
      "GET",
      "/me/shelf"
    ],
    "listMyShelf": [
      "GET",
      "/me/shelf/{shelf}"
    ],
    "addFavorite": [
      "PUT",
      "/me/favorites/{book_id}"
    ],
    "removeFavorite": [
      "DELETE",
      "/me/favorites/{book_id}"
    ],
    "listMyProgress": [
      "GET",
      "/me/progress"
    ],
    "getMyProgress": [
      "GET",
      "/me/progress/{book_id}"
    ],
    "saveMyProgress": [
      "PUT",
      "/me/progress/{book_id}"
    ],
    "listMyNotes": [
      "GET",
      "/me/notes"
    ],
    "createMyNote": [
      "POST",
      "/me/notes"
    ],
    "updateMyNote": [
      "PATCH",
      "/me/notes/{note_id}"
    ],
    "deleteMyNote": [
      "DELETE",
      "/me/notes/{note_id}"
    ],
    "streamMyEvents": [
      "GET",
      "/me/events"
    ],
    "listMyNotifications": [
      "GET",
      "/me/notifications"
    ],
    "markMyNotificationsRead": [
      "POST",
      "/me/notifications/read"
    ],
    "getMyBookMarks": [
      "GET",
      "/me/book-marks"
    ],
    "getMyLibrary": [
      "GET",
      "/me/library"
    ],
    "listMySearches": [
      "GET",
      "/me/searches"
    ],
    "clearMySearches": [
      "DELETE",
      "/me/searches"
    ],
    "deleteMySearch": [
      "DELETE",
      "/me/searches/{search_id}"
    ],
    "getMyStats": [
      "GET",
      "/me/stats"
    ],
    "listMyClubs": [
      "GET",
      "/me/clubs"
    ],
    "listMyInvites": [
      "GET",
      "/me/invites"
    ],
    "answerMyInvite": [
      "POST",
      "/me/invites/{invite_id}/{decision}"
    ],
    "listMyReports": [
      "GET",
      "/me/reports"
    ],
    "getMyReadingSettings": [
      "GET",
      "/me/books/{book_id}/reading-settings"
    ],
    "saveMyReadingSettings": [
      "PATCH",
      "/me/books/{book_id}/reading-settings"
    ],
    "watchBook": [
      "PUT",
      "/me/watches/{book_id}"
    ],
    "unwatchBook": [
      "DELETE",
      "/me/watches/{book_id}"
    ],
    "setBookLabel": [
      "PUT",
      "/me/labels/{book_id}"
    ],
    "clearBookLabel": [
      "DELETE",
      "/me/labels/{book_id}"
    ],
    "listMyReaderProfiles": [
      "GET",
      "/me/reader-profiles"
    ],
    "recordMyActivity": [
      "POST",
      "/me/activity"
    ],
    "completeMyOnboarding": [
      "POST",
      "/me/onboarding"
    ],
    "listMyStarterBooks": [
      "GET",
      "/me/starter-shelf"
    ],
    "addBooksToMyShelf": [
      "POST",
      "/me/shelf/{shelf}/items"
    ]
  },
  "ops": {
    "opsListJobs": [
      "GET",
      "/ops/jobs"
    ],
    "opsGetJob": [
      "GET",
      "/ops/jobs/{job_id}"
    ],
    "opsRetryJob": [
      "POST",
      "/ops/jobs/{job_id}/retry"
    ],
    "opsRequeueJob": [
      "POST",
      "/ops/jobs/{job_id}/requeue"
    ],
    "opsCancelJob": [
      "POST",
      "/ops/jobs/{job_id}/cancel"
    ],
    "opsBumpJob": [
      "POST",
      "/ops/jobs/{job_id}/bump"
    ],
    "opsReprocessBook": [
      "POST",
      "/ops/books/{book_id}/reprocess"
    ],
    "opsListProcessingRequests": [
      "GET",
      "/ops/processing-requests"
    ],
    "opsApproveProcessingRequest": [
      "POST",
      "/ops/processing-requests/{request_id}/approve"
    ],
    "opsRejectProcessingRequest": [
      "POST",
      "/ops/processing-requests/{request_id}/reject"
    ],
    "opsGetOverview": [
      "GET",
      "/ops/overview"
    ],
    "opsGetTriage": [
      "GET",
      "/ops/triage"
    ],
    "opsGetMonitor": [
      "GET",
      "/ops/monitor"
    ],
    "opsListWorkflows": [
      "GET",
      "/ops/workflows"
    ],
    "opsRunWorkflow": [
      "POST",
      "/ops/workflows/{workflow_key}/run"
    ],
    "opsListNarrationReview": [
      "GET",
      "/ops/narration-review"
    ],
    "opsListSchedules": [
      "GET",
      "/ops/schedules"
    ],
    "opsUpdateSchedule": [
      "PATCH",
      "/ops/schedules/{schedule_id}"
    ],
    "opsGetLimits": [
      "GET",
      "/ops/limits"
    ],
    "opsUpdateLimits": [
      "PATCH",
      "/ops/limits"
    ],
    "opsGetModelPolicy": [
      "GET",
      "/ops/model-policy"
    ],
    "opsUpdateModelPolicy": [
      "PATCH",
      "/ops/model-policy/{kind}"
    ],
    "opsResetModelPolicy": [
      "POST",
      "/ops/model-policy/{kind}/reset"
    ],
    "opsGetCouncil": [
      "GET",
      "/ops/council"
    ],
    "opsUpdateCouncil": [
      "PATCH",
      "/ops/council"
    ],
    "opsGetHealth": [
      "GET",
      "/ops/health"
    ],
    "opsListErrors": [
      "GET",
      "/ops/errors"
    ],
    "opsHydrateCache": [
      "POST",
      "/ops/cache/hydrate"
    ],
    "opsRebuildGraphClosure": [
      "POST",
      "/ops/graph/rebuild-closure"
    ],
    "opsRelevelGraph": [
      "POST",
      "/ops/graph/relevel"
    ],
    "opsListAlerts": [
      "GET",
      "/ops/alerts"
    ],
    "opsAckAlert": [
      "POST",
      "/ops/alerts/{alert_id}/ack"
    ]
  },
  "premium": {
    "listPremiumPlans": [
      "GET",
      "/premium/plans"
    ],
    "getPremiumSubscription": [
      "GET",
      "/premium/subscription"
    ],
    "cancelPremiumSubscription": [
      "POST",
      "/premium/subscription/cancel"
    ],
    "resumePremiumSubscription": [
      "POST",
      "/premium/subscription/resume"
    ],
    "changePremiumSubscription": [
      "POST",
      "/premium/subscription/change"
    ],
    "createPremiumCheckout": [
      "POST",
      "/premium/checkout"
    ],
    "validatePremiumCheckout": [
      "POST",
      "/premium/checkout/{intent_id}/validate"
    ],
    "getPremiumBillingPortal": [
      "GET",
      "/premium/billing-portal"
    ],
    "createPremiumUpgradeRequest": [
      "POST",
      "/premium/upgrade-requests"
    ],
    "listMyPremiumUpgradeRequests": [
      "GET",
      "/premium/upgrade-requests/mine"
    ],
    "getPremiumCredits": [
      "GET",
      "/premium/credits"
    ],
    "listPremiumCreditLedger": [
      "GET",
      "/premium/credits/ledger"
    ],
    "getPremiumUsage": [
      "GET",
      "/premium/usage"
    ],
    "listPremiumInvoices": [
      "GET",
      "/premium/invoices"
    ],
    "getPremiumInvoice": [
      "GET",
      "/premium/invoices/{invoice_id}"
    ],
    "createPremiumQuote": [
      "POST",
      "/premium/quotes"
    ],
    "listPremiumOrders": [
      "GET",
      "/premium/orders"
    ],
    "createPremiumOrder": [
      "POST",
      "/premium/orders"
    ],
    "getPremiumOrder": [
      "GET",
      "/premium/orders/{order_id}"
    ],
    "listPremiumVoices": [
      "GET",
      "/premium/voices"
    ],
    "getPremiumAiSettings": [
      "GET",
      "/premium/ai-settings"
    ],
    "updatePremiumAiSettings": [
      "PATCH",
      "/premium/ai-settings"
    ],
    "getBillingAgreement": [
      "GET",
      "/premium/billing-agreement"
    ],
    "getBillingAgreementVersion": [
      "GET",
      "/premium/billing-agreement/versions/{version}"
    ],
    "acceptBillingAgreement": [
      "POST",
      "/premium/billing-agreement/acceptances"
    ],
    "getMyBillingStatement": [
      "GET",
      "/premium/statement"
    ],
    "listMyCharges": [
      "GET",
      "/premium/charges"
    ],
    "getMyMonthlyInvoice": [
      "GET",
      "/premium/monthly-invoices/{month}"
    ],
    "listMyPayments": [
      "GET",
      "/premium/payments"
    ],
    "getMyPayment": [
      "GET",
      "/premium/payments/{payment_id}"
    ],
    "listMyRefundRequests": [
      "GET",
      "/premium/refund-requests"
    ],
    "createMyRefundRequest": [
      "POST",
      "/premium/refund-requests"
    ],
    "setMyCreditLimit": [
      "PUT",
      "/premium/credit-limit"
    ],
    "listPaymentMethods": [
      "GET",
      "/premium/payment-methods"
    ],
    "listMyTopUps": [
      "GET",
      "/premium/top-ups"
    ],
    "createTopUp": [
      "POST",
      "/premium/top-ups"
    ],
    "getMyTopUp": [
      "GET",
      "/premium/top-ups/{top_up_id}"
    ],
    "markTopUpSent": [
      "POST",
      "/premium/top-ups/{top_up_id}/sent"
    ],
    "cancelTopUp": [
      "POST",
      "/premium/top-ups/{top_up_id}/cancel"
    ]
  },
  "super-admin": {
    "superAdminListRoles": [
      "GET",
      "/super-admin/roles"
    ],
    "superAdminListPermissions": [
      "GET",
      "/super-admin/permissions"
    ],
    "superAdminSetUserRoles": [
      "PUT",
      "/super-admin/users/{user_id}/roles"
    ],
    "superAdminListRoleLog": [
      "GET",
      "/super-admin/role-log"
    ],
    "superAdminStartImpersonation": [
      "POST",
      "/super-admin/impersonation"
    ],
    "superAdminEndImpersonation": [
      "DELETE",
      "/super-admin/impersonation"
    ],
    "superAdminListImpersonationLog": [
      "GET",
      "/super-admin/impersonation/log"
    ],
    "superAdminListFeatureFlags": [
      "GET",
      "/super-admin/feature-flags"
    ],
    "superAdminUpdateFeatureFlags": [
      "PATCH",
      "/super-admin/feature-flags"
    ],
    "superAdminSetUserFlags": [
      "PUT",
      "/super-admin/users/{user_id}/flags"
    ],
    "superAdminGetSiteSettings": [
      "GET",
      "/super-admin/site-settings"
    ],
    "superAdminUpdateSiteSettings": [
      "PATCH",
      "/super-admin/site-settings"
    ],
    "superAdminGetWatermark": [
      "GET",
      "/super-admin/watermark"
    ],
    "superAdminUpdateWatermark": [
      "PATCH",
      "/super-admin/watermark"
    ],
    "superAdminListKeys": [
      "GET",
      "/super-admin/keys"
    ],
    "superAdminRevokeKey": [
      "POST",
      "/super-admin/keys/{key_id}/revoke"
    ],
    "superAdminGetKeyRateLimits": [
      "GET",
      "/super-admin/rate-limits/{key_id}"
    ],
    "superAdminUpdateKeyRateLimits": [
      "PATCH",
      "/super-admin/rate-limits/{key_id}"
    ],
    "superAdminListAudit": [
      "GET",
      "/super-admin/audit"
    ],
    "superAdminListDocs": [
      "GET",
      "/super-admin/docs"
    ],
    "superAdminGetDoc": [
      "GET",
      "/super-admin/docs/{doc_id}"
    ]
  }
} as const;

export type Surface = keyof typeof OPERATIONS;
