// COPIED from ilm-red-unbound/packages/api-client by scripts/sync-api-client.mjs. Do not edit here.
// GENERATED by scripts/build-api-client.mjs from api/openapi/*.json. Do not edit by hand;
// change the contract in openapi/ and run `npm run api:spec`.

import type { operations as adminOps } from './types/admin';
import type { operations as aiOps } from './types/ai';
import type { operations as blogOps } from './types/blog';
import type { operations as booksOps } from './types/books';
import type { operations as clubsOps } from './types/clubs';
import type { operations as contentOps } from './types/content';
import type { operations as financeOps } from './types/finance';
import type { operations as meOps } from './types/me';
import type { operations as opsOps } from './types/ops';
import type { operations as premiumOps } from './types/premium';
import type { operations as superAdminOps } from './types/super-admin';

/** The generated `operations` interface of each surface, keyed by surface name. */
export interface SurfaceOperations {
  "admin": adminOps;
  "ai": aiOps;
  "blog": blogOps;
  "books": booksOps;
  "clubs": clubsOps;
  "content": contentOps;
  "finance": financeOps;
  "me": meOps;
  "ops": opsOps;
  "premium": premiumOps;
  "super-admin": superAdminOps;
}
